import React from 'react';
import Link from 'next/link';
import { listSupplierTargets } from '@/server/suppliers/store';

export const dynamic = 'force-dynamic';

export default async function RecruitmentQueuePage() {
  const targets = await listSupplierTargets();

  return (
    <div className="space-y-6">
      <div className="bg-white border border-slate-200 p-6 rounded-sm shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <span className="text-[10px] uppercase tracking-widest text-slate-500 font-light">
            PROACTIVE STRATEGY
          </span>
          <h1 className="text-2xl font-extralight text-slate-900 mt-1">
            Supplier Recruitment Queue
          </h1>
          <p className="text-xs text-slate-600 font-light mt-1">
            Strategic recruitment requirements generated by supply chain deficit analysis.
          </p>
        </div>

        <Link href="/admin/suppliers/targets" className="btn-primary text-xs py-2 px-4">
          View Target Partners Board
        </Link>
      </div>

      <div className="bg-white border border-slate-200 rounded-sm p-8 text-center text-xs text-slate-500 font-light shadow-sm">
        Recruitment requirements actively linked to {targets.length} target partners across Manchester, Leeds, and London.
      </div>
    </div>
  );
}
