import { NextRequest, NextResponse } from 'next/server';
import { getCurrentSession } from '@/server/identity';
import { dbQuery } from '@/server/db/client';
import { getEffectivePolicy, resolveRateHierarchy } from '@/server/commercial';

export async function POST(request: NextRequest) {
  const session = await getCurrentSession();
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const body = await request.json();
    const { transcript, visitId, workOrderId } = body;

    if (!transcript) {
      return NextResponse.json({ error: 'transcript is required' }, { status: 400 });
    }

    // 1. Assist Structuring (deterministic rule-based parse of voice transcript)
    const lower = transcript.toLowerCase();
    let estimatedHours = 2.0;
    let engineersCount = 1;

    // Simple heuristic parser for hours/engineers
    const hoursMatch = lower.match(/(\d+(?:\.\d+)?)\s*(?:hour|hr)s?/);
    if (hoursMatch) estimatedHours = parseFloat(hoursMatch[1]);

    const engMatch = lower.match(/(\d+)\s*(?:engineer|tech|man|person)s?/);
    if (engMatch) engineersCount = parseInt(engMatch[1], 10);

    // Extract potential parts
    const materials: Array<{ description: string; quantity: number }> = [];
    if (lower.includes('filter')) {
      materials.push({ description: 'Replacement air filter (F7 panel)', quantity: 2 });
    }
    if (lower.includes('belt') || lower.includes('fan belt')) {
      materials.push({ description: 'Drive belt replacement', quantity: 1 });
    }
    if (lower.includes('valve') || lower.includes('actuator')) {
      materials.push({ description: '2-port control valve actuator', quantity: 1 });
    }
    if (lower.includes('refrigerant') || lower.includes('gas')) {
      materials.push({ description: 'R410A Refrigerant (kg)', quantity: 2 });
    }

    // 2. Fetch context rate card info
    const policy = await getEffectivePolicy();
    const { rateCard, sourceName } = await resolveRateHierarchy({});

    return NextResponse.json({
      aiAgent: 'TALK_TO_QUOTE_AGENT',
      autonomyLevel: 'ASSIST',
      confidenceScore: 0.88,
      structuredProposal: {
        scopeDescription: transcript,
        labourEngineersCount: engineersCount,
        labourEstimatedHours: estimatedHours,
        materialsProposed: materials,
        resolvedRateCard: rateCard ? rateCard.name : null,
        rateSource: sourceName,
        targetMarginPct: policy.target_margin_pct,
      },
      disclaimer: 'This proposal is generated by TALK_TO_QUOTE_AGENT in ASSIST mode. No authoritative commercial commitments are made without human confirmation and rate card verification.',
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message || 'Internal server error' }, { status: 500 });
  }
}
