/**
 * CENTRAL GEO REGISTRY — ENTIREFM
 * =================================
 * Single source of truth for geographical operations, regional email desks,
 * districts, building stocks, local sector specialisms, and cross-references
 * to existing legacy service URLs.
 *
 * NON-NEGOTIABLE RULE:
 * Existing legacy URLs must remain untouched with status=200 and canonical=self.
 */

export interface GeoLocation {
  slug: string;
  name: string;
  region: string;
  tier: 1 | 2;
  email: string;
  tagline: string;
  metaDescription: string;
  districts: string[];
  propertyTypes: string[];
  keySectors: string[];
  surroundingAreas: string[];
  travelCorridors: string;
  legacyUrls: string[];
  serviceUrls: {
    serviceName: string;
    href: string;
    isExistingLegacy: boolean;
  }[];
  operatingContext: string;
  technicalChallenges: string[];
  faqs: {
    question: string;
    answer: string;
  }[];
}

export const GEO_LOCATIONS: Record<string, GeoLocation> = {
  london: {
    slug: 'london',
    name: 'London',
    region: 'Greater London & South East',
    tier: 1,
    email: 'london@entirefm.com',
    tagline: 'EntireFM London Regional Operations Hub — Engineering Coverage & Service Delivery Across Greater London',
    metaDescription: "Explore EntireFM's London operational coverage, engineering services, local FM delivery model and support for commercial properties across Greater London.",
    districts: [
      'City of London (EC2, EC3, EC4)',
      'Westminster & Victoria (SW1)',
      'Canary Wharf & Isle of Dogs (E14)',
      "King's Cross & Euston (N1C, NW1)",
      'Shoreditch & Clerkenwell (EC1, EC2A)',
      'Stratford & East London (E20)',
      'Hammersmith & West London (W6)',
      'Park Royal & Greenford (NW10, UB6)',
      'Croydon & South London (CR0)',
      'Greater London & M25 Corridor',
    ],
    propertyTypes: [
      'Multi-Tenant Commercial Office Towers',
      'Grade A Corporate Headquarters',
      'Listed & Conservation Area Commercial Buildings',
      'Converted Warehouses & Workspace',
      'Logistics Hubs & Light Industrial Parks',
      'Mixed-Use Commercial & Retail Estates',
    ],
    keySectors: [
      'Commercial Offices & Managing Agents',
      'Financial & Professional Services',
      'Retail & Shopping Centres',
      'Hospitality & Luxury Hotels',
      'Logistics & Light Industrial',
      'Public Sector & Higher Education',
    ],
    surroundingAreas: ['M25 Outer Ring', 'Heathrow Corridor', 'Thames Gateway', 'Docklands', 'West End', 'Midtown', 'City Fringe', 'North & South Circular'],
    travelCorridors: 'Strategic deployment via Zone 1–6 radial routes, North/South Circular, A40/M4 West corridor, and A13/M11 East gateway.',
    legacyUrls: [
      '/facilities-management-london',
      '/facilities-management-services-london',
      '/hard-facilities-management-london',
      '/soft-facilities-management-london',
      '/ppm-london',
      '/hvac-london',
      '/mechanical-electrical-london',
      '/commercial-cleaning-london',
      '/contract-cleaning-london',
      '/industrial-cleaning-london',
      '/reactive-maintenance-london',
      '/fm-london',
      '/london-facilities-management',
      '/london-facilities-management-areas',
      '/facilities-management-glossary-london',
    ],
    serviceUrls: [
      { serviceName: 'Facilities Management London (Flagship)', href: '/facilities-management-london', isExistingLegacy: true },
      { serviceName: 'Facilities Management Services London', href: '/facilities-management-services-london', isExistingLegacy: true },
      { serviceName: 'Hard FM & Mechanical Electrical', href: '/hard-facilities-management-london', isExistingLegacy: true },
      { serviceName: 'Planned Preventative Maintenance (PPM)', href: '/ppm-london', isExistingLegacy: true },
      { serviceName: 'Commercial HVAC & Chillers', href: '/hvac-london', isExistingLegacy: true },
      { serviceName: '24/7 Reactive Maintenance', href: '/reactive-maintenance-london', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning London', href: '/commercial-cleaning-london', isExistingLegacy: true },
      { serviceName: 'Statutory Compliance & EICR', href: '/compliance', isExistingLegacy: true },
      { serviceName: 'Outsourced FM London', href: '/fm-london', isExistingLegacy: true },
      { serviceName: 'Multi-Site Estate FM London', href: '/london-facilities-management', isExistingLegacy: true },
    ],
    operatingContext: 'EntireFM coordinates mobile engineering coverage, planned compliance attendance, and commercial property support across Greater London and the M25 corridor. Our London operations structure accounts for ULEZ emission controls, congestion windows, high-rise building services, tight loading bay access, and strict landlord permit-to-work protocols.',
    technicalChallenges: [
      'Managing out-of-hours access windows and landlord permit-to-work procedures for high-rise commercial towers and multi-tenant offices.',
      'Navigating ULEZ, Congestion Zone, and loading-bay logistics to maintain rapid 24/7 mobile engineering attendance across Central London.',
      'Executing SFG20 planned maintenance across complex mechanical & electrical plant, high-rise risers, and BMS controls.',
      'Maintaining digital compliance records in EntireCAFM for managing agents, institutional landlords, and corporate occupiers.',
    ],
    faqs: [
      {
        question: "What is the role of EntireFM's London Regional Operations Hub?",
        answer: 'The London Regional Operations Hub coordinates our mobile engineering fleet, 24/7 helpdesk response, and scheduled maintenance delivery across all 32 London boroughs and the M25 corridor, supporting commercial offices, retail estates, industrial facilities, and managing agents.',
      },
      {
        question: 'How does EntireFM manage logistics, ULEZ, and loading access across Central London?',
        answer: 'Our London engineering vans are fully ULEZ-compliant and dispatched strategically from regional corridors. For congested City and West End locations, we coordinate out-of-hours access, secure delivery loading permits, and liaise with building management teams to prevent tenant disruption.',
      },
      {
        question: 'Which commercial premises and property types do you support across London?',
        answer: 'We support Grade A corporate offices in the City and West End, high-rise towers in Canary Wharf, converted commercial workspace in Shoreditch and Southwark, industrial and logistics parks in Park Royal and Thames Gateway, and multi-tenant managed estates.',
      },
      {
        question: "Where can I view EntireFM's primary commercial London FM proposition?",
        answer: 'For our primary commercial London FM overview and contract scope, visit our flagship Facilities Management London page (/facilities-management-london), or explore our London Service Directory (/facilities-management-services-london).',
      },
    ],
  },

  manchester: {
    slug: 'manchester',
    name: 'Manchester',
    region: 'Greater Manchester & North West',
    tier: 1,
    email: 'manchester@entirefm.com',
    tagline: 'Integrated FM, M&E Engineering & Industrial Property Care Across Greater Manchester',
    metaDescription: 'EntireFM provides comprehensive facilities management, planned maintenance, M&E services, and industrial cleaning across Manchester, Salford, and the North West.',
    districts: ['Manchester City Centre', 'Spinningfields', 'Trafford Park', 'MediaCityUK', 'Salford Quays', 'Airport City Manchester', 'Ancoats', 'Didsbury', 'Stockport Commercial Corridor'],
    propertyTypes: ['Grade A Corporate Offices', 'Media & High-Tech Facilities', 'Heavy Industrial & Manufacturing Plants', 'Logistics Warehouses', 'Residential Build-to-Rent Blocks', 'Commercial Retail Parks'],
    keySectors: ['Commercial Offices & Tech Campuses', 'Manufacturing & Heavy Industry', 'Logistics & FMCG Distribution', 'Media & Digital Production', 'Higher Education & Student Accommodation', 'Retail & Leisure Estates'],
    surroundingAreas: ['Salford', 'Trafford', 'Stockport', 'Oldham', 'Rochdale', 'Bolton', 'Bury', 'Wigan', 'Altrincham', 'Warrington'],
    travelCorridors: 'Rapid response via the M60 orbital motorway, M602 Salford corridor, M56 airport link, and M62 trans-Pennine artery.',
    legacyUrls: ['/fm-manchester', '/facilities-management-manchester', '/manchester-facilities-management', '/commercial-cleaning-manchester', '/industrial-cleaning-manchester', '/contract-cleaning-manchester', '/external-cleaning-manchester', '/manchester-office-cleaning', '/pressure-washing-manchester', '/manchester-facilities-managment', '/facilities-management-glossary-manchester'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Planned Maintenance (PPM)', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning Manchester', href: '/commercial-cleaning-manchester', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning Manchester', href: '/industrial-cleaning-manchester', isExistingLegacy: true },
      { serviceName: 'HVAC & Climate Systems', href: '/hvac-contractor', isExistingLegacy: true },
      { serviceName: 'Working at Height & BMU', href: '/working-at-height-rope-access-bmu', isExistingLegacy: true },
      { serviceName: 'Fire & Life Safety', href: '/fire-emergency-systems', isExistingLegacy: true },
      { serviceName: 'Fabric Maintenance', href: '/building-maintenance', isExistingLegacy: true },
    ],
    operatingContext: 'Greater Manchester combines high-growth city centre commercial towers with massive continuous industrial manufacturing and distribution hubs across Trafford Park and the M62 corridor.',
    technicalChallenges: [
      'Plantroom climate control and AHU vibration monitoring in intensive MediaCity production hubs.',
      'Heavy degreasing, scrubber-drier operations, and high-level crane rail cleaning in Trafford Park.',
      'Managing high-turnover residential BTR compliance across modern skyline towers.',
      'Coordinating rapid M60 orbital emergency attendance during peak commuter traffic.',
    ],
    faqs: [
      {
        question: 'Which areas of Greater Manchester do EntireFM service engineers cover?',
        answer: 'Our mobile engineering and specialist maintenance teams cover Manchester city centre, Trafford Park, MediaCity, Salford Quays, Airport City, Stockport, Bolton, Bury, and surrounding North West commercial estates.',
      },
      {
        question: 'Can you deliver combined Hard FM and Industrial Cleaning for manufacturing sites in Manchester?',
        answer: 'Yes. We deliver Total FM contracts that unite M&E plantroom maintenance, statutory compliance testing, heavy factory degreasing, and external cladding washdowns under one transparent SLA.',
      },
    ],
  },

  birmingham: {
    slug: 'birmingham',
    name: 'Birmingham',
    region: 'West Midlands & Central England',
    tier: 1,
    email: 'birmingham@entirefm.com',
    tagline: 'Commercial FM, Building Services & Industrial Maintenance Across Birmingham & West Midlands',
    metaDescription: 'EntireFM delivers total facilities management, M&E engineering, statutory PPM, and specialist cleaning across Birmingham, Colmore Business District, and the West Midlands.',
    districts: ['Colmore Business District', 'Digbeth', 'Birmingham City Centre', 'NEC / Airport Corridor', 'Jewellery Quarter', 'Aston Advanced Manufacturing Hub', 'Longbridge Technology Park', 'Solihull Commercial Park'],
    propertyTypes: ['City Centre Commercial Offices', 'Advanced Engineering & Automotive Facilities', 'Multi-Bay Logistics Warehouses', 'Exhibition & Arena Venues', 'Retail Centres & High Streets', 'Healthcare & Clinical Buildings'],
    keySectors: ['Corporate & Professional Services', 'Advanced Automotive & Manufacturing', 'Logistics & Supply Chain Hubs', 'Events & Hospitality Venues', 'Higher Education Campuses', 'Public Sector & Healthcare'],
    surroundingAreas: ['Solihull', 'Wolverhampton', 'Walsall', 'Dudley', 'West Bromwich', 'Sutton Coldfield', 'Coventry', 'Telford', 'Redditch'],
    travelCorridors: 'Seamless mobility via the M6 expressway corridor, M42 logistics loop, M5 South West link, and A38(M) Aston Expressway.',
    legacyUrls: ['/fm-birmingham', '/facilities-management-birmingham', '/birmingham-facilities-management', '/commercial-cleaning-birmingham', '/industrial-cleaning-birmingham', '/external-cleaning-birmingham', '/pressure-washing-birmingham', '/facilities-management-glossary-birmingham', '/post/facilities-management-to-birmingham'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'PPM Maintenance Scheduling', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning Birmingham', href: '/commercial-cleaning-birmingham', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning Birmingham', href: '/industrial-cleaning-birmingham', isExistingLegacy: true },
      { serviceName: 'HVAC & Air Handling Systems', href: '/hvac-contractor', isExistingLegacy: true },
      { serviceName: 'Specialist Working at Height', href: '/working-at-height-rope-access-bmu', isExistingLegacy: true },
      { serviceName: 'Fire Protection Systems', href: '/fire-emergency-systems', isExistingLegacy: true },
    ],
    operatingContext: 'Birmingham represents Britain’s central industrial and commercial crossroads, featuring dense corporate office towers alongside extensive automotive manufacturing and nationwide logistics distribution.',
    technicalChallenges: [
      'High-bay lighting, busbar, and overhead crane maintenance in active automotive component plants.',
      'Managing Clean Air Zone (CAZ) compliance and delivery scheduling across Birmingham core.',
      'Large-scale commercial chillers and VRF air conditioning across Colmore Row corporate estates.',
      'Rapid out-of-hours turnaround for major exhibition spaces and event infrastructure.',
    ],
    faqs: [
      {
        question: 'Do EntireFM engineers operate inside the Birmingham Clean Air Zone (CAZ)?',
        answer: 'Yes, our mobile fleet is fully compliant with Clean Air Zone standards, ensuring unrestricted 24/7 access to central Birmingham commercial developments.',
      },
      {
        question: 'What Hard FM engineering capabilities do you self-deliver in Birmingham?',
        answer: 'We deliver comprehensive M&E services including HVAC maintenance, commercial boiler gas safety, EICR electrical testing, fire alarm servicing, plumbing, and building fabric repair.',
      },
    ],
  },

  leeds: {
    slug: 'leeds',
    name: 'Leeds',
    region: 'West Yorkshire & Yorkshire and the Humber',
    tier: 1,
    email: 'leeds@entirefm.com',
    tagline: 'Total Facilities Management & Technical Engineering Across Leeds & West Yorkshire',
    metaDescription: 'EntireFM provides high-performance facilities management, M&E engineering, PPM schedules, and commercial cleaning across Leeds and West Yorkshire commercial centres.',
    districts: ['Leeds City Centre', 'South Bank Regeneration Area', 'Wellington Place', 'Thorpe Park Business Park', 'Kirkstall Commercial Zone', 'Hunslet Industrial Estate', 'Leeds Valley Park', 'White Rose Office Park'],
    propertyTypes: ['Corporate Banking & Legal Headquarters', 'Digital & Tech Office Hubs', 'Manufacturing & Food Processing Plants', 'Distribution Warehouses', 'Higher Education Campuses', 'Medical & Research Facilities'],
    keySectors: ['Financial, Legal & Tech Services', 'Manufacturing & Food Production', 'E-Commerce & Regional Distribution', 'Higher Education & Student Living', 'Healthcare & Clinical Research', 'Commercial Retail Parks'],
    surroundingAreas: ['Bradford', 'Wakefield', 'Huddersfield', 'Halifax', 'Harrogate', 'York', 'Castleford', 'Pontefract'],
    travelCorridors: 'Direct strategic connectivity along the M62 trans-Pennine corridor, M1 North/South spine, and M621 city access.',
    legacyUrls: ['/fm-leeds', '/facilities-management-leeds', '/leeds-facilities-management', '/commercial-cleaning-leeds', '/industrial-cleaning-leeds', '/contract-cleaning-leeds', '/facilities-management-glossary-leeds'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Planned Preventative Maintenance', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning Leeds', href: '/commercial-cleaning-leeds', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning Leeds', href: '/industrial-cleaning-leeds', isExistingLegacy: true },
      { serviceName: 'HVAC & Climate Control', href: '/hvac-contractor', isExistingLegacy: true },
      { serviceName: 'Working at Height & Façade Access', href: '/working-at-height-rope-access-bmu', isExistingLegacy: true },
    ],
    operatingContext: 'Leeds boasts one of the UK’s premier legal, financial, and digital tech office clusters alongside a sprawling manufacturing and logistics base stretching along the Aire Valley and M621.',
    technicalChallenges: [
      'Maintaining high-spec BMS environmental controls in major financial headquarters.',
      'High-level façade cleaning and window maintenance on new South Bank commercial developments.',
      'Food-grade hygiene and factory deep cleaning across Aire Valley production plants.',
      'Managing heritage building fabric alongside state-of-the-art modern M&E services.',
    ],
    faqs: [
      {
        question: 'Can EntireFM manage multi-site commercial portfolios across Leeds and West Yorkshire?',
        answer: 'Yes. We manage estates spanning Leeds, Bradford, Wakefield, and York with centralised SLA tracking, digital compliance vaults, and live client reporting in EntireCAFM.',
      },
    ],
  },

  sheffield: {
    slug: 'sheffield',
    name: 'Sheffield',
    region: 'South Yorkshire & Sheffield City Region',
    tier: 1,
    email: 'sheffield@entirefm.com',
    tagline: 'Specialist FM Engineering, Industrial Care & Building Services Across Sheffield & South Yorkshire',
    metaDescription: 'EntireFM delivers bespoke facilities management, heavy engineering maintenance, PPM compliance, and industrial cleaning across Sheffield, Advanced Manufacturing Park, and South Yorkshire.',
    districts: ['Sheffield City Centre', 'Advanced Manufacturing Park (AMP)', 'Don Valley Commercial Corridor', 'Sheaf Valley', 'Kelham Island', 'Meadowhall Retail Zone', 'Holbrook Industrial Estate', 'Thorncliffe Business Park'],
    propertyTypes: ['Advanced Manufacturing & Metallurgy Facilities', 'Precision Engineering Works', 'Corporate Office Buildings', 'Regional Logistics Warehouses', 'Higher Education & Research Hubs', 'Retail & Leisure Complexes'],
    keySectors: ['Advanced Manufacturing & Aerospace Components', 'Heavy Engineering & Steel Fabrication', 'Higher Education & Medical Research', 'Retail & Leisure Properties', 'Commercial Offices & Technology', 'Logistics & Warehousing'],
    surroundingAreas: ['Rotherham', 'Doncaster', 'Barnsley', 'Chesterfield', 'Worksop', 'Peak District Borders', 'Dronfield'],
    travelCorridors: 'Rapid deployment via the M1 motorway (Junctions 31–36), Sheffield Parkway (A57), and Dearne Valley Link (A6195).',
    legacyUrls: ['/fm-sheffield', '/facilities-management-sheffield', '/sheffield-facilities-management', '/sheffield', '/commercial-cleaning-sheffield', '/industrial-cleaning-sheffield', '/contract-cleaning-sheffield', '/pressure-washing-sheffield', '/fm-services-sheffield', '/mobile-crane-hire/sheffield', '/facilities-management-glossary-sheffield'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Planned Maintenance Schedules', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning Sheffield', href: '/commercial-cleaning-sheffield', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning Sheffield', href: '/industrial-cleaning-sheffield', isExistingLegacy: true },
      { serviceName: 'Mobile Crane Hire & Plant Replacement', href: '/mobile-crane-hire/sheffield', isExistingLegacy: true },
      { serviceName: 'HVAC & Industrial Ductwork', href: '/hvac-contractor', isExistingLegacy: true },
      { serviceName: 'Working at Height & Rigging', href: '/working-at-height-rope-access-bmu', isExistingLegacy: true },
    ],
    operatingContext: 'Sheffield is the historic heart of precision engineering and metallurgy, featuring heavy industrial plantrooms, high-amperage electrical distributions, and cleanroom aerospace facilities alongside modern university and office assets.',
    technicalChallenges: [
      'Specialist contract lifts and plantroom equipment replacements via our direct crane division.',
      'LEV extraction, industrial swarf removal, and heavy factory degreasing across engineering bays.',
      'High-voltage switchgear testing, transformer inspections, and thermographic surveys.',
      'Strict health & safety isolation protocols for combined high-temperature manufacturing environments.',
    ],
    faqs: [
      {
        question: 'Do EntireFM provide crane hire and heavy plant replacement in Sheffield?',
        answer: 'Yes. Our specialized mobile crane hire and lifting operations team is based locally, delivering contract lifts, chiller replacements, and transformer rigging across South Yorkshire.',
      },
    ],
  },

  liverpool: {
    slug: 'liverpool',
    name: 'Liverpool',
    region: 'Liverpool City Region & Merseyside',
    tier: 1,
    email: 'liverpool@entirefm.com',
    tagline: 'Port & Maritime FM, Commercial M&E & Building Operations Across Liverpool & Merseyside',
    metaDescription: 'EntireFM provides dedicated facilities management, M&E engineering, statutory compliance, and commercial cleaning across Liverpool, Knowledge Quarter, and Merseyside commercial hubs.',
    districts: ['Commercial District & Old Hall Street', 'Liverpool Waterfront & Docks', 'Knowledge Quarter & Universities', 'Speke Boulevard Industrial Zone', 'Knowsley Business Park', 'Baltic Triangle', 'Liverpool ONE Retail Core'],
    propertyTypes: ['Waterfront Commercial Towers', 'Port & Maritime Logistics Warehouses', 'Pharmaceutical & Biotech Laboratories', 'Automotive Assembly Facilities', 'Higher Education Campuses', 'Heritage & Listed Commercial Buildings'],
    keySectors: ['Port, Maritime & Global Logistics', 'Life Sciences & Pharmaceutical Manufacturing', 'Corporate Offices & Creative Industries', 'Higher Education & Student Living', 'Automotive Manufacturing', 'Retail & Leisure Hubs'],
    surroundingAreas: ['Knowsley', 'Sefton', 'St Helens', 'Wirral / Birkenhead', 'Speke', 'Bootle', 'Halton / Widnes', 'Warrington'],
    travelCorridors: 'Direct strategic connectivity via the M62 corridor, M57 orbital, M58 Northern link, and Mersey Gateway / Queensway Tunnels.',
    legacyUrls: ['/fm-liverpool', '/facilities-management-liverpool', '/liverpool-facilities-management'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Planned Preventative Maintenance', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'HVAC & Refrigeration', href: '/hvac-contractor', isExistingLegacy: true },
      { serviceName: 'Working at Height & BMU', href: '/working-at-height-rope-access-bmu', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning Services', href: '/cleaning-services', isExistingLegacy: true },
      { serviceName: 'Industrial Plant Cleaning', href: '/industrial-cleaning', isExistingLegacy: true },
    ],
    operatingContext: 'Liverpool combines intense maritime port logistics and pharmaceutical cleanrooms with historic waterfront commercial assets and bustling university medical research faculties.',
    technicalChallenges: [
      'Marine-grade corrosion protection on external plant and façade access systems near the Mersey.',
      'Cleanroom HVAC balance and validated particulate control in Speke pharmaceutical plants.',
      'Heritage fabric preservation combined with modern M&E compliance in Grade I/II listed commercial blocks.',
      'Coordinating cross-river tunnel logistics for emergency engineering response between Liverpool and Wirral.',
    ],
    faqs: [
      {
        question: 'How do you handle coastal atmospheric corrosion on Liverpool waterfront buildings?',
        answer: 'We implement specialized anti-corrosion maintenance regimes for AHU coils, rooftop plant enclosures, and BMU cradle systems exposed to marine atmospheric conditions.',
      },
    ],
  },

  nottingham: {
    slug: 'nottingham',
    name: 'Nottingham',
    region: 'East Midlands & Nottinghamshire',
    tier: 1,
    email: 'nottingham@entirefm.com',
    tagline: 'Integrated FM, M&E Engineering & Property Maintenance Across Nottingham & East Midlands',
    metaDescription: 'EntireFM provides professional facilities management, planned maintenance, M&E services, and commercial cleaning across Nottingham and surrounding commercial business parks.',
    districts: ['Nottingham City Centre', 'Lenton Lane Industrial Corridor', 'Boots Campus / Enterprise Zone', 'Colwick Industrial Estate', 'NG2 Business Park', 'Beeston Tech Hub', 'Blenheim Industrial Park'],
    propertyTypes: ['Corporate Office Complexes', 'Life Sciences & Biotech Laboratories', 'Light Manufacturing & Assembly Works', 'Logistics Warehouses', 'Higher Education Campuses', 'Retail & Leisure Complexes'],
    keySectors: ['Life Sciences & Healthcare Technology', 'Digital, Financial & Professional Services', 'Higher Education & Student Accommodation', 'Light Manufacturing & Precision Assembly', 'Logistics & FMCG Distribution', 'Retail & Hospitality'],
    surroundingAreas: ['Mansfield', 'Newark-on-Trent', 'Grantham', 'Ilkeston', 'Hucknall', 'Loughborough', 'Derby Border Corridor', 'East Midlands Airport'],
    travelCorridors: 'Rapid mobility via the M1 motorway (Junctions 24–27), A52 Brian Clough Way, A453 Remembrance Way, and A610.',
    legacyUrls: ['/fm-nottingham', '/facilities-management-nottingham', '/nottingham-facilities-management', '/commercial-cleaning-nottingham', '/industrial-cleaning-nottingham'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'PPM Maintenance', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning Nottingham', href: '/commercial-cleaning-nottingham', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning Nottingham', href: '/industrial-cleaning-nottingham', isExistingLegacy: true },
      { serviceName: 'HVAC & Environmental Controls', href: '/hvac-contractor', isExistingLegacy: true },
      { serviceName: 'Working at Height', href: '/working-at-height-rope-access-bmu', isExistingLegacy: true },
    ],
    operatingContext: 'Nottingham is a vibrant commercial and life sciences centre, blending high-density university campuses with enterprise business parks and fast-growing logistics corridors along the M1.',
    technicalChallenges: [
      'Complex laboratory fume extraction, medical gas line testing, and pure water system compliance.',
      'Managing heritage multi-tenant Victorian mill conversions with updated M&E infrastructure.',
      'Coordinating rapid cross-city tram network and pedestrian zone access for maintenance crews.',
    ],
    faqs: [
      {
        question: 'Do EntireFM support bioscience and laboratory facilities in Nottingham?',
        answer: 'Yes. Our M&E technicians maintain precision climate systems, HEPA filtration, LEV extractors, and statutory compliance records for life science and research buildings.',
      },
    ],
  },

  derby: {
    slug: 'derby',
    name: 'Derby',
    region: 'East Midlands & Derbyshire',
    tier: 1,
    email: 'derby@entirefm.com',
    tagline: 'Engineering FM, Heavy Industry Maintenance & Facilities Services Across Derby & Derbyshire',
    metaDescription: 'EntireFM delivers advanced facilities management, M&E engineering, statutory PPM compliance, and industrial cleaning across Derby, Pride Park, and Derbyshire industrial estates.',
    districts: ['Derby City Centre', 'Pride Park Business Estate', 'Infinity Park Derby (Enterprise Zone)', 'Sinfin Manufacturing Corridor', 'Raynesway Industrial Hub', 'Ascot Drive Commercial Area', 'Manskip Industrial Zone'],
    propertyTypes: ['Aerospace & Rail Engineering Complexes', 'Heavy Manufacturing & Assembly Plants', 'Technology & Office Parks', 'Regional Logistics Hubs', 'Automotive Supply Facilities', 'Commercial Office Buildings'],
    keySectors: ['Aerospace Engineering & Turbine Technology', 'Rail Transport & Rolling Stock Manufacturing', 'Advanced Automotive Supply', 'Precision Engineering & Metallurgy', 'Logistics & Warehousing', 'Commercial Offices'],
    surroundingAreas: ['Burton upon Trent', 'Ashbourne', 'Belper', 'Ilkeston', 'Swadlincote', 'Ripley', 'East Midlands Airport Corridor', 'Matlock'],
    travelCorridors: 'Superb logistics connectivity via the A52, A38 dual carriageway spine, A50 trunk route, and M1 Junction 25.',
    legacyUrls: ['/fm-derby', '/facilities-management-derby', '/derby-facilities-management', '/industrial-cleaning-derby'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Statutory PPM Scheduling', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning Derby', href: '/industrial-cleaning-derby', isExistingLegacy: true },
      { serviceName: 'HVAC & Process Cooling', href: '/hvac-contractor', isExistingLegacy: true },
      { serviceName: 'Working at Height & Rigging', href: '/working-at-height-rope-access-bmu', isExistingLegacy: true },
      { serviceName: 'Fire & Emergency Systems', href: '/fire-emergency-systems', isExistingLegacy: true },
    ],
    operatingContext: 'Derby is Britain’s foremost centre for aerospace and rail engineering excellence, home to heavy production halls, high-precision clean rooms, and extensive testing infrastructure.',
    technicalChallenges: [
      'High-pressure compressed air, process cooling, and industrial gas distribution testing.',
      'Heavy factory shutdown cleans, machine degreasing, and overhead purlin de-dusting.',
      'Strict security vetting, foreign object damage (FOD) prevention, and safety isolation in aerospace facilities.',
    ],
    faqs: [
      {
        question: 'Are EntireFM engineers trained to work in high-security aerospace and rail engineering plants in Derby?',
        answer: 'Yes, our engineering teams operate under strict permit-to-work protocols, hold appropriate trade certifications, and are trained in safety isolation for sensitive industrial sites.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // TIER 2 CITIES (13 CITIES)
  // ─────────────────────────────────────────────────────────────────────────────

  oxford: {
    slug: 'oxford',
    name: 'Oxford',
    region: 'Oxfordshire & Thames Valley',
    tier: 2,
    email: 'oxford@entirefm.com',
    tagline: 'Life Science FM, University Estate Maintenance & Commercial Services Across Oxford',
    metaDescription: 'EntireFM provides specialist facilities management, M&E engineering, laboratory compliance, and commercial cleaning across Oxford Science Park, Headington, and Oxfordshire.',
    districts: ['Oxford City Centre', 'Oxford Science Park', 'Milton Park', 'Headington Biomedical Hub', 'Cowley Commercial Corridor', 'Begbroke Science Park', 'Osney Mead'],
    propertyTypes: ['Biomedical & Life Science Laboratories', 'Academic & Collegiate Buildings', 'Automotive Assembly Works', 'Technology Research Incubators', 'Commercial Offices', 'Healthcare Facilities'],
    keySectors: ['Life Sciences & Biotechnology', 'Higher Education & Academic Research', 'Automotive & Advanced Technology', 'Healthcare & Clinical Services', 'Commercial Property & Offices'],
    surroundingAreas: ['Abingdon', 'Didcot', 'Bicester', 'Witney', 'Banbury', 'Thame', 'Kidlington'],
    travelCorridors: 'Direct coverage via the A34 spine, A40 East/West corridor, and M40 motorway link.',
    legacyUrls: ['/fm-oxford', '/facilities-management-oxford', '/oxford-facilities-management'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'PPM Schedules & SFG20', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'HVAC & Laboratory Air Control', href: '/hvac-contractor', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning', href: '/cleaning-services', isExistingLegacy: true },
      { serviceName: 'Compliance Vault Management', href: '/compliance', isExistingLegacy: true },
    ],
    operatingContext: 'Oxford demands ultra-precise environmental control for cutting-edge bioscience research facilities alongside historic collegiate preservation.',
    technicalChallenges: ['Precision laboratory air balancing and HEPA validation', 'Listed collegiate fabric maintenance', 'Zero-emission delivery routing in Oxford central zone'],
    faqs: [{ question: 'Do you service laboratories at Oxford Science Park?', answer: 'Yes, we provide M&E maintenance, LEV inspections, and statutory compliance testing for biotech campuses across Oxford.' }],
  },

  bradford: {
    slug: 'bradford',
    name: 'Bradford',
    region: 'West Yorkshire',
    tier: 2,
    email: 'bradford@entirefm.com',
    tagline: 'Industrial FM, Commercial Cleaning & Building Maintenance Across Bradford & West Yorkshire',
    metaDescription: 'EntireFM delivers total facilities management, M&E maintenance, factory cleaning, and building fabric care across Bradford, Canal Road corridor, and surrounding districts.',
    districts: ['Bradford City Centre', 'Canal Road Industrial Corridor', 'Euroway Commercial Park', 'Low Moor Industrial Zone', 'Thornbury', 'Bowling Back Lane'],
    propertyTypes: ['Textile & Chemical Processing Mills', 'Modern Logistics Warehouses', 'Commercial Offices', 'Retail Parks', 'Educational Facilities'],
    keySectors: ['Manufacturing & Chemicals', 'Logistics & Warehousing', 'Commercial Offices', 'Public Sector & Education', 'Retail'],
    surroundingAreas: ['Shipley', 'Bingley', 'Keighley', 'Pudsey', 'Halifax', 'Leeds Border'],
    travelCorridors: 'Connected via the M606 motorway link, M62 trans-Pennine artery, and A650 / A647.',
    legacyUrls: ['/fm-bradford', '/facilities-management-bradford', '/bradford-facilities-management'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Planned Preventative Maintenance', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning', href: '/industrial-cleaning', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning', href: '/cleaning-services', isExistingLegacy: true },
    ],
    operatingContext: 'Bradford blends massive multi-storey historic manufacturing mills with high-volume modern logistics warehousing off the M606.',
    technicalChallenges: ['High-level masonry inspection and heritage mill roof repairs', 'Heavy chemical degreasing and ATEX compliance in manufacturing bays'],
    faqs: [{ question: 'Can EntireFM service industrial facilities in Bradford?', answer: 'Yes, we provide complete Hard and Soft FM services across all Bradford industrial corridors.' }],
  },

  doncaster: {
    slug: 'doncaster',
    name: 'Doncaster',
    region: 'South Yorkshire',
    tier: 2,
    email: 'doncaster@entirefm.com',
    tagline: 'Logistics FM, Rail Maintenance & Commercial Property Services Across Doncaster',
    metaDescription: 'EntireFM provides comprehensive facilities management, warehouse M&E engineering, dock maintenance, and industrial cleaning across Doncaster logistics hubs.',
    districts: ['Doncaster City Centre', 'iPort Logistics Hub', 'Lakeside Business Park', 'Wheatley Hall Commercial Strip', 'Redhouse Interchange', 'Carcroft Industrial Estate'],
    propertyTypes: ['Mega-Distribution Centres', 'Rail Freight & Engineering Depots', 'Commercial Business Parks', 'Retail Complexes', 'Manufacturing Works'],
    keySectors: ['Logistics & Supply Chain Hubs', 'Rail Engineering', 'Manufacturing', 'Retail & Commercial Offices'],
    surroundingAreas: ['Rotherham', 'Barnsley', 'Scunthorpe', 'Bawtry', 'Goole', 'Thorne'],
    travelCorridors: 'Superb freight mobility via the M18, A1(M), M180, and M62 East link.',
    legacyUrls: ['/fm-doncaster', '/facilities-management-doncaster', '/doncaster-facilities-management'],
    serviceUrls: [
      { serviceName: 'Planned Preventative Maintenance', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning', href: '/industrial-cleaning', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning', href: '/cleaning-services', isExistingLegacy: true },
    ],
    operatingContext: 'Doncaster is one of the UK’s premier strategic logistics and rail hubs, home to massive continuous distribution centres requiring 24/7 uptime.',
    technicalChallenges: ['Dock leveller, rapid-roller shutter, and high-bay lighting PPM', 'Industrial floor scrubbing across 500,000+ sq ft warehouse slabs'],
    faqs: [{ question: 'Do you manage facilities at Doncaster iPort?', answer: 'Yes, our mobile crews provide 24/7 M&E, compliance, and industrial cleaning across Doncaster iPort and surrounding parks.' }],
  },

  rotherham: {
    slug: 'rotherham',
    name: 'Rotherham',
    region: 'South Yorkshire',
    tier: 2,
    email: 'rotherham@entirefm.com',
    tagline: 'Industrial Engineering FM & Commercial Facilities Management Across Rotherham',
    metaDescription: 'EntireFM delivers expert facilities management, heavy plantroom maintenance, EICR compliance, and industrial cleaning across Rotherham and Advanced Manufacturing Park.',
    districts: ['Rotherham Town Centre', 'Advanced Manufacturing Park (AMP)', 'Manvers Commercial Park', 'Templeborough Industrial Zone', 'Parkgate Retail World', 'Barbot Hall'],
    propertyTypes: ['High-Tech Engineering Centres', 'Steel & Metal Fabrication Plants', 'Call Centres & Commercial Offices', 'Retail Parks', 'Logistics Warehouses'],
    keySectors: ['Advanced Engineering & Materials', 'Steel & Metallurgy', 'Logistics & Warehousing', 'Commercial Offices & Retail'],
    surroundingAreas: ['Sheffield', 'Doncaster', 'Barnsley', 'Worksop', 'Dearne Valley'],
    travelCorridors: 'Direct access via M1 Junctions 33–34, M18, and A630 Sheffield-Rotherham Link.',
    legacyUrls: ['/fm-rotherham', '/facilities-management-rotherham', '/rotherham-facilities-management'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'PPM Maintenance', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning', href: '/industrial-cleaning', isExistingLegacy: true },
      { serviceName: 'Mobile Crane Hire', href: '/mobile-crane-hire', isExistingLegacy: true },
    ],
    operatingContext: 'Rotherham features cutting-edge aerospace materials research at AMP alongside traditional metallurgy and high-density customer service office campuses.',
    technicalChallenges: ['High-voltage switchgear testing and power quality monitoring', 'Heavy plant replacement and rigging in active fabrication works'],
    faqs: [{ question: 'Do you service companies at the Advanced Manufacturing Park (AMP)?', answer: 'Yes, we support AMP facilities with certified M&E engineering, statutory compliance, and precision cleaning.' }],
  },

  chesterfield: {
    slug: 'chesterfield',
    name: 'Chesterfield',
    region: 'Derbyshire & Peak District Gateway',
    tier: 2,
    email: 'chesterfield@entirefm.com',
    tagline: 'Commercial FM, Heavy Plant Lifting & Building Services Across Chesterfield & Derbyshire',
    metaDescription: 'EntireFM provides comprehensive facilities management, mobile crane hire, M&E maintenance, and commercial cleaning across Chesterfield and Derbyshire commercial estates.',
    districts: ['Chesterfield Town Centre', 'Chesterfield Waterside', 'Markham Vale Logistics Hub', 'Sheepbridge Industrial Estate', 'Whittington Moor', 'Holmewood Industrial Park'],
    propertyTypes: ['Logistics & Supply Chain Hubs', 'Engineering & Fabrication Works', 'Commercial Offices', 'Retail Complexes', 'Business Incubation Centres'],
    keySectors: ['Logistics & Distribution', 'Precision Engineering & Fabrication', 'Commercial Offices', 'Retail & Leisure'],
    surroundingAreas: ['Sheffield', 'Dronfield', 'Matlock', 'Clay Cross', 'Bolsover', 'Staveley'],
    travelCorridors: 'Direct transit via the M1 (Junctions 29–30), A61 bypass, and A619.',
    legacyUrls: ['/fm-chesterfield', '/facilities-management-chesterfield', '/chesterfield-facilities-management', '/chesterfield', '/commercial-cleaning-chesterfield', '/industrial-cleaning-chesterfield', '/contract-cleaning-chesterfield', '/mobile-crane-hire/chesterfield', '/facilities-management-glossary-chesterfield'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Planned Preventative Maintenance', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning Chesterfield', href: '/commercial-cleaning-chesterfield', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning Chesterfield', href: '/industrial-cleaning-chesterfield', isExistingLegacy: true },
      { serviceName: 'Mobile Crane Hire Chesterfield', href: '/mobile-crane-hire/chesterfield', isExistingLegacy: true },
    ],
    operatingContext: 'Chesterfield is a primary operational base for EntireFM, combining historic engineering links with the major Markham Vale M1 logistics gateway.',
    technicalChallenges: ['Contract crane lifting for plant replacements', '24/7 logistics maintenance at Markham Vale'],
    faqs: [{ question: 'Are EntireFM crane and lifting teams based in Chesterfield?', answer: 'Yes, our specialist mobile crane hire and lifting operations division operates directly from our Chesterfield base.' }],
  },

  lincoln: {
    slug: 'lincoln',
    name: 'Lincoln',
    region: 'Lincolnshire & East Coast',
    tier: 2,
    email: 'lincoln@entirefm.com',
    tagline: 'Commercial Facilities Management & Engineering Operations Across Lincoln & Lincolnshire',
    metaDescription: 'EntireFM delivers total facilities management, planned maintenance, industrial cleaning, and M&E services across Lincoln, Allenby Industrial Estate, and Lincolnshire.',
    districts: ['Lincoln City Centre', 'Allenby Road Industrial Estate', 'Teal Park Business Zone', 'Doddington Road Commercial Corridor', 'Bishop’s Grosseteste University Campus', 'Lincoln Science & Innovation Park'],
    propertyTypes: ['Engineering & Turbine Manufacturing Plants', 'Food Processing & Agritech Facilities', 'University & Educational Campuses', 'Commercial Office Buildings', 'Heritage & Cathedral Quarter Buildings'],
    keySectors: ['Heavy Engineering & Power Generation', 'Agritech & Food Manufacturing', 'Higher Education & Research', 'Public Sector & Healthcare', 'Commercial Property & Retail'],
    surroundingAreas: ['Newark-on-Trent', 'Gainsborough', 'Sleaford', 'Scunthorpe', 'Grantham', 'Market Rasen', 'Louth'],
    travelCorridors: 'Connected via the A46 dual carriageway bypass, A15 North/South link, and A57.',
    legacyUrls: ['/fm-lincoln', '/facilities-management-lincoln', '/lincoln-facilities-management', '/commercial-cleaning-lincoln', '/industrial-cleaning-lincoln', '/contract-cleaning-lincoln', '/external-cleaning-lincoln', '/office-cleaning-lincoln', '/pressure-washing-lincoln', '/commercial-fm-lincoln', '/industrial-fm-lincoln', '/residential-fm-lincoln', '/retail-fm-lincoln', '/lincoln-facilities-management-areas', '/facilities-management-glossary-lincoln', '/post/facilities-management-services-in-lincoln'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Planned Preventative Maintenance (PPM)', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning Lincoln', href: '/commercial-cleaning-lincoln', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning Lincoln', href: '/industrial-cleaning-lincoln', isExistingLegacy: true },
      { serviceName: 'HVAC & Commercial Gas', href: '/hvac-contractor', isExistingLegacy: true },
      { serviceName: 'Building Fabric Maintenance', href: '/building-maintenance', isExistingLegacy: true },
    ],
    operatingContext: 'Lincoln has long been an anchor market for EntireFM, blending world-class industrial turbine manufacturing with agritech processing and historic civic architecture.',
    technicalChallenges: ['Managing food safety hygiene and drainage compliance in agritech plants', 'Specialist turbine hall ventilation and high-load power management'],
    faqs: [{ question: 'Does EntireFM provide comprehensive FM across Lincolnshire?', answer: 'Yes, we have deep roots in Lincoln, servicing industrial plants, universities, and commercial offices across the county.' }],
  },

  bolton: {
    slug: 'bolton',
    name: 'Bolton',
    region: 'Greater Manchester',
    tier: 2,
    email: 'bolton@entirefm.com',
    tagline: 'Commercial FM, Industrial Maintenance & Cleaning Across Bolton & North West',
    metaDescription: 'EntireFM provides dedicated facilities management, M&E engineering, statutory compliance, and commercial cleaning across Bolton and surrounding industrial corridors.',
    districts: ['Bolton Town Centre', 'Middlebrook Commercial Park', 'Logistics North Business Park', 'Lostock Industrial Estate', 'Breightmet Commercial Area', 'Wingates Industrial Park'],
    propertyTypes: ['Modern Distribution Hubs', 'Retail & Stadium Complexes', 'Manufacturing Facilities', 'Commercial Offices', 'Healthcare Clinics'],
    keySectors: ['Logistics & Warehousing', 'Retail & Leisure Estates', 'Light Engineering', 'Commercial Offices & Public Sector'],
    surroundingAreas: ['Bury', 'Wigan', 'Chorley', 'Salford', 'Manchester Border'],
    travelCorridors: 'Fast access via the M61 motorway, A666 St Peter’s Way, and M60 ring road.',
    legacyUrls: ['/fm-bolton', '/facilities-management-bolton', '/bolton-facilities-management'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Planned Preventative Maintenance', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning', href: '/cleaning-services', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning', href: '/industrial-cleaning', isExistingLegacy: true },
    ],
    operatingContext: 'Bolton is home to major national retail hubs like Middlebrook and the colossal Logistics North development off the M61.',
    technicalChallenges: ['High-throughput logistics warehouse maintenance', 'Large-format retail estate compliance'],
    faqs: [{ question: 'Do EntireFM engineers service Logistics North in Bolton?', answer: 'Yes, we support major distribution and manufacturing facilities at Logistics North with 24/7 FM cover.' }],
  },

  bury: {
    slug: 'bury',
    name: 'Bury',
    region: 'Greater Manchester',
    tier: 2,
    email: 'bury@entirefm.com',
    tagline: 'Commercial Facilities Management & Industrial Services Across Bury & North Manchester',
    metaDescription: 'EntireFM delivers reliable facilities management, M&E maintenance, statutory testing, and commercial cleaning across Bury and North Manchester commercial parks.',
    districts: ['Bury Town Centre', 'Pilsworth Commercial Park', 'Bridge Hall Industrial Estate', 'Chamberhall Business Park', 'Fishpool Industrial Zone', 'Radcliffe Commercial Corridor'],
    propertyTypes: ['Paper & Chemical Processing Plants', 'Distribution Warehouses', 'Commercial Retail Parks', 'Offices & Business Centres', 'Public Sector Buildings'],
    keySectors: ['Manufacturing & Processing', 'Logistics & Distribution', 'Retail & Commercial Offices', 'Healthcare & Education'],
    surroundingAreas: ['Bolton', 'Rochdale', 'Prestwich', 'Whitefield', 'Ramsbottom', 'Manchester City Centre'],
    travelCorridors: 'Connected via the M66 motorway corridor, M60 ring road, and A56 Manchester Road.',
    legacyUrls: ['/fm-bury', '/facilities-management-bury', '/bury-facilities-management'],
    serviceUrls: [
      { serviceName: 'Planned Maintenance', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning', href: '/cleaning-services', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning', href: '/industrial-cleaning', isExistingLegacy: true },
    ],
    operatingContext: 'Bury combines traditional heavy industrial manufacturing along the Irwell valley with modern commercial parks off the M66.',
    technicalChallenges: ['Industrial wastewater drainage and interceptor maintenance', 'Commercial retail compliance testing'],
    faqs: [{ question: 'What FM services do you provide in Bury?', answer: 'We deliver Hard FM engineering, statutory compliance testing, commercial cleaning, and building maintenance across Bury.' }],
  },

  preston: {
    slug: 'preston',
    name: 'Preston',
    region: 'Lancashire & Central North West',
    tier: 2,
    email: 'preston@entirefm.com',
    tagline: 'Total Facilities Management & Engineering Maintenance Across Preston & Lancashire',
    metaDescription: 'EntireFM provides expert facilities management, M&E engineering, statutory compliance, and industrial cleaning across Preston, Samlesbury Aerospace hub, and Central Lancashire.',
    districts: ['Preston City Centre', 'Samlesbury Aerospace Enterprise Zone', 'Red Scar Business Park', 'Roman Way Industrial Estate', 'Preston Docks Commercial Area', 'Walton Summit Centre'],
    propertyTypes: ['Aerospace & Defence Manufacturing Facilities', 'High-Volume Logistics Warehouses', 'University & Higher Education Blocks', 'Corporate Offices', 'Public Sector & Healthcare Estates'],
    keySectors: ['Aerospace & Defence', 'Logistics & Distribution', 'Higher Education (UCLan)', 'Public Sector & NHS', 'Commercial Offices'],
    surroundingAreas: ['Blackburn', 'Blackpool', 'Lancaster', 'Chorley', 'Leyland', 'Southport'],
    travelCorridors: 'Strategic crossroads via M6 (Junctions 31–32), M65 East Lancashire spine, and M55 coastal link.',
    legacyUrls: ['/fm-preston', '/facilities-management-preston', '/preston-facilities-management'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Planned Preventative Maintenance', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'HVAC & Environmental Controls', href: '/hvac-contractor', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning', href: '/industrial-cleaning', isExistingLegacy: true },
    ],
    operatingContext: 'Preston serves as Lancashire’s commercial and advanced defence engineering capital, anchored by UCLan and the Samlesbury aerospace campus.',
    technicalChallenges: ['Defence-grade security compliance and facility access', 'Managing high-density university campus infrastructure'],
    faqs: [{ question: 'Do EntireFM provide 24/7 emergency engineering in Preston?', answer: 'Yes, our mobile crews cover Preston and the M6 Lancashire corridor with contracted 24/7 SLAs.' }],
  },

  wigan: {
    slug: 'wigan',
    name: 'Wigan',
    region: 'Greater Manchester & Lancashire Border',
    tier: 2,
    email: 'wigan@entirefm.com',
    tagline: 'Logistics FM, Industrial Maintenance & Commercial Cleaning Across Wigan',
    metaDescription: 'EntireFM provides comprehensive facilities management, warehouse M&E engineering, PPM compliance, and industrial cleaning across Wigan and M6 commercial parks.',
    districts: ['Wigan Town Centre', 'Pemberton Commercial Zone', 'South Lancashire Industrial Estate', 'Martland Park', 'Hindley Green Commercial Area', 'Westwood Park'],
    propertyTypes: ['Food Production & Packaging Plants', 'E-Commerce Logistics Hubs', 'Light Manufacturing Works', 'Commercial Offices', 'Retail Complexes'],
    keySectors: ['Food & Beverage Manufacturing', 'Logistics & Warehousing', 'Light Engineering', 'Commercial Offices & Retail'],
    surroundingAreas: ['Bolton', 'St Helens', 'Warrington', 'Leigh', 'Skelmersdale', 'Standish'],
    travelCorridors: 'Exceptional logistics access via M6 (Junctions 25–27), M58, and A577.',
    legacyUrls: ['/fm-wigan', '/facilities-management-wigan', '/wigan-facilities-management'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Planned Preventative Maintenance', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning', href: '/industrial-cleaning', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning', href: '/cleaning-services', isExistingLegacy: true },
    ],
    operatingContext: 'Wigan occupies a prime logistical location on the M6 corridor, supporting extensive food manufacturing and regional distribution centres.',
    technicalChallenges: ['Food hygiene compliance, grease trap maintenance, and cold storage refrigeration', 'High-bay warehouse electrical inspections'],
    faqs: [{ question: 'Can you service food manufacturing plants in Wigan?', answer: 'Yes, our teams deliver certified food-grade M&E and deep cleaning aligned to BRCGS standards.' }],
  },

  grimsby: {
    slug: 'grimsby',
    name: 'Grimsby',
    region: 'North East Lincolnshire & Humber Bank',
    tier: 2,
    email: 'grimsby@entirefm.com',
    tagline: 'Port FM, Renewable Energy Support & Cold Storage Maintenance Across Grimsby & Cleethorpes',
    metaDescription: 'EntireFM delivers specialist facilities management, commercial refrigeration maintenance, industrial cleaning, and M&E services across Grimsby and the Humber Bank.',
    districts: ['Grimsby Town Centre', 'Port of Grimsby & Fish Docks', 'Europarc Commercial Centre', 'South Humberside Industrial Estate', 'Pyewipe Industrial Corridor', 'Great Coates'],
    propertyTypes: ['Cold Storage & Food Processing Facilities', 'Offshore Wind Operations & Maintenance Bases', 'Chemical & Petrochemical Processing Plants', 'Port Logistics Warehouses', 'Commercial Offices'],
    keySectors: ['Food Processing & Cold Chain Logistics', 'Offshore Wind & Renewable Energy', 'Port & Maritime Operations', 'Chemical Processing', 'Commercial Offices'],
    surroundingAreas: ['Cleethorpes', 'Immingham', 'Scunthorpe', 'Louth', 'Hull Border (via Humber Bridge)'],
    travelCorridors: 'Connected via the A180 expressway, A46 South link, and M180.',
    legacyUrls: ['/fm-grimsby', '/facilities-management-grimsby', '/grimsby-facilities-management'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Commercial Refrigeration & HVAC', href: '/hvac-contractor', isExistingLegacy: true },
      { serviceName: 'Planned Preventative Maintenance', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Industrial Plant Cleaning', href: '/industrial-cleaning', isExistingLegacy: true },
    ],
    operatingContext: 'Grimsby is the UK’s leading cold-chain food processing hub and a world capital for offshore wind operations and maintenance bases.',
    technicalChallenges: ['Industrial ammonia/F-Gas cold store refrigeration maintenance', 'Corrosive marine environment maintenance on port infrastructure'],
    faqs: [{ question: 'Do EntireFM maintain commercial cold storage facilities in Grimsby?', answer: 'Yes, our F-Gas certified refrigeration and M&E engineers maintain food-processing cold stores across Europarc and South Humberside.' }],
  },

  telford: {
    slug: 'telford',
    name: 'Telford',
    region: 'Shropshire & West Midlands Border',
    tier: 2,
    email: 'telford@entirefm.com',
    tagline: 'Advanced Manufacturing FM, Automotive Maintenance & Building Services Across Telford',
    metaDescription: 'EntireFM provides full facilities management, M&E engineering, industrial plant cleaning, and PPM compliance across Telford, Stafford Park, and Halesfield.',
    districts: ['Telford Town Centre', 'Stafford Park Commercial Estate', 'Halesfield Industrial Estate', 'Hortonwood Industrial Park', 'T54 Advanced Manufacturing Park', 'Hadley Park'],
    propertyTypes: ['Advanced Manufacturing & Plastics Facilities', 'Automotive Supply Plants', 'Electronics Assembly Works', 'Logistics Warehouses', 'Commercial Offices'],
    keySectors: ['Advanced Manufacturing & Polymers', 'Automotive Supply Chain', 'Logistics & Warehousing', 'Electronics & Technology', 'Commercial Offices'],
    surroundingAreas: ['Shrewsbury', 'Wolverhampton', 'Bridgnorth', 'Newport', 'Oswestry', 'Stafford Border'],
    travelCorridors: 'Direct strategic spine via the M54 motorway, A5, and A442 Queensway.',
    legacyUrls: ['/fm-telford', '/facilities-management-telford', '/telford-facilities-management', '/facilities-management-in-telford'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Planned Preventative Maintenance', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Industrial Cleaning', href: '/industrial-cleaning', isExistingLegacy: true },
      { serviceName: 'HVAC & Process Cooling', href: '/hvac-contractor', isExistingLegacy: true },
    ],
    operatingContext: 'Telford is Shropshire’s industrial economic powerhouse, home to extensive polymer, automotive, and electronic precision manufacturing plants.',
    technicalChallenges: ['Process cooling, chiller maintenance, and pneumatic distribution', 'Heavy factory floor scrubbing and oil mist extraction'],
    faqs: [{ question: 'Do you cover industrial estates across Telford?', answer: 'Yes, we provide 24/7 facilities management and M&E maintenance across Stafford Park, Halesfield, Hortonwood, and T54.' }],
  },

  matlock: {
    slug: 'matlock',
    name: 'Matlock',
    region: 'Derbyshire Dales & Peak District',
    tier: 2,
    email: 'matlock@entirefm.com',
    tagline: 'Commercial Property FM, Quarrying Services & Building Maintenance Across Derbyshire Dales',
    metaDescription: 'EntireFM provides trusted facilities management, M&E maintenance, building fabric repairs, and commercial cleaning across Matlock, Bakewell, and the Derbyshire Dales.',
    districts: ['Matlock Town Centre', 'Cawdor Quarry Commercial Area', 'Twiggs Commercial Zone', 'Derbyshire Dales Business Park', 'Darley Dale Business Corridor', 'Cromford Mills Area'],
    propertyTypes: ['Quarrying & Mineral Processing Works', 'Heritage & Tourism Complexes', 'Commercial Offices & Local Authority Buildings', 'Light Engineering Works', 'Healthcare & Care Facilities'],
    keySectors: ['Quarrying & Minerals', 'Tourism, Hospitality & Heritage', 'Local Government & Public Services', 'Light Engineering', 'Healthcare'],
    surroundingAreas: ['Bakewell', 'Chesterfield', 'Ashbourne', 'Wirksworth', 'Buxton', 'Belper'],
    travelCorridors: 'Main routes via the A6 Derwent Valley corridor, A615 to M1, and A632 to Chesterfield.',
    legacyUrls: ['/fm-matlock'],
    serviceUrls: [
      { serviceName: 'Mechanical & Electrical', href: '/mechanical-electrical', isExistingLegacy: true },
      { serviceName: 'Planned Maintenance Schedules', href: '/ppm', isExistingLegacy: true },
      { serviceName: 'Building Maintenance & Fabric', href: '/building-maintenance', isExistingLegacy: true },
      { serviceName: 'Commercial Cleaning Services', href: '/cleaning-services', isExistingLegacy: true },
    ],
    operatingContext: 'Matlock serves as the administrative seat of the Derbyshire Dales, blending heavy mineral extraction operations with sensitive heritage tourism and commercial properties.',
    technicalChallenges: ['Dust extraction, heavy plant maintenance, and stone quarry safety compliance', 'Heritage fabric preservation in conservation zones'],
    faqs: [{ question: 'How do you support facilities in the Derbyshire Dales?', answer: 'From our nearby base, we deliver responsive M&E, compliance, and building maintenance across Matlock and the Peak District.' }],
  },
};
