/**
 * ENTIREFM PROTECTED GEO SEO REGISTRY (Phase 2A)
 * ===============================================
 * Authoritative, immutable registry of all geographical landing pages,
 * legacy flat routes, location hubs, and geographic service permutations.
 *
 * MANDATORY POLICY:
 * 1. Every route listed here is permanently protected against deletion,
 *    redirect, canonical changes, or removal from sitemaps.
 * 2. Flat legacy URLs (e.g. /fm-london, /commercial-cleaning-london) must
 *    remain self-canonical (canonical: 'self') and NEVER canonicalise or
 *    redirect to /locations/london.
 */

export interface ProtectedGeoRoute {
  url: string;
  location: string;
  service: string | null;
  routeType: 'location' | 'geographic-service' | 'glossary-location' | 'blog-location';
  tier: 'TIER_1' | 'TIER_2' | 'REGIONAL_HUB';
  legacy: boolean;
  intent: string;
  indexable: boolean;
  expectedCanonical: 'self';
  statusRequired: 200;
  protected: true;
}

export const PROTECTED_GEO_REGISTRY: ProtectedGeoRoute[] = [
  // ============================================================
  // LONDON (13 Routes)
  // ============================================================
  {
    url: '/fm-london',
    location: 'London',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Outsourced facilities management, integrated FM provider, London corporate offices',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-london',
    location: 'London',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial facilities management, planned maintenance, statutory engineering in London',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/london-facilities-management',
    location: 'London',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial property portfolios, managing agents, and multi-tenant London estates',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/london-facilities-management-areas',
    location: 'London',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'London borough coverage, commercial districts, and travel corridors',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/commercial-cleaning-london',
    location: 'London',
    service: 'Commercial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial daily contract cleaning for London corporate workspaces',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/contract-cleaning-london',
    location: 'London',
    service: 'Contract Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Scheduled contract cleaning agreements for London commercial properties',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/office-cleaning-london',
    location: 'London',
    service: 'Office Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Office cleaning services across the City of London and West End',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/industrial-cleaning-london',
    location: 'London',
    service: 'Industrial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Industrial, warehouse, and plant cleaning in Park Royal and Thames Gateway',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/external-cleaning-london',
    location: 'London',
    service: 'External Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Building façade, exterior, and grounds pressure washing across London',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/pressure-washing-london',
    location: 'London',
    service: 'Pressure Washing',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial jet washing, car parks, and public realm cleaning in London',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-london',
    location: 'London',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'London-specific commercial property, building regulations, and FM terminology',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/london',
    location: 'London',
    service: null,
    routeType: 'location',
    tier: 'TIER_1',
    legacy: false,
    intent: 'EntireFM London regional headquarters, capability overview, and local authority hub',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/london/services',
    location: 'London',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: false,
    intent: 'Index of all Hard and Soft FM services available across Greater London',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  // ============================================================
  // MANCHESTER (13 Routes)
  // ============================================================
  {
    url: '/fm-manchester',
    location: 'Manchester',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Outsourced facilities management across Greater Manchester and North West',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-manchester',
    location: 'Manchester',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial facilities management and planned engineering in Manchester',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/manchester-facilities-management',
    location: 'Manchester',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Managing agent and property portfolio facilities support in Manchester',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/manchester-facilities-managment',
    location: 'Manchester',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Protected legacy Wix spelling preservation for Manchester facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/commercial-cleaning-manchester',
    location: 'Manchester',
    service: 'Commercial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial contract cleaning across Spinningfields, MediaCity, and Manchester',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/contract-cleaning-manchester',
    location: 'Manchester',
    service: 'Contract Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Contract cleaning agreements for Manchester commercial and industrial estates',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/manchester-office-cleaning',
    location: 'Manchester',
    service: 'Office Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Office cleaning for Manchester city centre professional occupiers',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/industrial-cleaning-manchester',
    location: 'Manchester',
    service: 'Industrial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Industrial cleaning for Trafford Park and Greater Manchester manufacturing',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/external-cleaning-manchester',
    location: 'Manchester',
    service: 'External Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'External building fabric and grounds washing in Manchester',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/pressure-washing-manchester',
    location: 'Manchester',
    service: 'Pressure Washing',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial jet washing and car park cleaning across Manchester',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-manchester',
    location: 'Manchester',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Manchester building stock, mill conversions, and FM terms',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/manchester',
    location: 'Manchester',
    service: null,
    routeType: 'location',
    tier: 'TIER_1',
    legacy: false,
    intent: 'EntireFM Manchester regional operations hub and regional authority page',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/manchester/services',
    location: 'Manchester',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: false,
    intent: 'Directory of facilities management services delivered across Greater Manchester',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  // ============================================================
  // BIRMINGHAM (11 Routes)
  // ============================================================
  {
    url: '/fm-birmingham',
    location: 'Birmingham',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Outsourced facilities management across Birmingham and the West Midlands',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-birmingham',
    location: 'Birmingham',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial building maintenance and planned compliance in Birmingham',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/birmingham-facilities-management',
    location: 'Birmingham',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial estate management in Colmore District, Digbeth, and Solihull',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/commercial-cleaning-birmingham',
    location: 'Birmingham',
    service: 'Commercial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial and office contract cleaning across Birmingham',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/industrial-cleaning-birmingham',
    location: 'Birmingham',
    service: 'Industrial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Industrial cleaning for West Midlands manufacturing and trade estates',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/external-cleaning-birmingham',
    location: 'Birmingham',
    service: 'External Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'External façade and grounds pressure washing in Birmingham',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/pressure-washing-birmingham',
    location: 'Birmingham',
    service: 'Pressure Washing',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial jet washing across Birmingham commercial car parks',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-birmingham',
    location: 'Birmingham',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Birmingham Clean Air Zone, listed property, and FM terminology',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/post/facilities-management-to-birmingham',
    location: 'Birmingham',
    service: 'Article',
    routeType: 'blog-location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Editorial commentary on facilities management expansion into Birmingham',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/birmingham',
    location: 'Birmingham',
    service: null,
    routeType: 'location',
    tier: 'TIER_1',
    legacy: false,
    intent: 'EntireFM Birmingham regional hub and local operations centre',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/birmingham/services',
    location: 'Birmingham',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: false,
    intent: 'Service directory for Birmingham and West Midlands commercial facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  // ============================================================
  // LEEDS (9 Routes)
  // ============================================================
  {
    url: '/fm-leeds',
    location: 'Leeds',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Outsourced facilities management in Leeds and West Yorkshire',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-leeds',
    location: 'Leeds',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Planned maintenance and building compliance for Leeds corporate property',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/leeds-facilities-management',
    location: 'Leeds',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial portfolio and multi-tenant property care in Leeds',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/commercial-cleaning-leeds',
    location: 'Leeds',
    service: 'Commercial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Daily contract office cleaning across Wellington Place and Leeds city centre',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/contract-cleaning-leeds',
    location: 'Leeds',
    service: 'Contract Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial contract cleaning for Leeds business parks and distribution',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/industrial-cleaning-leeds',
    location: 'Leeds',
    service: 'Industrial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Industrial cleaning for Aire Valley logistics and manufacturing estates',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-leeds',
    location: 'Leeds',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Leeds financial quarter, lease standards, and FM definitions',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/leeds',
    location: 'Leeds',
    service: null,
    routeType: 'location',
    tier: 'TIER_1',
    legacy: false,
    intent: 'EntireFM Leeds regional hub and Yorkshire operations desk',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/leeds/services',
    location: 'Leeds',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: false,
    intent: 'Service breakdown for Leeds and Yorkshire commercial facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  // ============================================================
  // SHEFFIELD (13 Routes)
  // ============================================================
  {
    url: '/fm-sheffield',
    location: 'Sheffield',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Outsourced facilities management across Sheffield and South Yorkshire',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-sheffield',
    location: 'Sheffield',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Industrial and commercial facilities engineering in Sheffield',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/sheffield-facilities-management',
    location: 'Sheffield',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial portfolio management in Sheffield and Don Valley',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/fm-services-sheffield',
    location: 'Sheffield',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Specialist FM service delivery in Sheffield and Catcliffe',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/sheffield',
    location: 'Sheffield',
    service: 'Facilities Management',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Historic flat Sheffield landing page URL',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/commercial-cleaning-sheffield',
    location: 'Sheffield',
    service: 'Commercial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial daily office cleaning in Sheffield city centre and retail parks',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/contract-cleaning-sheffield',
    location: 'Sheffield',
    service: 'Contract Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Scheduled contract cleaning across Sheffield commercial premises',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/industrial-cleaning-sheffield',
    location: 'Sheffield',
    service: 'Industrial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Heavy industrial cleaning for Don Valley and Advanced Manufacturing Park',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/pressure-washing-sheffield',
    location: 'Sheffield',
    service: 'Pressure Washing',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial jet washing for Sheffield retail parks and industrial yards',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/mobile-crane-hire/sheffield',
    location: 'Sheffield',
    service: 'Crane Hire',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Mobile crane hire and contract lifting operations across Sheffield',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-sheffield',
    location: 'Sheffield',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Sheffield manufacturing terms, industrial power, and LEV guidance',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/sheffield',
    location: 'Sheffield',
    service: null,
    routeType: 'location',
    tier: 'TIER_1',
    legacy: false,
    intent: 'EntireFM Sheffield regional operations hub and local authority page',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/sheffield/services',
    location: 'Sheffield',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: false,
    intent: 'Service breakdown for Sheffield industrial and commercial facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  // ============================================================
  // LIVERPOOL (6 Routes)
  // ============================================================
  {
    url: '/fm-liverpool',
    location: 'Liverpool',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Outsourced facilities management across Liverpool and Merseyside',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-liverpool',
    location: 'Liverpool',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial facilities management and coastal fabric care in Liverpool',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/liverpool-facilities-management',
    location: 'Liverpool',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Port, commercial district, and waterfront estate facilities in Liverpool',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-liverpool',
    location: 'Liverpool',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Liverpool waterfront corrosion, port logistics, and FM terminology',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/liverpool',
    location: 'Liverpool',
    service: null,
    routeType: 'location',
    tier: 'TIER_1',
    legacy: false,
    intent: 'EntireFM Liverpool regional operations hub and Merseyside desk',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/liverpool/services',
    location: 'Liverpool',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: false,
    intent: 'Service breakdown for Liverpool and Merseyside commercial estates',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  // ============================================================
  // NOTTINGHAM (8 Routes)
  // ============================================================
  {
    url: '/fm-nottingham',
    location: 'Nottingham',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Outsourced facilities management across Nottingham and Nottinghamshire',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-nottingham',
    location: 'Nottingham',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial facilities engineering and workplace parking compliance in Nottingham',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/nottingham-facilities-management',
    location: 'Nottingham',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial office and campus estate management in Nottingham',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/commercial-cleaning-nottingham',
    location: 'Nottingham',
    service: 'Commercial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Daily contract office cleaning across Nottingham business parks',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/industrial-cleaning-nottingham',
    location: 'Nottingham',
    service: 'Industrial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Industrial cleaning for Nottingham manufacturing and trade estates',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-nottingham',
    location: 'Nottingham',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Nottingham workplace parking levy, Lace Market heritage, and FM guidance',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/nottingham',
    location: 'Nottingham',
    service: null,
    routeType: 'location',
    tier: 'TIER_1',
    legacy: false,
    intent: 'EntireFM Nottingham regional operations hub and East Midlands desk',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/nottingham/services',
    location: 'Nottingham',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: false,
    intent: 'Service breakdown for Nottingham commercial and educational estates',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  // ============================================================
  // DERBY (7 Routes)
  // ============================================================
  {
    url: '/fm-derby',
    location: 'Derby',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Outsourced facilities management across Derby and Derbyshire',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-derby',
    location: 'Derby',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Engineering-led facilities maintenance for Derby aerospace and manufacturing',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/derby-facilities-management',
    location: 'Derby',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Commercial portfolio management across Pride Park and Infinity Park Derby',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/industrial-cleaning-derby',
    location: 'Derby',
    service: 'Industrial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Industrial cleaning for Derby engineering and transport manufacturing plants',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-derby',
    location: 'Derby',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_1',
    legacy: true,
    intent: 'Derby advanced engineering, World Heritage mill, and FM guidance',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/derby',
    location: 'Derby',
    service: null,
    routeType: 'location',
    tier: 'TIER_1',
    legacy: false,
    intent: 'EntireFM Derby regional operations hub and Derbyshire desk',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/derby/services',
    location: 'Derby',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_1',
    legacy: false,
    intent: 'Service breakdown for Derby engineering and commercial facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  // ============================================================
  // LINCOLN & LINCOLNSHIRE (18 Routes)
  // ============================================================
  {
    url: '/fm-lincoln',
    location: 'Lincoln',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Outsourced facilities management across Lincoln and Lincolnshire',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-lincoln',
    location: 'Lincoln',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial facilities engineering and agricultural corridor maintenance in Lincoln',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/lincoln-facilities-management',
    location: 'Lincoln',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial property management in Lincoln downhill and uphill districts',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/lincoln-facilities-management-areas',
    location: 'Lincoln',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Lincolnshire county coverage: North Hykeham, Sleaford, Newark, Grantham',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/commercial-fm-lincoln',
    location: 'Lincoln',
    service: 'Commercial FM',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial office and retail facilities management in Lincoln',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/industrial-fm-lincoln',
    location: 'Lincoln',
    service: 'Industrial FM',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Industrial, food processing, and warehouse facilities in Lincolnshire',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/residential-fm-lincoln',
    location: 'Lincoln',
    service: 'Residential FM',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Residential block and student accommodation facilities in Lincoln',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/retail-fm-lincoln',
    location: 'Lincoln',
    service: 'Retail FM',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Retail park and shopping centre facilities management in Lincoln',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/commercial-cleaning-lincoln',
    location: 'Lincoln',
    service: 'Commercial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial contract cleaning across Lincoln commercial premises',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/contract-cleaning-lincoln',
    location: 'Lincoln',
    service: 'Contract Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Contract cleaning agreements for Lincolnshire businesses',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/office-cleaning-lincoln',
    location: 'Lincoln',
    service: 'Office Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Office cleaning for Lincoln commercial occupiers',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/industrial-cleaning-lincoln',
    location: 'Lincoln',
    service: 'Industrial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Industrial cleaning for Teal Park and Lincolnshire manufacturing',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/external-cleaning-lincoln',
    location: 'Lincoln',
    service: 'External Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: true,
    intent: 'External building fabric and grounds washing in Lincoln',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/pressure-washing-lincoln',
    location: 'Lincoln',
    service: 'Pressure Washing',
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Pressure washing and commercial jet washing across Lincoln',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-lincoln',
    location: 'Lincoln',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Lincolnshire agricultural property, heritage fabric, and FM terminology',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/post/facilities-management-services-in-lincoln',
    location: 'Lincoln',
    service: 'Article',
    routeType: 'blog-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Editorial overview of facilities management services across Lincoln',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/lincoln',
    location: 'Lincoln',
    service: null,
    routeType: 'location',
    tier: 'TIER_2',
    legacy: false,
    intent: 'EntireFM Lincoln regional operations hub and Lincolnshire operations desk',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/lincoln/services',
    location: 'Lincoln',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: false,
    intent: 'Service directory for Lincoln and Lincolnshire commercial facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  // ============================================================
  // CHESTERFIELD (11 Routes)
  // ============================================================
  {
    url: '/fm-chesterfield',
    location: 'Chesterfield',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Outsourced facilities management across Chesterfield and North Derbyshire',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-chesterfield',
    location: 'Chesterfield',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial facilities engineering and M1 corridor maintenance in Chesterfield',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/chesterfield-facilities-management',
    location: 'Chesterfield',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial property management in Chesterfield town centre and Holmewood',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/chesterfield',
    location: 'Chesterfield',
    service: 'Facilities Management',
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Historic flat Chesterfield landing page URL',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/commercial-cleaning-chesterfield',
    location: 'Chesterfield',
    service: 'Commercial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial contract cleaning across Chesterfield business premises',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/contract-cleaning-chesterfield',
    location: 'Chesterfield',
    service: 'Contract Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Contract cleaning agreements for North Derbyshire businesses',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/industrial-cleaning-chesterfield',
    location: 'Chesterfield',
    service: 'Industrial Cleaning',
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Industrial cleaning for Sheepbridge, Holmewood, and Clay Cross',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/mobile-crane-hire/chesterfield',
    location: 'Chesterfield',
    service: 'Crane Hire',
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Mobile crane hire and contract lifting across Chesterfield',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-chesterfield',
    location: 'Chesterfield',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Chesterfield engineering, M1 logistics, and FM terminology',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/chesterfield',
    location: 'Chesterfield',
    service: null,
    routeType: 'location',
    tier: 'TIER_2',
    legacy: false,
    intent: 'EntireFM Chesterfield regional hub and Derbyshire operations desk',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/chesterfield/services',
    location: 'Chesterfield',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: false,
    intent: 'Service directory for Chesterfield and North Derbyshire facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  // ============================================================
  // OTHER TIER 2 MARKETS (Bradford, Bolton, Bury, Doncaster, Rotherham, Oxford, Preston, Wigan, Grimsby, Telford, Matlock)
  // ============================================================
  {
    url: '/fm-bradford',
    location: 'Bradford',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Outsourced facilities management in Bradford and West Yorkshire',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-bradford',
    location: 'Bradford',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial facilities management in Bradford',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/bradford-facilities-management',
    location: 'Bradford',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial property management in Bradford',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-bradford',
    location: 'Bradford',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Bradford commercial property and FM terms',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/bradford',
    location: 'Bradford',
    service: null,
    routeType: 'location',
    tier: 'TIER_2',
    legacy: false,
    intent: 'EntireFM Bradford regional hub',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/bradford/services',
    location: 'Bradford',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: false,
    intent: 'Service breakdown for Bradford commercial facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  {
    url: '/fm-bolton',
    location: 'Bolton',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Outsourced facilities management in Bolton',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-bolton',
    location: 'Bolton',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial facilities engineering in Bolton',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/bolton-facilities-management',
    location: 'Bolton',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial estate management in Bolton',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-bolton',
    location: 'Bolton',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Bolton industrial property and FM terms',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/bolton',
    location: 'Bolton',
    service: null,
    routeType: 'location',
    tier: 'TIER_2',
    legacy: false,
    intent: 'EntireFM Bolton regional hub',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/bolton/services',
    location: 'Bolton',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: false,
    intent: 'Service breakdown for Bolton commercial estates',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  {
    url: '/fm-bury',
    location: 'Bury',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Outsourced facilities management in Bury',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-bury',
    location: 'Bury',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial facilities engineering in Bury',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/bury-facilities-management',
    location: 'Bury',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial estate management in Bury',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-bury',
    location: 'Bury',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Bury industrial property and FM terms',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/bury',
    location: 'Bury',
    service: null,
    routeType: 'location',
    tier: 'TIER_2',
    legacy: false,
    intent: 'EntireFM Bury regional hub',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/bury/services',
    location: 'Bury',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: false,
    intent: 'Service breakdown for Bury commercial estates',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  {
    url: '/fm-doncaster',
    location: 'Doncaster',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Outsourced facilities management in Doncaster',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-doncaster',
    location: 'Doncaster',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial facilities and rail-freight logistics FM in Doncaster',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/doncaster-facilities-management',
    location: 'Doncaster',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial estate management in Doncaster iPort and town centre',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-doncaster',
    location: 'Doncaster',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Doncaster high-bay logistics, rail engineering, and FM terminology',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/doncaster',
    location: 'Doncaster',
    service: null,
    routeType: 'location',
    tier: 'TIER_2',
    legacy: false,
    intent: 'EntireFM Doncaster regional operations hub and South Yorkshire desk',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/doncaster/services',
    location: 'Doncaster',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: false,
    intent: 'Service breakdown for Doncaster freight and commercial facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  {
    url: '/fm-rotherham',
    location: 'Rotherham',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Outsourced facilities management in Rotherham',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-rotherham',
    location: 'Rotherham',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial facilities engineering in Rotherham and Templeborough',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/rotherham-facilities-management',
    location: 'Rotherham',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial estate management in Rotherham and Parkgate',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-rotherham',
    location: 'Rotherham',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Rotherham materials processing, metal fabrication, and FM terminology',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/rotherham',
    location: 'Rotherham',
    service: null,
    routeType: 'location',
    tier: 'TIER_2',
    legacy: false,
    intent: 'EntireFM Rotherham regional operations hub and South Yorkshire desk',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/rotherham/services',
    location: 'Rotherham',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: false,
    intent: 'Service breakdown for Rotherham industrial and commercial facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  {
    url: '/fm-oxford',
    location: 'Oxford',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Outsourced facilities management in Oxford and Oxfordshire',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-oxford',
    location: 'Oxford',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Life science and academic estate facilities in Oxford',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/oxford-facilities-management',
    location: 'Oxford',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial and research estate management in Oxford',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-oxford',
    location: 'Oxford',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Oxford laboratory environments, heritage restrictions, and FM terminology',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/oxford',
    location: 'Oxford',
    service: null,
    routeType: 'location',
    tier: 'TIER_2',
    legacy: false,
    intent: 'EntireFM Oxford regional hub and South operations desk',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/oxford/services',
    location: 'Oxford',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: false,
    intent: 'Service breakdown for Oxford science parks and commercial estates',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  {
    url: '/fm-preston',
    location: 'Preston',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Outsourced facilities management in Preston and Lancashire',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-preston',
    location: 'Preston',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial facilities engineering in Preston',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/preston-facilities-management',
    location: 'Preston',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial estate management in Preston',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-preston',
    location: 'Preston',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Preston commercial property and FM terms',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/preston',
    location: 'Preston',
    service: null,
    routeType: 'location',
    tier: 'TIER_2',
    legacy: false,
    intent: 'EntireFM Preston regional operations hub',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/preston/services',
    location: 'Preston',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: false,
    intent: 'Service breakdown for Preston commercial facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  {
    url: '/fm-wigan',
    location: 'Wigan',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Outsourced facilities management in Wigan and Greater Manchester West',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-wigan',
    location: 'Wigan',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial facilities engineering in Wigan',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/wigan-facilities-management',
    location: 'Wigan',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial estate management in Wigan',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-wigan',
    location: 'Wigan',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Wigan distribution corridors and FM terms',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/wigan',
    location: 'Wigan',
    service: null,
    routeType: 'location',
    tier: 'TIER_2',
    legacy: false,
    intent: 'EntireFM Wigan regional operations hub',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/wigan/services',
    location: 'Wigan',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: false,
    intent: 'Service breakdown for Wigan commercial facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  {
    url: '/fm-grimsby',
    location: 'Grimsby',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Outsourced facilities management in Grimsby and Humber Ports',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-grimsby',
    location: 'Grimsby',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Port logistics and cold storage facilities management in Grimsby',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/grimsby-facilities-management',
    location: 'Grimsby',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial estate management in Grimsby',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-grimsby',
    location: 'Grimsby',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Grimsby cold storage, seafood processing, port maintenance, and FM terms',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/grimsby',
    location: 'Grimsby',
    service: null,
    routeType: 'location',
    tier: 'TIER_2',
    legacy: false,
    intent: 'EntireFM Grimsby regional operations hub and Humber ports desk',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/grimsby/services',
    location: 'Grimsby',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: false,
    intent: 'Service breakdown for Grimsby port and commercial facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  {
    url: '/fm-telford',
    location: 'Telford',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Outsourced facilities management in Telford and Shropshire',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-telford',
    location: 'Telford',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial facilities engineering in Telford and M54 corridor',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-in-telford',
    location: 'Telford',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Protected legacy Wix alias for Telford facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/telford-facilities-management',
    location: 'Telford',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Commercial property management in Telford',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-telford',
    location: 'Telford',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Telford automotive supply chain, manufacturing, and FM terms',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/telford',
    location: 'Telford',
    service: null,
    routeType: 'location',
    tier: 'TIER_2',
    legacy: false,
    intent: 'EntireFM Telford regional operations hub and Shropshire desk',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/telford/services',
    location: 'Telford',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: false,
    intent: 'Service breakdown for Telford industrial and commercial estates',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  {
    url: '/fm-matlock',
    location: 'Matlock',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Outsourced facilities management in Matlock and Derbyshire Dales',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-glossary-matlock',
    location: 'Matlock',
    service: 'Glossary',
    routeType: 'glossary-location',
    tier: 'TIER_2',
    legacy: true,
    intent: 'Derbyshire Dales, rural heritage, and FM terminology',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/matlock',
    location: 'Matlock',
    service: null,
    routeType: 'location',
    tier: 'TIER_2',
    legacy: false,
    intent: 'EntireFM Matlock regional operations hub and Peak District fringe desk',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/locations/matlock/services',
    location: 'Matlock',
    service: null,
    routeType: 'geographic-service',
    tier: 'TIER_2',
    legacy: false,
    intent: 'Service breakdown for Matlock and Peak District facilities',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },

  // ============================================================
  // REGIONAL HUBS & DIRECTORIES (3 Routes)
  // ============================================================
  {
    url: '/locations',
    location: 'UK Nationwide',
    service: null,
    routeType: 'location',
    tier: 'REGIONAL_HUB',
    legacy: false,
    intent: 'EntireFM national directory of UK regional operational hubs',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-midlands',
    location: 'Midlands',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'REGIONAL_HUB',
    legacy: true,
    intent: 'Regional facilities management across the East and West Midlands',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
  {
    url: '/facilities-management-in-the-midlands',
    location: 'Midlands',
    service: 'Facilities Management',
    routeType: 'location',
    tier: 'REGIONAL_HUB',
    legacy: true,
    intent: 'Protected legacy Wix alias for Midlands facilities management',
    indexable: true,
    expectedCanonical: 'self',
    statusRequired: 200,
    protected: true,
  },
];

/**
 * Returns all protected geo routes
 */
export function getProtectedGeoRoutes(): ProtectedGeoRoute[] {
  return PROTECTED_GEO_REGISTRY;
}

/**
 * Finds a protected geo route by URL path
 */
export function findProtectedGeoRoute(path: string): ProtectedGeoRoute | undefined {
  return PROTECTED_GEO_REGISTRY.find(r => r.url === path);
}
