/**
 * INDEXATION TIERS
 * ================
 * Reads config/indexation-tiers.json, generated by
 * scripts/generate-indexation-tiers.js.
 *
 * SCOPE — READ THIS BEFORE CHANGING ANYTHING HERE
 * -----------------------------------------------
 * This controls `noindex` ONLY. It has no effect on routing.
 *
 * Every path in the registry is a live page returning 200 whatever this file
 * says about it. Nothing here redirects, deletes or 404s a URL. A page held
 * for differentiation is still reachable, still internally linked, still
 * passes link equity and still converts a visitor who lands on it — it is
 * simply not offered to search engines while it remains a near-duplicate of
 * a page targeting the same thing.
 *
 * That distinction is the whole point: restoring the 187 legacy URLs is what
 * recovers ranking history, and holding the near-duplicates back is what stops
 * the restored estate reading as doorway pages. The two are compatible.
 *
 * A page leaves AWAITING_DIFFERENTIATION by having content written for it,
 * then regenerating — never by editing the JSON by hand.
 */

// eslint-disable-next-line @typescript-eslint/no-require-imports
const tierData = require('../../config/indexation-tiers.json') as {
  summary: { total: number; indexable: number; awaitingDifferentiation: number };
  tiers: Record<
    string,
    {
      indexable: boolean;
      tier: string;
      reason: string;
      peakSimilarity: number;
      clusterSize?: number;
      representative?: string;
    }
  >;
};

export type IndexationTier =
  | 'TIER_1'
  | 'CLUSTER_REPRESENTATIVE'
  | 'UNIQUE'
  | 'AWAITING_DIFFERENTIATION'
  | 'UNCLASSIFIED';

export const INDEXATION_SUMMARY = tierData.summary;

/**
 * Whether a path may be offered for indexing.
 * Unknown paths default to true so a new page is never silently hidden —
 * the similarity gate catches it on the next generation instead.
 */
export function isIndexableByTier(path: string): boolean {
  const entry = tierData.tiers[path];
  if (entry) return entry.indexable;
  try {
    const decoded = decodeURIComponent(path);
    if (tierData.tiers[decoded]) return tierData.tiers[decoded].indexable;
  } catch {
    /* fall through */
  }
  return true;
}

/** Full tier record, for reporting and QA. */
export function getTierRecord(path: string) {
  return tierData.tiers[path] ?? null;
}

/** Paths currently held back pending differentiation. */
export function getHeldPaths(): string[] {
  return Object.entries(tierData.tiers)
    .filter(([, v]) => !v.indexable)
    .map(([p]) => p);
}
