/**
 * ENTIRE FM — PROTECTED LEGACY & SEO ROUTE REGISTRY
 *
 * MANDATORY REQUIREMENT:
 * Every route in this registry must:
 * 1. Exist as an independent server-rendered Next.js page.
 * 2. Return HTTP 200 (NOT 301, 302, 404, or 410).
 * 3. Have a self-referencing canonical tag.
 * 4. Be indexable (index, follow).
 * 5. Contain unique, substantive, high-information-gain content.
 *
 * AUTOMATED BUILD TESTS WILL FAIL IF ANY OF THESE ROUTES REGRESS.
 */

export interface ProtectedRoute {
  path: string;
  source: 'wix-generation-1' | 'wix-generation-2' | 'wix-generation-1-and-2' | 'mandatory-historic-directive' | 'NEW_GROWTH_ROUTE';
  historic: boolean;
  protected: boolean;
  statusRequired: 200;
  canonical: 'self';
  uniquePageRequired: boolean;
  g1_url?: string | null;
  g2_url?: string | null;
}

export const PROTECTED_LEGACY_ROUTES: ProtectedRoute[] = [
{
    "path": "/",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724"
  },
  {
    "path": "/24-7-fm-support",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/24-7-fm-support",
    "g2_url": null
  },
  {
    "path": "/about-entire-facilities-management",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/about-entire-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/about-entire-facilities-management"
  },
  {
    "path": "/accessibility-statement",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/accessibility-statement"
  },
  {
    "path": "/aerial-drone-building-inspection",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/aerial-drone-building-inspection",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/aerial-drone-building-inspection"
  },
  {
    "path": "/airport-facilities-management",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/airport-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/airport-facilities-management"
  },
  {
    "path": "/arena-facilities-management",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/arena-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/arena-facilities-management"
  },
  {
    "path": "/best-facilities-management-company",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/best-facilities-management-company",
    "g2_url": null
  },
  {
    "path": "/birmingham-facilities-management",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/birmingham-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/birmingham-facilities-management"
  },
  {
    "path": "/blog",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/blog"
  },
  {
    "path": "/bocker-crane-hire",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/bocker-crane-hire"
  },
  {
    "path": "/bolton-facilities-management",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/bradford-facilities-management",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/bradford-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/bradford-facilities-management"
  },
  {
    "path": "/building-inspecting-testing",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/building-inspecting-testing"
  },
  {
    "path": "/building-maintenance",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/building-maintenance",
    "g2_url": null
  },
  {
    "path": "/bury-facilities-management",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/caretaker",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/caretaker",
    "g2_url": null
  },
  {
    "path": "/carpark-management",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/carpark-management",
    "g2_url": null
  },
  {
    "path": "/chesterfield-facilities-management",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/chesterfield-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/chesterfield-facilities-management"
  },
  {
    "path": "/cleaning-services",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/cleaning-services",
    "g2_url": null
  },
  {
    "path": "/client-login",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/client-login"
  },
  {
    "path": "/client-login/account-registration",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/client-login/account-registration"
  },
  {
    "path": "/commercial-cleaning-birmingham",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/commercial-cleaning-birmingham",
    "g2_url": null
  },
  {
    "path": "/commercial-cleaning-chesterfield",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/commercial-cleaning-chesterfield",
    "g2_url": null
  },
  {
    "path": "/commercial-cleaning-leeds",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/commercial-cleaning-leeds",
    "g2_url": null
  },
  {
    "path": "/commercial-cleaning-lincoln",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/commercial-cleaning-lincoln",
    "g2_url": null
  },
  {
    "path": "/commercial-cleaning-london",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/commercial-cleaning-london",
    "g2_url": null
  },
  {
    "path": "/commercial-cleaning-manchester",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/commercial-cleaning-manchester",
    "g2_url": null
  },
  {
    "path": "/commercial-cleaning-nottingham",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/commercial-cleaning-nottingham",
    "g2_url": null
  },
  {
    "path": "/commercial-cleaning-sheffield",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/commercial-cleaning-sheffield",
    "g2_url": null
  },
  {
    "path": "/commercial-facilities-management",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/commercial-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/commercial-facilities-management"
  },
  {
    "path": "/commercial-fm-lincoln",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/commercial-fm-lincoln",
    "g2_url": null
  },
  {
    "path": "/concierge-services",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/concierge-services",
    "g2_url": null
  },
  {
    "path": "/construction-facilities-management",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/construction-facilities-management",
    "g2_url": null
  },
  {
    "path": "/contact-us",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/contact-us"
  },
  {
    "path": "/contract-cleaning",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/contract-cleaning",
    "g2_url": null
  },
  {
    "path": "/contract-cleaning-chesterfield",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/contract-cleaning-chesterfield",
    "g2_url": null
  },
  {
    "path": "/contract-cleaning-leeds",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/contract-cleaning-leeds",
    "g2_url": null
  },
  {
    "path": "/contract-cleaning-lincoln",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/contract-cleaning-lincoln",
    "g2_url": null
  },
  {
    "path": "/contract-cleaning-london",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/contract-cleaning-london",
    "g2_url": null
  },
  {
    "path": "/contract-cleaning-manchester",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/contract-cleaning-manchester",
    "g2_url": null
  },
  {
    "path": "/contract-cleaning-sheffield",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/contract-cleaning-sheffield",
    "g2_url": null
  },
  {
    "path": "/copy-of-helpdesk-registration",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/copy-of-helpdesk-registration",
    "g2_url": null
  },
  {
    "path": "/copy-of-industrial-cleaning",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/copy-of-industrial-cleaning",
    "g2_url": null
  },
  {
    "path": "/copy-of-what-is-facilities-manageme",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/copy-of-what-is-facilities-manageme",
    "g2_url": null
  },
  {
    "path": "/derby-facilities-management",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/derby-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/derby-facilities-management"
  },
  {
    "path": "/doncaster-facilities-management",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/education-cleaning",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/education-cleaning",
    "g2_url": null
  },
  {
    "path": "/education-facilities-management",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/education-facilities-management",
    "g2_url": null
  },
  {
    "path": "/employment-portal",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/employment-portal",
    "g2_url": null
  },
  {
    "path": "/external-cleaning-birmingham",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/external-cleaning-birmingham",
    "g2_url": null
  },
  {
    "path": "/external-cleaning-lincoln",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/external-cleaning-lincoln",
    "g2_url": null
  },
  {
    "path": "/external-cleaning-london",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/external-cleaning-london",
    "g2_url": null
  },
  {
    "path": "/external-cleaning-manchester",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/external-cleaning-manchester",
    "g2_url": null
  },
  {
    "path": "/facilities-management-birmingham",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-birmingham",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-birmingham"
  },
  {
    "path": "/facilities-management-blog",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-blog",
    "g2_url": null
  },
  {
    "path": "/facilities-management-bolton",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/facilities-management-bradford",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-bradford",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-bradford"
  },
  {
    "path": "/facilities-management-bury",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/facilities-management-chesterfield",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-chesterfield",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-chesterfield"
  },
  {
    "path": "/facilities-management-derby",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-derby",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-derby"
  },
  {
    "path": "/facilities-management-doncaster",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/facilities-management-for/construction-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/construction-facilities-management"
  },
  {
    "path": "/facilities-management-for/education-%26-schools-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/education-%26-schools-facilities-management"
  },
  {
    "path": "/facilities-management-for/healthcare-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/healthcare-facilities-management"
  },
  {
    "path": "/facilities-management-for/hotels-%26-resort-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/hotels-%26-resort-facilities-management"
  },
  {
    "path": "/facilities-management-for/industrial-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/industrial-facilities-management"
  },
  {
    "path": "/facilities-management-for/leisure-centre-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/leisure-centre-facilities-management"
  },
  {
    "path": "/facilities-management-for/logistics-%26-distribution-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/logistics-%26-distribution-facilities-management"
  },
  {
    "path": "/facilities-management-for/managing-agent-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/managing-agent-facilities-management"
  },
  {
    "path": "/facilities-management-for/offices%2C-corporate-%26-co-working",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/offices%2C-corporate-%26-co-working"
  },
  {
    "path": "/facilities-management-for/residential-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/residential-facilities-management"
  },
  {
    "path": "/facilities-management-for/restaurant-%26-hospitality-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/restaurant-%26-hospitality-facilities-management"
  },
  {
    "path": "/facilities-management-for/retail-%26-shopping-centre-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/retail-%26-shopping-centre-facilities-management"
  },
  {
    "path": "/facilities-management-for/sports-venue-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/sports-venue-facilities-management"
  },
  {
    "path": "/facilities-management-for/stadium-%26-arena-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/stadium-%26-arena-facilities-management"
  },
  {
    "path": "/facilities-management-for/warehouse-%26-distribution",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-for/warehouse-%26-distribution"
  },
  {
    "path": "/facilities-management-grimsby",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/facilities-management-in-telford",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-in-telford",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-in-telford"
  },
  {
    "path": "/facilities-management-in-the-midlands",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-in-the-midlands",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-in-the-midlands"
  },
  {
    "path": "/facilities-management-leeds",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-leeds",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-leeds"
  },
  {
    "path": "/facilities-management-lincoln",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-lincoln",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-lincoln"
  },
  {
    "path": "/facilities-management-liverpool",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-liverpool",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-liverpool"
  },
  {
    "path": "/facilities-management-london",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-london",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-london"
  },
  {
    "path": "/facilities-management-manchester",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-manchester",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-manchester"
  },
  {
    "path": "/facilities-management-midlands",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-midlands",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-midlands"
  },
  {
    "path": "/facilities-management-nottingham",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-nottingham",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-nottingham"
  },
  {
    "path": "/facilities-management-offices",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-offices",
    "g2_url": null
  },
  {
    "path": "/facilities-management-oxford",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/facilities-management-preston",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/facilities-management-rotherham",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/facilities-management-services",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-services",
    "g2_url": null
  },
  {
    "path": "/facilities-management-services-london",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-services-lond",
    "g2_url": null
  },
  {
    "path": "/facilities-management-sheffield",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-sheffield",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-sheffield"
  },
  {
    "path": "/facilities-management-team",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-team",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-team"
  },
  {
    "path": "/facilities-management-telford",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/facilities-management-telford",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/facilities-management-telford"
  },
  {
    "path": "/facilities-management-wigan",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/fire-emergency-systems",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fire-emergency-systems",
    "g2_url": null
  },
  {
    "path": "/fm-birmingham",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-birmingham",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-birmingham"
  },
  {
    "path": "/fm-bolton",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/fm-bradford",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-bradford",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-bradford"
  },
  {
    "path": "/fm-bury",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/fm-chesterfield",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-chesterfield",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-chesterfield"
  },
  {
    "path": "/fm-client-info",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-client-info",
    "g2_url": null
  },
  {
    "path": "/fm-derby",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-derby",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-derby"
  },
  {
    "path": "/fm-doncaster",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/fm-grimsby",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/fm-leeds",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-leeds",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-leeds"
  },
  {
    "path": "/fm-lincoln",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-lincoln",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-lincoln"
  },
  {
    "path": "/fm-liverpool",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-liverpool",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-liverpool"
  },
  {
    "path": "/fm-london",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-london",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-london"
  },
  {
    "path": "/fm-manchester",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-manchester",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-manchester"
  },
  {
    "path": "/fm-matlock",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-matlock",
    "g2_url": null
  },
  {
    "path": "/fm-nottingham",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-nottingham",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-nottingham"
  },
  {
    "path": "/fm-oxford",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/fm-preston",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/fm-rotherham",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/fm-services-sheffield",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-services-sheffield",
    "g2_url": null
  },
  {
    "path": "/fm-sheffield",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-sheffield",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-sheffield"
  },
  {
    "path": "/fm-supply-chain",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-supply-chain",
    "g2_url": null
  },
  {
    "path": "/fm-supply-form",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-supply-form",
    "g2_url": null
  },
  {
    "path": "/fm-support-n-contact",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-support-n-contact",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-support-n-contact"
  },
  {
    "path": "/fm-support-n-contact/facilities-management-glossary",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-support-n-contact/facilities-management-glossary"
  },
  {
    "path": "/fm-technical-services",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-technical-services",
    "g2_url": null
  },
  {
    "path": "/fm-telford",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/fm-telford",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/fm-telford"
  },
  {
    "path": "/fm-wigan",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/gates-barriers",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/gates-barriers",
    "g2_url": null
  },
  {
    "path": "/grimsby-facilities-management",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/grounds-maintenance",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/grounds-maintenance",
    "g2_url": null
  },
  {
    "path": "/hard-services",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/hard-services",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/hard-services"
  },
  {
    "path": "/healthcare-facilities-management",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/healthcare-facilities-management",
    "g2_url": null
  },
  {
    "path": "/helpdesk",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/helpdesk",
    "g2_url": null
  },
  {
    "path": "/helpdesk-registration",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/helpdesk-registration",
    "g2_url": null
  },
  {
    "path": "/hot-tub-relocation",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/hot-tub-relocation"
  },
  {
    "path": "/hotel-facilities-management",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/hotel-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/hotel-facilities-management"
  },
  {
    "path": "/hvac-contractor",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/hvac-contractor",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/hvac-contractor"
  },
  {
    "path": "/industrial-cleaning",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/industrial-cleaning",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/industrial-cleaning"
  },
  {
    "path": "/industrial-cleaning-birmingham",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/industrial-cleaning-birmingham",
    "g2_url": null
  },
  {
    "path": "/industrial-cleaning-chesterfield",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/industrial-cleaning-chesterfield",
    "g2_url": null
  },
  {
    "path": "/industrial-cleaning-derby",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/industrial-cleaning-derby",
    "g2_url": null
  },
  {
    "path": "/industrial-cleaning-leeds",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/industrial-cleaning-leeds",
    "g2_url": null
  },
  {
    "path": "/industrial-cleaning-lincoln",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/industrial-cleaning-lincoln",
    "g2_url": null
  },
  {
    "path": "/industrial-cleaning-london",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/industrial-cleaning-london",
    "g2_url": null
  },
  {
    "path": "/industrial-cleaning-manchester",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/industrial-cleaning-manchester",
    "g2_url": null
  },
  {
    "path": "/industrial-cleaning-nottingham",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/industrial-cleaning-nottingham",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/industrial-cleaning-nottingham"
  },
  {
    "path": "/industrial-cleaning-sheffield",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/industrial-cleaning-sheffield",
    "g2_url": null
  },
  {
    "path": "/industrial-facilities-management",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/industrial-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/industrial-facilities-management"
  },
  {
    "path": "/industrial-fm-lincoln",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/industrial-fm-lincoln",
    "g2_url": null
  },
  {
    "path": "/internal-cleaning",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/internal-cleaning",
    "g2_url": null
  },
  {
    "path": "/items",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/items",
    "g2_url": null
  },
  {
    "path": "/job-board",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/job-board",
    "g2_url": null
  },
  {
    "path": "/landmark-facilities-management",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/landmark-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/landmark-facilities-management"
  },
  {
    "path": "/landscaping",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/landscaping",
    "g2_url": null
  },
  {
    "path": "/leeds-facilities-management",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/leeds-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/leeds-facilities-management"
  },
  {
    "path": "/lincoln-facilities-management",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/lincoln-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/lincoln-facilities-management"
  },
  {
    "path": "/lincoln-facilities-management-areas",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/lincoln-facilities-management-areas",
    "g2_url": null
  },
  {
    "path": "/liverpool-facilities-management",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/liverpool-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/liverpool-facilities-management"
  },
  {
    "path": "/logistics-facilities-management",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/logistics-facilities-management",
    "g2_url": null
  },
  {
    "path": "/london-facilities-management",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/london-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/london-facilities-management"
  },
  {
    "path": "/london-facilities-management-areas",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/london-facilities-management-areas",
    "g2_url": null
  },
  {
    "path": "/manchester-facilities-management",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/manchester-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/manchester-facilities-management"
  },
  {
    "path": "/manchester-facilities-managment",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/manchester-facilities-managment",
    "g2_url": null
  },
  {
    "path": "/manchester-office-cleaning",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/manchester-office-cleaning",
    "g2_url": null
  },
  {
    "path": "/mechanical-electrical",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/mechanical-electrical",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/mechanical-electrical"
  },
  {
    "path": "/mechanical-electrical/access-control",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/mechanical-electrical/access-control"
  },
  {
    "path": "/mechanical-electrical/emergency-light-testing",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/mechanical-electrical/emergency-light-testing"
  },
  {
    "path": "/media-digital-displays",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/media-digital-displays",
    "g2_url": null
  },
  {
    "path": "/medical-cleaning",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/medical-cleaning",
    "g2_url": null
  },
  {
    "path": "/mobile-crane-hire",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/mobile-crane-hire"
  },
  {
    "path": "/mobile-crane-hire/chesterfield",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/mobile-crane-hire/chesterfield"
  },
  {
    "path": "/mobile-crane-hire/sheffield",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/mobile-crane-hire/sheffield"
  },
  {
    "path": "/mobile-crane-hire/truck-mount-crane-hire",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/mobile-crane-hire/truck-mount-crane-hire"
  },
  {
    "path": "/nottingham-facilities-management",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/nottingham-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/nottingham-facilities-management"
  },
  {
    "path": "/office-cleaning",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/office-cleaning",
    "g2_url": null
  },
  {
    "path": "/office-cleaning-lincoln",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/office-cleaning-lincoln",
    "g2_url": null
  },
  {
    "path": "/office-cleaning-london",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/office-cleaning-london",
    "g2_url": null
  },
  {
    "path": "/oxford-facilities-management",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/plumbing-gas",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/plumbing-gas",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/plumbing-gas"
  },
  {
    "path": "/portfolio",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/portfolio",
    "g2_url": null
  },
  {
    "path": "/post/facilities-management-in-different-sectors-similarities-differences-and-the-need-for-agility",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/post/facilities-management-in-different-sectors-similarities-differences-and-the-need-for-agility"
  },
  {
    "path": "/post/facilities-management-services-in-lincoln",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/post/facilities-management-services-in-lincoln",
    "g2_url": null
  },
  {
    "path": "/post/facilities-management-to-birmingham",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/post/facilities-management-to-birmingham",
    "g2_url": null
  },
  {
    "path": "/post/the-importance-of-regular-maintenance-and-inspections",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/post/the-importance-of-regular-maintenance-and-inspections",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/post/the-importance-of-regular-maintenance-and-inspections"
  },
  {
    "path": "/post/the-importance-of-regular-maintenance-and-inspections-1",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/post/the-importance-of-regular-maintenance-and-inspections-1"
  },
  {
    "path": "/post/what-are-hard-services",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/post/what-are-hard-services",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/post/what-are-hard-services"
  },
  {
    "path": "/post/what-are-hard-services-in-facilities-management",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/post/what-are-hard-services-in-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/post/what-are-hard-services-in-facilities-management"
  },
  {
    "path": "/post/what-are-hard-services-in-facilities-management-1",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/post/what-are-hard-services-in-facilities-management-1"
  },
  {
    "path": "/post/what-is-facilities-management",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/post/what-is-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/post/what-is-facilities-management"
  },
  {
    "path": "/post/what-is-facilities-management-1",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/post/what-is-facilities-management-1",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/post/what-is-facilities-management-1"
  },
  {
    "path": "/post/what-is-facilities-management-1-1",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/post/what-is-facilities-management-1-1"
  },
  {
    "path": "/ppm",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/ppm",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/ppm"
  },
  {
    "path": "/pressure-washing",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/pressure-washing",
    "g2_url": null
  },
  {
    "path": "/pressure-washing-birmingham",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/pressure-washing-birmingham",
    "g2_url": null
  },
  {
    "path": "/pressure-washing-lincoln",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/pressure-washing-lincoln",
    "g2_url": null
  },
  {
    "path": "/pressure-washing-london",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/pressure-washing-london",
    "g2_url": null
  },
  {
    "path": "/pressure-washing-manchester",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/pressure-washing-manchester",
    "g2_url": null
  },
  {
    "path": "/pressure-washing-sheffield",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/pressure-washing-sheffield",
    "g2_url": null
  },
  {
    "path": "/preston-facilities-management",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/privacy-policy",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/privacy-policy",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/privacy-policy"
  },
  {
    "path": "/property-manager-fm-services",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/property-manager-fm-services",
    "g2_url": null
  },
  {
    "path": "/public-sector-facilities-management",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/public-sector-facilities-management",
    "g2_url": null
  },
  {
    "path": "/reactive-cleaning-services",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/reactive-cleaning-services",
    "g2_url": null
  },
  {
    "path": "/residential-cleaning",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/residential-cleaning",
    "g2_url": null
  },
  {
    "path": "/residential-facilities-management",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/residential-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/residential-facilities-management"
  },
  {
    "path": "/residential-fm-lincoln",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/residential-fm-lincoln",
    "g2_url": null
  },
  {
    "path": "/restaurant-facilities-management",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/restaurant-facilities-management",
    "g2_url": null
  },
  {
    "path": "/retail-cleaning",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/retail-cleaning",
    "g2_url": null
  },
  {
    "path": "/retail-facilities-management",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/retail-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/retail-facilities-management"
  },
  {
    "path": "/retail-fm-lincoln",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/retail-fm-lincoln",
    "g2_url": null
  },
  {
    "path": "/rotherham-facilities-management",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/safety-critical-emergency-systems",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/safety-critical-emergency-systems"
  },
  {
    "path": "/security-services",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/security-services",
    "g2_url": null
  },
  {
    "path": "/service-station-fm",
    "source": "wix-generation-1-and-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/service-station-fm",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/service-station-fm"
  },
  {
    "path": "/services",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/services",
    "g2_url": null
  },
  {
    "path": "/sheffield-facilities-management",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/sheffield-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/sheffield-facilities-management"
  },
  {
    "path": "/soft-services",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/soft-services",
    "g2_url": null
  },
  {
    "path": "/sport-centre-facilities-management",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/sport-centre-facilities-management",
    "g2_url": null
  },
  {
    "path": "/telford-facilities-management",
    "source": "mandatory-historic-directive",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/telford-facilities-management",
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/telford-facilities-management"
  },
  {
    "path": "/terms-and-conditions",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/terms-and-conditions"
  },
  {
    "path": "/tier-one-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/tier-one-facilities-management"
  },
  {
    "path": "/tierone-facilities-managment",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/tierone-facilities-managment",
    "g2_url": null
  },
  {
    "path": "/transport-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/transport-facilities-management"
  },
  {
    "path": "/vending-supplier",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/vending-supplier",
    "g2_url": null
  },
  {
    "path": "/warehouse-facilities-management",
    "source": "wix-generation-2",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": "https://petercurrey.wixstudio.com/efmsut17724/warehouse-facilities-management"
  },
  {
    "path": "/washroom-management",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/washroom-management",
    "g2_url": null
  },
  {
    "path": "/what-is-facilities-management",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/what-is-facilities-management",
    "g2_url": null
  },
  {
    "path": "/wigan-facilities-management",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": null,
    "g2_url": null
  },
  {
    "path": "/window-cleaning",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/window-cleaning",
    "g2_url": null
  },
  {
    "path": "/working-at-heights",
    "source": "wix-generation-1",
    "historic": true,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true,
    "g1_url": "https://petercurrey.wixsite.com/efm-new/working-at-heights",
    "g2_url": null
  },
  {
    "path": "/ppm-london",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true
  },
  {
    "path": "/ppm-manchester",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true
  },
  {
    "path": "/hvac-london",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true
  },
  {
    "path": "/mechanical-electrical-london",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true
  },
  {
    "path": "/ppm-birmingham",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true
  },
  {
    "path": "/hvac-manchester",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true
  },
  {
    "path": "/ppm-leeds",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true
  },
  {
    "path": "/ppm-sheffield",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true
  },
  {
    "path": "/commercial-cleaning-liverpool",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true
  },
  {
    "path": "/commercial-cleaning-derby",
    "source": "NEW_GROWTH_ROUTE",
    "historic": false,
    "protected": true,
    "statusRequired": 200,
    "canonical": "self",
    "uniquePageRequired": true
  }
];

export const PROTECTED_ROUTE_PATHS = new Set(PROTECTED_LEGACY_ROUTES.map(r => r.path));
