import { ComplianceClassification, COMPLIANCE_REGIMES } from './compliance-taxonomy';

export interface MaintenanceTaskDefinition {
  activity: string;
  frequency: 'Weekly' | 'Monthly' | 'Quarterly' | '6-Monthly' | 'Annually' | '2-Yearly' | '3-Yearly' | '5-Yearly' | '14-Monthly' | 'Risk-Based';
  frequencyMonths: number[]; // 1-12
  classification: ComplianceClassification;
  governingBasis: string;
  statutoryReference: string;
  recommendedCompetency: string;
  evidenceExpected: string;
  riskNotes: string;
}

export interface CommercialAssetCategory {
  id: string;
  name: string;
  description: string;
  iconName: string;
  assets: CommercialAssetDefinition[];
}

export interface CommercialAssetDefinition {
  id: string;
  categoryId: string;
  categoryName: string;
  name: string;
  shortDescription: string;
  defaultFrequencies: string[];
  isStatutoryOrStandard: boolean;
  supportsQuantity?: boolean; // Default true, false for single fixed site assessments
  defaultQuantity?: number;
  regimeId?: string;
  tasks: MaintenanceTaskDefinition[];
}

export const COMMERCIAL_ASSET_CATEGORIES: CommercialAssetCategory[] = [
  {
    id: 'hvac',
    name: 'HVAC & Climate Control',
    description: 'Central air handling, mechanical ventilation, chillers, VRF/VRV air conditioning, boilers, and heating distribution.',
    iconName: 'Wind',
    assets: [
      {
        id: 'hvac-ahu',
        categoryId: 'hvac',
        categoryName: 'HVAC & Climate Control',
        name: 'Air Handling Units (AHUs)',
        shortDescription: 'Supply and extract air handling units, filtration stages, heat recovery wheels, and duct distribution.',
        defaultFrequencies: ['Quarterly', '6-Monthly', 'Annually'],
        isStatutoryOrStandard: false,
        supportsQuantity: true,
        defaultQuantity: 4,
        tasks: [
          {
            activity: 'Air filter inspection, differential pressure check, and replacement',
            frequency: 'Quarterly',
            frequencyMonths: [3, 6, 9, 12],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'SFG20 Core Task / CIBSE Guide M',
            statutoryReference: 'Workplace (Health, Safety and Welfare) Regs 1992 Reg 5',
            recommendedCompetency: 'HVAC Maintenance Technician',
            evidenceExpected: 'Service report with filter grade (e.g. ISO ePM1) and differential pressure log',
            riskNotes: 'Clogged filters increase motor energy consumption by up to 25% and reduce indoor air quality.',
          },
          {
            activity: 'Drive belts tensioning, pulley alignment, bearing lubrication, and coil chemical sanitisation',
            frequency: '6-Monthly',
            frequencyMonths: [4, 10],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'SFG20 / CIBSE Guide M',
            statutoryReference: 'Workplace Regs 1992',
            recommendedCompetency: 'Qualified Mechanical Engineer',
            evidenceExpected: 'Mechanical service log with coil hygiene condition records',
            riskNotes: 'Unmaintained fan bearings cause catastrophic motor burnout and building supply air loss.',
          },
          {
            activity: 'Motor electrical insulation testing, damper linkage calibration, and condensate drainage disinfection',
            frequency: 'Annually',
            frequencyMonths: [10],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'CIBSE Guide M / SFG20 / BS EN 15780',
            statutoryReference: 'Workplace (Health, Safety and Welfare) Regs 1992',
            recommendedCompetency: 'HVAC Electrical & Mechanical Engineer',
            evidenceExpected: 'Annual AHU validation certificate with motor amp draws and airflow velocities',
            riskNotes: 'Blocked condensate drains cause ceiling water ingress and microbial bacterial growth.',
          },
        ],
      },
      {
        id: 'hvac-fcu',
        categoryId: 'hvac',
        categoryName: 'HVAC & Climate Control',
        name: 'Fan Coil Units (FCU)',
        shortDescription: 'Terminal 2-pipe and 4-pipe fan coil units serving individual tenant zones, meeting rooms, and office floors.',
        defaultFrequencies: ['Quarterly', '6-Monthly', 'Annually'],
        isStatutoryOrStandard: false,
        supportsQuantity: true,
        defaultQuantity: 20,
        tasks: [
          {
            activity: 'Filter vacuum/clean, condensate tray disinfection, and return air temperature verification',
            frequency: 'Quarterly',
            frequencyMonths: [3, 6, 9, 12],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'SFG20 Maintenance Schedule 01-08',
            statutoryReference: 'Workplace Regs 1992 Reg 5',
            recommendedCompetency: 'AC / HVAC Engineer',
            evidenceExpected: 'FCU asset logbook with clean filter signoff',
            riskNotes: 'Dirty FCU filters lead to thermal comfort complaints and localized coil freezing.',
          },
          {
            activity: 'Modulating valve actuator stroke testing, electrical terminal torque check, and fan speed control audit',
            frequency: 'Annually',
            frequencyMonths: [9],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'SFG20 / CIBSE Guide M',
            statutoryReference: 'Electricity at Work Regs 1989',
            recommendedCompetency: 'HVAC BMS Controls Specialist',
            evidenceExpected: 'BMS signal verification report and actuator stroke test log',
            riskNotes: 'Stuck actuators cause simultaneous heating and cooling energy wastage.',
          },
        ],
      },
      {
        id: 'hvac-split',
        categoryId: 'hvac',
        categoryName: 'HVAC & Climate Control',
        name: 'Split Air Conditioning Systems',
        shortDescription: 'Single-split and multi-split wall, cassette, and under-ceiling air conditioning systems.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 6,
        regimeId: 'F_GAS_REFRIGERATION',
        tasks: [
          {
            activity: 'F-Gas leak test, filter sanitisation, condensate pump test, and refrigerant operating pressure log',
            frequency: '6-Monthly',
            frequencyMonths: [4, 10],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'GB F-Gas Regulations 2015 / SFG20',
            statutoryReference: 'F-Gas Regs 2015 Reg 4',
            recommendedCompetency: 'REFCOM Certified F-Gas Engineer',
            evidenceExpected: 'F-Gas service log and operational pressure check sheet',
            riskNotes: 'Unserviced split units develop iced evaporator coils and water leakage into occupied spaces.',
          },
        ],
      },
      {
        id: 'hvac-vrf',
        categoryId: 'hvac',
        categoryName: 'HVAC & Climate Control',
        name: 'VRF / VRV Heat Recovery Systems',
        shortDescription: 'Variable Refrigerant Flow (VRF/VRV) 3-pipe heat recovery multi-outdoor and indoor master units.',
        defaultFrequencies: ['Quarterly', '6-Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 2,
        regimeId: 'F_GAS_REFRIGERATION',
        tasks: [
          {
            activity: 'Statutory F-Gas refrigerant leak check, electronic sniffer test, and system run logs',
            frequency: '6-Monthly',
            frequencyMonths: [5, 11],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'GB F-Gas Regulations 2015',
            statutoryReference: 'F-Gas Regs 2015 Reg 4',
            recommendedCompetency: 'Category 1 F-Gas Certified Technician',
            evidenceExpected: 'F-Gas on-site logbook and signed certificate',
            riskNotes: 'Refrigerant leaks in occupied spaces risk asphyxiation and severe environmental fines.',
          },
          {
            activity: 'Indoor cassette filter clean, evaporator coil disinfection, condensate pump lift test, outdoor coil clean',
            frequency: '6-Monthly',
            frequencyMonths: [4, 10],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'SFG20 Maintenance Schedule / CIBSE Guide M',
            statutoryReference: 'Workplace Regs 1992',
            recommendedCompetency: 'HVAC Engineer',
            evidenceExpected: 'Service maintenance sheet with condensate pump operational test',
            riskNotes: 'Blocked outdoor condensing coils cause high-pressure trips during summer peak ambient days.',
          },
        ],
      },
      {
        id: 'hvac-chiller',
        categoryId: 'hvac',
        categoryName: 'HVAC & Climate Control',
        name: 'Central Chillers & Heat Rejection',
        shortDescription: 'Air-cooled and water-cooled scroll, screw, and centrifugal chillers providing central building chilled water.',
        defaultFrequencies: ['Quarterly', '6-Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 2,
        regimeId: 'F_GAS_REFRIGERATION',
        tasks: [
          {
            activity: 'Mandatory F-Gas direct/indirect leak inspection, refrigerant log update, and operating pressure check',
            frequency: 'Quarterly',
            frequencyMonths: [3, 6, 9, 12],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'Fluorinated Greenhouse Gases Regulations 2015 (GB F-Gas)',
            statutoryReference: 'F-Gas Regs (as amended) Reg 4 / Environment Agency Guidance',
            recommendedCompetency: 'REFCOM / City & Guilds 2079 F-Gas Certified Engineer',
            evidenceExpected: 'Statutory F-Gas logbook with engineer registration number and leak inspection record',
            riskNotes: 'Operating without F-Gas leak checks carries civil penalties up to £200,000 and environmental enforcement.',
          },
          {
            activity: 'Compressor oil acidity test, vibration analysis, condenser coil pressure wash, and control calibration',
            frequency: '6-Monthly',
            frequencyMonths: [4, 10],
            classification: 'MANUFACTURER_REQUIREMENT',
            governingBasis: 'Manufacturer OEM Specification & SFG20',
            statutoryReference: 'Pressure Systems Safety Regs 2000 (where applicable)',
            recommendedCompetency: 'Senior Chiller Systems Specialist',
            evidenceExpected: 'Chiller health audit report, oil analysis laboratory report',
            riskNotes: 'Acidic compressor oil causes internal insulation breakdown and catastrophic mechanical seizure.',
          },
        ],
      },
      {
        id: 'hvac-cooling-tower',
        categoryId: 'hvac',
        categoryName: 'HVAC & Climate Control',
        name: 'Cooling Towers & Evaporative Condensers',
        shortDescription: 'Open and closed-circuit evaporative cooling towers serving central refrigeration or industrial processes.',
        defaultFrequencies: ['Weekly', 'Monthly', 'Quarterly', '6-Monthly'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 2,
        regimeId: 'LEGIONELLA_CONTROL',
        tasks: [
          {
            activity: 'Biocide dosing check, dip-slide microbiological testing, conductivity and pH chemical monitoring',
            frequency: 'Weekly',
            frequencyMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'HSE ACOP L8 / HSG274 Part 1',
            statutoryReference: 'Health and Safety at Work Act 1974 / Notification of Cooling Towers Regs 1992',
            recommendedCompetency: 'Specialist Water Treatment Chemist / Operative',
            evidenceExpected: 'Weekly chemical dosing log and incubated dip-slide result photographs',
            riskNotes: 'Poorly treated cooling towers are the primary vector for aerosolized Legionnaires’ disease outbreaks.',
          },
          {
            activity: 'Tower pack inspection, drift eliminator clean, mechanical drain-down, thorough mechanical clean and chemical disinfection',
            frequency: '6-Monthly',
            frequencyMonths: [3, 9],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'HSE ACOP L8 / HSG274 Part 1',
            statutoryReference: 'ACOP L8 Paragraph 148',
            recommendedCompetency: 'LCA-Registered Water Hygiene Contractor',
            evidenceExpected: 'Certificate of Chlorination / Disinfection and UKAS Legionella culture laboratory certificates',
            riskNotes: 'Biofilm accumulation in packing prevents chemical penetration and creates rapid bacterial multiplication.',
          },
        ],
      },
      {
        id: 'hvac-boiler',
        categoryId: 'hvac',
        categoryName: 'HVAC & Climate Control',
        name: 'Commercial Boilers & Heating Plant',
        shortDescription: 'Atmospheric and condensing commercial gas boilers, burner assemblies, flues, and primary pumps.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 2,
        regimeId: 'GAS_SAFETY',
        tasks: [
          {
            activity: 'Statutory Gas Safe commercial inspection, flue gas combustion analysis (CO/CO2), burner service, and CP15 signoff',
            frequency: 'Annually',
            frequencyMonths: [9],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'Gas Safety (Installation and Use) Regulations 1998 Regulation 35',
            statutoryReference: 'GSIUR 1998 Reg 35 / IGEM/UP/1',
            recommendedCompetency: 'Gas Safe Commercial (COCN1 / CIGA1 / CDGA1) Registered Engineer',
            evidenceExpected: 'Gas Safe Non-Domestic Safety Certificate (CP15/CP17) and printed flue analyser strip',
            riskNotes: 'Uncertified gas plant exposes building operators to criminal prosecution and explosion/CO risk.',
          },
          {
            activity: 'Safety relief valve visual check, expansion vessel pre-charge pressure verification, and flue integrity survey',
            frequency: '6-Monthly',
            frequencyMonths: [3, 9],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'Pressure Systems Safety Regulations 2000 & SFG20',
            statutoryReference: 'PSSR 2000 ACOP L122',
            recommendedCompetency: 'Heating Engineer / Pressure Vessel Competent Person',
            evidenceExpected: 'Pressure vessel test certificate and expansion vessel pressure record',
            riskNotes: 'Failed expansion vessels cause hydraulic over-pressurisation and structural boiler damage.',
          },
        ],
      },
      {
        id: 'hvac-lev',
        categoryId: 'hvac',
        categoryName: 'HVAC & Climate Control',
        name: 'Extract Ventilation & LEV Systems',
        shortDescription: 'Industrial dust collectors, fume cupboards, welding extraction, spray booths, and kitchen canopy extract.',
        defaultFrequencies: ['14-Monthly', 'Quarterly'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 1,
        regimeId: 'LEV_EXTRACTION',
        tasks: [
          {
            activity: 'Statutory Thorough Examination and Test (TExT) of LEV system, hood face velocities, and duct transport velocities',
            frequency: '14-Monthly',
            frequencyMonths: [2],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'Control of Substances Hazardous to Health Regulations 2002 (COSHH) Regulation 9',
            statutoryReference: 'COSHH 2002 Reg 9 / HSE Guidance HSG258',
            recommendedCompetency: 'BOHS P601 Qualified LEV Commissioning Engineer',
            evidenceExpected: 'Formal statutory LEV Thorough Examination Report with hood static pressure benchmarks',
            riskNotes: 'Strict statutory requirement (max 14 months). Operating untested LEV breaches COSHH criminal law.',
          },
          {
            activity: 'Commercial kitchen canopy deep clean, extract duct grease removal, and TR19 certification',
            frequency: '6-Monthly',
            frequencyMonths: [4, 10],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BESA TR19 Grease Specification & Insurer Warranty Requirements',
            statutoryReference: 'RRO 2005 Article 17',
            recommendedCompetency: 'BESA Certified Duct Hygiene Operatives',
            evidenceExpected: 'TR19 Post-Clean Hygiene Certificate with wet film thickness (WFT) micrometer readings',
            riskNotes: 'Grease accumulation in kitchen extract ducts is the leading cause of catastrophic commercial fires.',
          },
        ],
      },
      {
        id: 'hvac-bms',
        categoryId: 'hvac',
        categoryName: 'HVAC & Climate Control',
        name: 'Building Management Systems (BMS) & Controls',
        shortDescription: 'Central BMS head-end servers, outstations, temperature/CO2 sensors, and energy meters.',
        defaultFrequencies: ['Quarterly', '6-Monthly', 'Annually'],
        isStatutoryOrStandard: false,
        supportsQuantity: false,
        defaultQuantity: 1,
        tasks: [
          {
            activity: 'Sensor calibration check, outstation communication verification, setpoint optimization, and alarm audit',
            frequency: '6-Monthly',
            frequencyMonths: [3, 9],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'CIBSE Guide H: Building Control Systems / SFG20',
            statutoryReference: 'Workplace Regs 1992',
            recommendedCompetency: 'BMS Controls Systems Specialist',
            evidenceExpected: 'BMS seasonal tuning report and sensor calibration log',
            riskNotes: 'Drifting sensors cause simultaneous heating and cooling, wasting up to 30% of building energy.',
          },
        ],
      },
    ],
  },
  {
    id: 'fire',
    name: 'Fire & Life Safety',
    description: 'Fire detection panels, manual call points, emergency lighting, fire doors, dampers, sprinklers, and risers.',
    iconName: 'Flame',
    assets: [
      {
        id: 'fire-alarm',
        categoryId: 'fire',
        categoryName: 'Fire & Life Safety',
        name: 'Fire Alarm System',
        shortDescription: 'Addressable and conventional fire alarm control panels, optical/heat detectors, call points, and interfaces.',
        defaultFrequencies: ['Weekly', 'Quarterly', '6-Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: false,
        defaultQuantity: 1,
        regimeId: 'FIRE_ALARM',
        tasks: [
          {
            activity: 'Weekly user manual call point operational test (rotating through all zones/points) and alarm audibility check',
            frequency: 'Weekly',
            frequencyMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS 5839-1:2017 Clause 44.2',
            statutoryReference: 'Regulatory Reform (Fire Safety) Order 2005 Article 17',
            recommendedCompetency: 'Appointed Building Responsible Person / Trained On-Site Facility Operative',
            evidenceExpected: 'On-site Fire Safety Logbook entry recording call point number, time, and sounder verification',
            riskNotes: 'Missing weekly tests is the single most common finding in Fire & Rescue Authority enforcement audits.',
          },
          {
            activity: 'Periodic statutory inspection by competent fire engineer, control panel standby battery load test, and 25% detector test',
            frequency: 'Quarterly',
            frequencyMonths: [3, 6, 9, 12],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS 5839-1:2017 Clause 45',
            statutoryReference: 'RRO 2005 Article 17',
            recommendedCompetency: 'BAFE / FIA Certified Fire Alarm Service Engineer',
            evidenceExpected: 'BAFE SP203-1 Fire Alarm Inspection & Servicing Certificate',
            riskNotes: 'Unchecked panel standby batteries will fail completely during mains power failure, leaving buildings unprotected.',
          },
        ],
      },
      {
        id: 'fire-emergency-light',
        categoryId: 'fire',
        categoryName: 'Fire & Life Safety',
        name: 'Emergency Lighting',
        shortDescription: 'Maintained and non-maintained emergency luminaires, exit signage boxes, and central battery systems.',
        defaultFrequencies: ['Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 45,
        regimeId: 'EMERGENCY_LIGHTING',
        tasks: [
          {
            activity: 'Monthly functional flicker test of all emergency luminaires and illuminated exit signs using fish-key switches',
            frequency: 'Monthly',
            frequencyMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS 5266-1:2016 Clause 12 / BS EN 50172',
            statutoryReference: 'RRO 2005 Article 17',
            recommendedCompetency: 'Designated Responsible Person / Trained Facilities Technician',
            evidenceExpected: 'Emergency lighting logbook recording all tested units, defects identified, and repair dates',
            riskNotes: 'Failed exit route luminaires result in immediate enforcement notices during local authority inspections.',
          },
          {
            activity: 'Annual full-duration 3-hour battery discharge test, luminaire lux level assessment, and compliance certification',
            frequency: 'Annually',
            frequencyMonths: [11],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS 5266-1:2016 Clause 12.4',
            statutoryReference: 'RRO 2005 Article 17 / Electricity at Work Regs 1989',
            recommendedCompetency: 'NICEIC / ECA Qualified Electrical Engineer',
            evidenceExpected: 'Annual Emergency Lighting Periodic Inspection & Discharge Certificate with luminaire schedule',
            riskNotes: 'Degraded NiCad/Lithium battery cells can illuminate for 10 minutes but die before statutory 3-hour requirement.',
          },
        ],
      },
      {
        id: 'fire-extinguishers',
        categoryId: 'fire',
        categoryName: 'Fire & Life Safety',
        name: 'Fire Extinguishers',
        shortDescription: 'CO2, water, foam, wet chemical, and powder portable fire extinguishers and fire blankets.',
        defaultFrequencies: ['Monthly', 'Annually', '5-Yearly'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 24,
        regimeId: 'FIRE_SAFETY_ORDER',
        tasks: [
          {
            activity: 'Monthly visual inspection of pressure gauges, safety pins, anti-tamper seals, and unobstructed access',
            frequency: 'Monthly',
            frequencyMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS 5306-3 Clause 4',
            statutoryReference: 'RRO 2005 Article 17',
            recommendedCompetency: 'Appointed Fire Warden / Facility Operative',
            evidenceExpected: 'Fire safety logbook monthly check sign-off',
            riskNotes: 'Discharged or depressurised extinguishers render staff helpless during early-stage fire incubation.',
          },
          {
            activity: 'Annual basic service, weight check, hose inspection, pressure gauge calibration, and maintenance tag application',
            frequency: 'Annually',
            frequencyMonths: [8],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS 5306-3:2017 & BS 5306-8',
            statutoryReference: 'RRO 2005 Article 17',
            recommendedCompetency: 'BAFE SP101 Certified Fire Extinguisher Technician',
            evidenceExpected: 'Annual Fire Extinguisher Inspection Certificate and individual dated asset service collar',
            riskNotes: 'Corroded canisters can rupture under pressure causing severe physical trauma.',
          },
        ],
      },
      {
        id: 'fire-doors',
        categoryId: 'fire',
        categoryName: 'Fire & Life Safety',
        name: 'Fire Doors & Shutters',
        shortDescription: 'FD30, FD60, FD120 timber and steel fire doors, intumescent/cold smoke seals, self-closing devices, and roller shutters.',
        defaultFrequencies: ['6-Monthly', 'Quarterly'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 32,
        regimeId: 'FIRE_DOORS',
        tasks: [
          {
            activity: 'Comprehensive inspection of perimeter gap tolerances (2–4mm), intumescent seals, hinge integrity, and self-closing speed',
            frequency: '6-Monthly',
            frequencyMonths: [4, 10],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS 8214:2016 / BS 9999 / Fire Safety (England) Regs 2022',
            statutoryReference: 'Regulatory Reform (Fire Safety) Order 2005 Article 17',
            recommendedCompetency: 'FDIS (Fire Door Inspection Scheme) DipFDI Certified Inspector',
            evidenceExpected: 'Fire Door Asset Register and Comprehensive Gap/Component Defect Schedule',
            riskNotes: 'A missing self-closer or 6mm gap permits smoke passage, making escape staircases impassable in minutes.',
          },
        ],
      },
      {
        id: 'fire-dampers',
        categoryId: 'fire',
        categoryName: 'Fire & Life Safety',
        name: 'Fire & Smoke Dampers',
        shortDescription: 'Mechanical fusible-link fire dampers and motorized smoke control dampers installed in ventilation ductwork.',
        defaultFrequencies: ['Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 18,
        regimeId: 'FIRE_SAFETY_ORDER',
        tasks: [
          {
            activity: 'Drop testing, visual inspection through duct access panels, thermal fuse check, internal blade clean, and reset verification',
            frequency: 'Annually',
            frequencyMonths: [7],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS 9999:2017 Annex E / BESA DW145 Guide to Good Practice',
            statutoryReference: 'RRO 2005 Article 17 / Building Regs Part B',
            recommendedCompetency: 'BESA Certified Fire Damper Testing Engineer',
            evidenceExpected: 'Damper Drop Test Schedule with before/after drop photographic evidence for each numbered damper',
            riskNotes: 'Inaccessible unmaintained dampers stuck open allow fire to spread undetected through ceiling voids.',
          },
        ],
      },
      {
        id: 'fire-sprinklers',
        categoryId: 'fire',
        categoryName: 'Fire & Life Safety',
        name: 'Automatic Fire Sprinklers',
        shortDescription: 'Wet and dry pipe automatic fire sprinkler installations, diesel/electric fire pumps, water storage tanks, and flow switches.',
        defaultFrequencies: ['Weekly', 'Monthly', 'Quarterly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: false,
        defaultQuantity: 1,
        regimeId: 'FIRE_SAFETY_ORDER',
        tasks: [
          {
            activity: 'Weekly fire pump auto-start test, water tank level check, town mains pressure check, and flow alarm verification',
            frequency: 'Weekly',
            frequencyMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS EN 12845:2015 Clause 20',
            statutoryReference: 'RRO 2005 / Insurer Warranty',
            recommendedCompetency: 'Trained Building Maintenance Technician',
            evidenceExpected: 'Sprinkler weekly test logbook signed by facility duty holder',
            riskNotes: 'Stagnant water pump seizure causes zero fire suppression when heat heads activate.',
          },
          {
            activity: 'Comprehensive quarterly and annual engineering inspection, flow switch testing, control valve lubrication, and pump churn test',
            frequency: 'Quarterly',
            frequencyMonths: [3, 6, 9, 12],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS EN 12845 / LPC Rules for Automatic Sprinkler Installations',
            statutoryReference: 'RRO 2005 Article 17',
            recommendedCompetency: 'FIRAS / LPC Certified Sprinkler Service Engineer',
            evidenceExpected: 'LPC Certificate of Inspection and flow-rate performance curve graph',
            riskNotes: 'Failure to service sprinklers invalidates commercial building property and business interruption insurance.',
          },
        ],
      },
      {
        id: 'fire-risers',
        categoryId: 'fire',
        categoryName: 'Fire & Life Safety',
        name: 'Dry & Wet Risers',
        shortDescription: 'Inlet breeching boxes, landing valves, air release valves, and pressurized riser mains for Fire Service use.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 2,
        regimeId: 'FIRE_SAFETY_ORDER',
        tasks: [
          {
            activity: '6-Monthly visual inspection of landing valves, glass boxes, padlocks, washers, and breeching inlet seals',
            frequency: '6-Monthly',
            frequencyMonths: [3, 9],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS 9990:2015 Clause 7',
            statutoryReference: 'RRO 2005 Article 17',
            recommendedCompetency: 'Fire Systems Service Specialist',
            evidenceExpected: 'Visual inspection checklist with valve closure verification',
            riskNotes: 'Vandalised or open landing valves prevent fire brigades from pressurising dry risers during high-rise fires.',
          },
          {
            activity: 'Annual full hydrostatic pressure test to 12 bar for 15 minutes, air release valve test, and flow test',
            frequency: 'Annually',
            frequencyMonths: [9],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS 9990:2015 Clause 7.4',
            statutoryReference: 'RRO 2005 Article 17',
            recommendedCompetency: 'Competent Dry Riser Pressure Test Engineer',
            evidenceExpected: 'Annual Hydrostatic Test Certificate with calibrated pressure gauge log',
            riskNotes: 'Pipe joint failures under emergency fire brigade pump pressure can flood electrical shafts and kill water pressure.',
          },
        ],
      },
      {
        id: 'fire-smoke-aov',
        categoryId: 'fire',
        categoryName: 'Fire & Life Safety',
        name: 'Smoke Control & Automatic Opening Vents (AOV)',
        shortDescription: 'Stairwell automatic opening vents (AOV), mechanical smoke extract fans, and pressure differential systems.',
        defaultFrequencies: ['Monthly', '6-Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 4,
        regimeId: 'FIRE_SAFETY_ORDER',
        tasks: [
          {
            activity: 'Monthly functional opening test of AOV roof/window louvres via manual control point and fire alarm interface',
            frequency: 'Monthly',
            frequencyMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS 9999 / BS 7346-8',
            statutoryReference: 'RRO 2005 Article 17',
            recommendedCompetency: 'Smoke Control Maintenance Technician',
            evidenceExpected: 'AOV monthly operational test record in fire logbook',
            riskNotes: 'Stuck AOVs trap toxic hot smoke in escape stairs, making building evacuation impossible.',
          },
        ],
      },
    ],
  },
  {
    id: 'electrical',
    name: 'Electrical',
    description: 'Fixed wire distribution, switchboards, EV charging points, lightning protection, standby diesel generators, and UPS.',
    iconName: 'Zap',
    assets: [
      {
        id: 'elec-eicr',
        categoryId: 'electrical',
        categoryName: 'Electrical',
        name: 'Fixed Electrical Installation (EICR)',
        shortDescription: 'Main low voltage distribution panels, sub-distribution boards, sub-mains cables, power and lighting circuits.',
        defaultFrequencies: ['3-Yearly', '5-Yearly', 'Risk-Based'],
        isStatutoryOrStandard: true,
        supportsQuantity: false,
        defaultQuantity: 1,
        regimeId: 'ELECTRICAL_INSTALLATION',
        tasks: [
          {
            activity: 'Periodic statutory inspection and testing of fixed wiring, insulation resistance, earth fault loop, and RCD trip times',
            frequency: '5-Yearly',
            frequencyMonths: [6],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'Electricity at Work Regulations 1989 Regulation 4(2) & BS 7671:2018+A2:2022',
            statutoryReference: 'EAWR 1989 Reg 4(2) / IET Guidance Note 3',
            recommendedCompetency: 'NICEIC Approved Contractor / JIB Qualified Approved Electrician (City & Guilds 2391)',
            evidenceExpected: 'Electrical Installation Condition Report (EICR) with Satisfactory overall outcome and C1/C2 rectification records',
            riskNotes: 'Unsatisfactory EICR or unaddressed C1/C2 defects leave the employer criminally liable for electrical injury/fire.',
          },
        ],
      },
      {
        id: 'elec-thermography',
        categoryId: 'electrical',
        categoryName: 'Electrical',
        name: 'Distribution Boards & Thermal Imaging',
        shortDescription: 'Main switchgear, busbars, power factor correction, and panel distribution boards under normal operational load.',
        defaultFrequencies: ['Annually'],
        isStatutoryOrStandard: false,
        supportsQuantity: true,
        defaultQuantity: 8,
        tasks: [
          {
            activity: 'Non-intrusive infrared thermal imaging survey of all electrical panels under normal load to detect loose terminations and phase imbalance',
            frequency: 'Annually',
            frequencyMonths: [5],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'IET Code of Practice for Electrical Safety Management / SFG20',
            statutoryReference: 'EAWR 1989 Reg 4(2)',
            recommendedCompetency: 'Certified ITC Level II Thermographer & Qualified Electrician',
            evidenceExpected: 'Thermal Imaging Inspection Report with comparative thermograms, delta-T severity matrix, and remedial schedule',
            riskNotes: '90% of commercial electrical fires originate from loose connection micro-arcing that thermal imaging detects months in advance.',
          },
        ],
      },
      {
        id: 'elec-pat',
        categoryId: 'electrical',
        categoryName: 'Electrical',
        name: 'Portable Electrical Equipment (PAT)',
        shortDescription: 'Plug-in IT hardware, kitchen appliances, cleaning machines, and extension leads.',
        defaultFrequencies: ['Annually', '2-Yearly', 'Risk-Based'],
        isStatutoryOrStandard: false,
        supportsQuantity: true,
        defaultQuantity: 120,
        regimeId: 'PORTABLE_APPLIANCES',
        tasks: [
          {
            activity: 'Formal visual inspection, earth continuity testing, insulation resistance testing, and asset tagging',
            frequency: 'Annually',
            frequencyMonths: [4],
            classification: 'RISK_BASED_SITE_SPECIFIC',
            governingBasis: 'IET Code of Practice for In-service Inspection and Testing (5th Edition)',
            statutoryReference: 'Electricity at Work Regs 1989 Reg 4 / PUWER 1998',
            recommendedCompetency: 'Competent Trained PAT Tester (City & Guilds 2377)',
            evidenceExpected: 'Complete Asset PAT Register with test instrument calibration certificate and failed equipment quarantine record',
            riskNotes: 'Damaged power cords on mobile appliances represent the highest frequency cause of workplace electric shock.',
          },
        ],
      },
      {
        id: 'elec-lightning',
        categoryId: 'electrical',
        categoryName: 'Electrical',
        name: 'Lightning Protection Systems (LPS)',
        shortDescription: 'Roof strike tape, air terminals, down conductors, earth test pits, and surge protection devices (SPDs).',
        defaultFrequencies: ['Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: false,
        defaultQuantity: 1,
        regimeId: 'LIGHTNING_PROTECTION',
        tasks: [
          {
            activity: 'Visual inspection of roof tape bonding, mechanical connection torque check, and earth pit resistance to earth testing',
            frequency: 'Annually',
            frequencyMonths: [8],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS EN 62305:2011 Part 3 & SFG20',
            statutoryReference: 'Electricity at Work Regulations 1989 / BS EN 62305',
            recommendedCompetency: 'ATLAS / NVQ Level 3 Qualified Lightning Protection Specialist',
            evidenceExpected: 'Annual Lightning Protection Test Certificate recording individual pit ohmic resistance (target < 10 ohms)',
            riskNotes: 'Tested on an 11-month cycle to account for seasonal variations in ground soil resistivity.',
          },
        ],
      },
      {
        id: 'elec-generator',
        categoryId: 'electrical',
        categoryName: 'Electrical',
        name: 'Standby Generator & Fuel Systems',
        shortDescription: 'Diesel backup generators, automatic transfer switches (ATS), fuel polishing, and exhaust systems.',
        defaultFrequencies: ['Monthly', 'Quarterly', 'Annually'],
        isStatutoryOrStandard: false,
        supportsQuantity: true,
        defaultQuantity: 1,
        tasks: [
          {
            activity: 'Monthly off-load test run, fluid level check (oil, coolant, fuel), battery charger status, and heater block inspection',
            frequency: 'Monthly',
            frequencyMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'BS 9999 / SFG20 / Manufacturer Guidelines',
            statutoryReference: 'Workplace Regs 1992',
            recommendedCompetency: 'Critical Power Maintenance Technician',
            evidenceExpected: 'Generator monthly test run sheet recording oil pressure, frequency (50Hz), and voltage output',
            riskNotes: 'Generators that sit without monthly running develop fuel degradation and battery failure, preventing start during blackouts.',
          },
          {
            activity: 'Annual full resistive load bank testing (100% capacity for 2–4 hours), fuel polishing, and fluid replacement',
            frequency: 'Annually',
            frequencyMonths: [10],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'SFG20 / CIBSE Guide M',
            statutoryReference: 'Health & Safety at Work Act 1974',
            recommendedCompetency: 'Senior Power Generation Engineer',
            evidenceExpected: 'Load bank test certificate with stepped load graphs and engine exhaust temperature data',
            riskNotes: 'Wet stacking in diesel engines causes soot accumulation that reduces emergency generator capacity when needed most.',
          },
        ],
      },
      {
        id: 'elec-ups',
        categoryId: 'electrical',
        categoryName: 'Electrical',
        name: 'Uninterruptible Power Supplies (UPS)',
        shortDescription: 'Central UPS inverters, static bypass switches, and valve-regulated lead-acid (VRLA) battery strings.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: false,
        supportsQuantity: true,
        defaultQuantity: 2,
        tasks: [
          {
            activity: 'UPS battery cell internal impedance testing, DC bus voltage check, bypass switch test, and fan operation check',
            frequency: '6-Monthly',
            frequencyMonths: [3, 9],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'SFG20 / IEEE 1188 / Manufacturer Guidelines',
            statutoryReference: 'Electricity at Work Regs 1989',
            recommendedCompetency: 'UPS Certified Power Engineer',
            evidenceExpected: 'UPS battery impedance report with cell-by-cell milliohm degradation readings',
            riskNotes: 'A single high-impedance battery cell can collapse the entire DC bus during a mains outage.',
          },
        ],
      },
      {
        id: 'elec-ev',
        categoryId: 'electrical',
        categoryName: 'Electrical',
        name: 'EV Charging Infrastructure',
        shortDescription: 'Commercial AC 7–22kW destination chargers and DC rapid charging posts in commercial car parks.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: false,
        supportsQuantity: true,
        defaultQuantity: 6,
        tasks: [
          {
            activity: 'RCD Type B trip testing, earth loop impedance check, physical cable and holster inspection, firmware and connectivity check',
            frequency: 'Annually',
            frequencyMonths: [6],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'IET Code of Practice for Electric Vehicle Charging Equipment Installation / BS 7671 Section 722',
            statutoryReference: 'Electricity at Work Regs 1989',
            recommendedCompetency: 'EVSE Certified Electrician (City & Guilds 2919)',
            evidenceExpected: 'EV Charger Electrical Inspection Certificate with RCD trip response time log',
            riskNotes: 'Exposed outdoor charging hardware is prone to physical impact damage and insulation degradation.',
          },
        ],
      },
      {
        id: 'elec-solar',
        categoryId: 'electrical',
        categoryName: 'Electrical',
        name: 'Solar PV (Photovoltaic) Arrays',
        shortDescription: 'Roof-mounted solar PV modules, DC string isolators, grid-tied inverters, and generation meters.',
        defaultFrequencies: ['Annually'],
        isStatutoryOrStandard: false,
        supportsQuantity: false,
        defaultQuantity: 1,
        tasks: [
          {
            activity: 'DC string I-V curve tracing, solar inverter thermal imaging, DC isolator contact check, and panel cleaning',
            frequency: 'Annually',
            frequencyMonths: [5],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'MCS Standards / BS EN 62446 / IET Guidance',
            statutoryReference: 'Electricity at Work Regs 1989',
            recommendedCompetency: 'MCS Certified Solar PV Engineer',
            evidenceExpected: 'Solar PV Test Certificate and string performance yield log',
            riskNotes: 'Degraded DC isolators on solar arrays represent a major commercial roof fire hazard.',
          },
        ],
      },
    ],
  },
  {
    id: 'water',
    name: 'Water & Plumbing',
    description: 'Legionella control, sentinel temperature monitoring, cold water storage tanks, thermostatic mixing valves, and booster pumps.',
    iconName: 'Droplets',
    assets: [
      {
        id: 'water-lra',
        categoryId: 'water',
        categoryName: 'Water & Plumbing',
        name: 'Legionella Risk Assessment (LRA)',
        shortDescription: 'Building-wide water asset inventory, risk evaluation, asset schematics, and water management plan.',
        defaultFrequencies: ['2-Yearly', 'Risk-Based'],
        isStatutoryOrStandard: true,
        supportsQuantity: false,
        defaultQuantity: 1,
        regimeId: 'LEGIONELLA_CONTROL',
        tasks: [
          {
            activity: 'Comprehensive site survey, water system schematic review, aerosol risk identification, and written control scheme update',
            frequency: '2-Yearly',
            frequencyMonths: [3],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'HSE Approved Code of Practice L8 (4th Edition) & HSG274',
            statutoryReference: 'Health and Safety at Work etc. Act 1974 / COSHH Regs 2002',
            recommendedCompetency: 'Water Management Society (WMSoc) Senior Risk Assessor / LCA Registered Assessor',
            evidenceExpected: 'Formal Legionella Risk Assessment Document, asset register, schematic, and prioritized remedial action plan',
            riskNotes: 'Must be reviewed immediately if there is a change of building use, system modification, or unexplained test failure.',
          },
        ],
      },
      {
        id: 'water-monitoring',
        categoryId: 'water',
        categoryName: 'Water & Plumbing',
        name: 'Sentinel Temperature Monitoring & Flushing',
        shortDescription: 'Incoming mains supply, calorifiers, water heaters, and nearest/furthest sentinel outlets.',
        defaultFrequencies: ['Weekly', 'Monthly'],
        isStatutoryOrStandard: true,
        supportsQuantity: false,
        defaultQuantity: 1,
        regimeId: 'LEGIONELLA_CONTROL',
        tasks: [
          {
            activity: 'Weekly flushing of low-use outlets, dead-legs, and expansion loops for at least 2 minutes',
            frequency: 'Weekly',
            frequencyMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'HSG274 Part 2 Table 2.1',
            statutoryReference: 'ACOP L8 Paragraph 51',
            recommendedCompetency: 'Appointed Building Caretaker / Water Technician',
            evidenceExpected: 'Weekly little-used outlet flushing logbook entries',
            riskNotes: 'Stagnant water between 20°C and 45°C allows Legionella bacteria to double every 90 minutes.',
          },
          {
            activity: 'Monthly sentinel temperature monitoring (cold water <20°C within 2 minutes; hot water >50°C within 1 minute)',
            frequency: 'Monthly',
            frequencyMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'HSE ACOP L8 & HSG274 Part 2',
            statutoryReference: 'ACOP L8 / HSG274 Part 2',
            recommendedCompetency: 'Competent Water Hygiene Technician',
            evidenceExpected: 'Monthly Water Temperature Log Sheets with calibrated digital probe serial numbers',
            riskNotes: 'Failing to record hot and cold water temperatures constitutes a strict liability breach under health & safety law.',
          },
        ],
      },
      {
        id: 'water-tanks',
        categoryId: 'water',
        categoryName: 'Water & Plumbing',
        name: 'Cold Water Storage Tanks (CWST)',
        shortDescription: 'Potable and non-potable GRP cold water storage cisterns, insect screens, warning pipes, and insulation.',
        defaultFrequencies: ['Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 2,
        regimeId: 'LEGIONELLA_CONTROL',
        tasks: [
          {
            activity: 'Annual internal visual condition inspection, water surface survey, sediment measurement, insect screen integrity check, and temperature profile',
            frequency: 'Annually',
            frequencyMonths: [6],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'HSE ACOP L8 & HSG274 Part 2 Table 2.1',
            statutoryReference: 'Water Supply (Water Fittings) Regulations 1999',
            recommendedCompetency: 'LCA Registered Water Hygiene Engineer',
            evidenceExpected: 'Annual Tank Inspection Certificate with internal/external condition photographs',
            riskNotes: 'Drain-down, cleaning and disinfection is triggered only when visual inspection shows sediment, stagnation, or contamination.',
          },
        ],
      },
      {
        id: 'water-tmv',
        categoryId: 'water',
        categoryName: 'Water & Plumbing',
        name: 'Thermostatic Mixing Valves (TMVs)',
        shortDescription: 'Under-basin and shower TMV2 / TMV3 valves regulating blended water outlet temperature.',
        defaultFrequencies: ['Annually', '6-Monthly'],
        isStatutoryOrStandard: false,
        supportsQuantity: true,
        defaultQuantity: 16,
        tasks: [
          {
            activity: 'Fail-safe shut-off test (cold water isolation test), blended delivery temperature check (38°C–43°C), and strainer clean',
            frequency: 'Annually',
            frequencyMonths: [7],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'HTM 04-01 / D08 / HSG274 Part 2',
            statutoryReference: 'Workplace Regs 1992 / Health & Safety at Work Act 1974',
            recommendedCompetency: 'Plumbing / Water Hygiene Engineer',
            evidenceExpected: 'TMV Validation Certificate recording initial temp, isolated cold fail-safe operation, and reset temp',
            riskNotes: 'Failed TMVs allow scalding water (60°C+) to reach vulnerable occupants, causing severe thermal burn injuries.',
          },
        ],
      },
      {
        id: 'water-booster',
        categoryId: 'water',
        categoryName: 'Water & Plumbing',
        name: 'Water Booster Sets & Pressurisation Units',
        shortDescription: 'Multi-pump variable speed cold water booster sets, expansion vessels, and pressurisation units.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: false,
        supportsQuantity: true,
        defaultQuantity: 1,
        tasks: [
          {
            activity: 'Pump changeover verification, pressure vessel pre-charge check, mechanical seal inspection, and transducer calibration',
            frequency: '6-Monthly',
            frequencyMonths: [4, 10],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'SFG20 / CIBSE Guide M',
            statutoryReference: 'Workplace Regs 1992',
            recommendedCompetency: 'Pump Service Engineer',
            evidenceExpected: 'Booster set service report with pump run hours and cut-in/cut-out pressure logs',
            riskNotes: 'Failed booster pumps result in total loss of water supply to upper building floors.',
          },
        ],
      },
    ],
  },
  {
    id: 'vertical',
    name: 'Lifting & Vertical Transport',
    description: 'Passenger lifts, goods lifts, platform lifts, escalators, and building maintenance unit (BMU) window cleaning cradles.',
    iconName: 'Layers',
    assets: [
      {
        id: 'lift-passenger',
        categoryId: 'vertical',
        categoryName: 'Lifting & Vertical Transport',
        name: 'Passenger Lifts',
        shortDescription: 'Traction and hydraulic passenger lifts carrying building occupants and visitors across floors.',
        defaultFrequencies: ['Monthly', '6-Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 2,
        regimeId: 'PASSENGER_LIFTS',
        tasks: [
          {
            activity: 'Statutory independent Thorough Examination of lifting mechanisms, safety gears, car doors, governors, and ropes',
            frequency: '6-Monthly',
            frequencyMonths: [5, 11],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'Lifting Operations and Lifting Equipment Regulations 1998 (LOLER) Regulation 9(3)(a)',
            statutoryReference: 'LOLER 1998 Reg 9(3)(a) / SAFed Guidelines',
            recommendedCompetency: 'Independent Engineer Surveyor (e.g. Zurich, Allianz, Bureau Veritas)',
            evidenceExpected: 'LOLER Report of Thorough Examination with defect categorization (Time-limited vs Immediate Danger Category A)',
            riskNotes: 'Strict criminal statutory requirement (max 6-month interval). Operating without a valid LOLER report is illegal.',
          },
          {
            activity: 'Routine planned preventative servicing, motor room lubrication, guide shoe wear check, brake testing, and autodialler check',
            frequency: 'Monthly',
            frequencyMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'BS EN 13015 / SFG20 Schedule 29',
            statutoryReference: 'PUWER 1998 Regulation 5',
            recommendedCompetency: 'LEIA Registered Lift Service Engineer',
            evidenceExpected: 'Lift service docket, motor room maintenance logbook entry',
            riskNotes: 'Routine monthly servicing is legally distinct from the independent 6-monthly LOLER examination; both are required.',
          },
        ],
      },
      {
        id: 'lift-goods',
        categoryId: 'vertical',
        categoryName: 'Lifting & Vertical Transport',
        name: 'Goods Lifts & Dock Levellers',
        shortDescription: 'Heavy-duty hydraulic and mechanical goods lifts, scissor lifts, and loading bay dock levellers.',
        defaultFrequencies: ['Annually', '6-Monthly'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 1,
        regimeId: 'GOODS_LIFTS',
        tasks: [
          {
            activity: 'Statutory independent Thorough Examination of hydraulic rams, chains, interlocking barriers, and structural guides',
            frequency: 'Annually',
            frequencyMonths: [9],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'Lifting Operations and Lifting Equipment Regulations 1998 (LOLER) Regulation 9(3)(b)',
            statutoryReference: 'LOLER 1998 Reg 9(3)(b) / PUWER 1998',
            recommendedCompetency: 'Competent Lift Engineer Surveyor',
            evidenceExpected: 'LOLER Thorough Examination Certificate for Goods Handling Equipment',
            riskNotes: 'Applies to lifting equipment used solely for goods handling. Max statutory interval is 12 months.',
          },
        ],
      },
      {
        id: 'lift-platform',
        categoryId: 'vertical',
        categoryName: 'Lifting & Vertical Transport',
        name: 'Platform Lifts & DDA Access Lifts',
        shortDescription: 'Vertical screw and hydraulic platform access lifts providing accessibility across split levels.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 1,
        regimeId: 'PASSENGER_LIFTS',
        tasks: [
          {
            activity: 'Statutory 6-Monthly LOLER Thorough Examination of screw drive, drive nut wear, interlocks, and emergency lowering',
            frequency: '6-Monthly',
            frequencyMonths: [4, 10],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'LOLER 1998 Reg 9(3)(a) / BS 6440',
            statutoryReference: 'LOLER 1998 / Equality Act 2010',
            recommendedCompetency: 'Independent Lift Surveyor',
            evidenceExpected: 'LOLER Thorough Examination Certificate for Person-Lifting Platform',
            riskNotes: 'Drive nut wear on screw platform lifts can cause sudden car drop if unmeasured.',
          },
        ],
      },
      {
        id: 'lift-bmu',
        categoryId: 'vertical',
        categoryName: 'Lifting & Vertical Transport',
        name: 'Building Maintenance Units (BMU) & Cradles',
        shortDescription: 'Roof-mounted powered BMU access machines, monorails, traversing gantries, and suspended window cleaning cradles.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 1,
        regimeId: 'WORKING_AT_HEIGHT',
        tasks: [
          {
            activity: 'Statutory LOLER Thorough Examination of hoist winches, wire ropes, safety harnesses anchorages, and track brakes',
            frequency: '6-Monthly',
            frequencyMonths: [4, 10],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'LOLER 1998 Reg 9(3)(a) & BS 6037-1 Code of practice for planning, installation and use of BMUs',
            statutoryReference: 'Work at Height Regs 2005 / LOLER 1998',
            recommendedCompetency: 'Specialist BMU Competent Engineer Surveyor',
            evidenceExpected: 'LOLER 6-Monthly Thorough Examination Report and proof-load test log',
            riskNotes: 'Suspended man-carrying equipment carries catastrophic fatal fall liability if operated without valid 6M LOLER.',
          },
        ],
      },
    ],
  },
  {
    id: 'security',
    name: 'Security & Access Control',
    description: 'Automatic doors, turnstiles, vehicle barriers, CCTV surveillance, access control, and intruder alarms.',
    iconName: 'Shield',
    assets: [
      {
        id: 'sec-auto-door',
        categoryId: 'security',
        categoryName: 'Security & Access Control',
        name: 'Automatic Sliding & Swing Doors',
        shortDescription: 'Commercial entrance automatic sliding doors, revolving doors, swing operators, and radar safety sensors.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 3,
        tasks: [
          {
            activity: 'Safety sensor presence test, dynamic impact force measurement, emergency breakout mechanism test, and battery fail-safe release test',
            frequency: '6-Monthly',
            frequencyMonths: [3, 9],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS EN 16005 Power operated pedestrian doorsets / Supply of Machinery (Safety) Regs 2008',
            statutoryReference: 'Workplace (Health, Safety and Welfare) Regs 1992 Reg 18',
            recommendedCompetency: 'ADSA (Automatic Door Suppliers Association) BS EN 16005 Certified Technician',
            evidenceExpected: 'BS EN 16005 Safety Checklist and force measurement verification certificate',
            riskNotes: 'Defective automatic doors can crush children or elderly visitors, resulting in heavy civil liability and HSE prosecution.',
          },
        ],
      },
      {
        id: 'sec-access',
        categoryId: 'security',
        categoryName: 'Security & Access Control',
        name: 'Access Control & Interlocks',
        shortDescription: 'Proximity card/fob readers, biometric access, magnetic locks (maglocks), and fire alarm interface release relays.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 12,
        regimeId: 'FIRE_SAFETY_ORDER',
        tasks: [
          {
            activity: 'Fire alarm fail-safe interface test (ensuring 100% immediate release of all magnetic locks on fire signal), green break-glass switch audit',
            frequency: '6-Monthly',
            frequencyMonths: [5, 11],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS EN 60839-11-1 / BS 7273-4 Code of practice for the operation of fire protection measures',
            statutoryReference: 'RRO 2005 Article 14 (Emergency routes and exits)',
            recommendedCompetency: 'NSI / SSAIB Certified Access Control Specialist',
            evidenceExpected: 'Access control fire interface test certificate signed jointly with fire alarm technician',
            riskNotes: 'Locked magnetic doors that fail to release during a fire trap occupants inside burning buildings.',
          },
        ],
      },
      {
        id: 'sec-cctv',
        categoryId: 'security',
        categoryName: 'Security & Access Control',
        name: 'CCTV Surveillance & Recording',
        shortDescription: 'IP camera networks, PTZ cameras, network video recorders, storage hard drives, and remote monitoring feeds.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: false,
        supportsQuantity: true,
        defaultQuantity: 16,
        tasks: [
          {
            activity: 'Camera lens cleaning, focus adjustment, recording retention verification (minimum 31 days), time-synchronisation check, and UPS test',
            frequency: '6-Monthly',
            frequencyMonths: [6, 12],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'BS EN 62676 / ICO CCTV Code of Practice / SFG20',
            statutoryReference: 'UK GDPR / Data Protection Act 2018',
            recommendedCompetency: 'Security Systems Engineer',
            evidenceExpected: 'CCTV operational health report and camera view archive verification log',
            riskNotes: 'Out-of-focus or unrecorded CCTV renders post-incident police investigations useless and breaches lease covenants.',
          },
        ],
      },
      {
        id: 'sec-intruder',
        categoryId: 'security',
        categoryName: 'Security & Access Control',
        name: 'Intruder Alarm & DualCom Link',
        shortDescription: 'Grade 2/3 intruder alarm panels, PIR sensors, door contacts, vibration detectors, and ARC signalling.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: false,
        supportsQuantity: false,
        defaultQuantity: 1,
        tasks: [
          {
            activity: 'Alarm receiving centre (ARC) signal test, standby battery test, PIR walk test, and tamper loop verification',
            frequency: '6-Monthly',
            frequencyMonths: [4, 10],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'PD 6662 / BS 8243 / NSI & SSAIB Codes',
            statutoryReference: 'Insurer Policy Warranty',
            recommendedCompetency: 'NSI Gold Security Engineer',
            evidenceExpected: 'Intruder alarm service certificate with ARC signal receipt time-stamp',
            riskNotes: 'Unserviced intruder alarms cause police URN response withdrawal following repeated false activations.',
          },
        ],
      },
    ],
  },
  {
    id: 'fabric',
    name: 'Building Fabric',
    description: 'Roof membranes, rainwater drainage, cladding inspections, curtain walling, man-safe fall arrest, and structural seals.',
    iconName: 'Home',
    assets: [
      {
        id: 'fab-roof',
        categoryId: 'fabric',
        categoryName: 'Building Fabric',
        name: 'Roof Membranes & Rainwater Drainage',
        shortDescription: 'Flat roof single-ply/bitumen membranes, parapet flashings, rainwater outlets, box gutters, and downpipes.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: false,
        supportsQuantity: false,
        defaultQuantity: 1,
        tasks: [
          {
            activity: 'Pre-winter and post-winter debris clearance from box gutters and rainwater outlets, membrane seam inspection, and flashing check',
            frequency: '6-Monthly',
            frequencyMonths: [4, 10],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'SFG20 Maintenance Schedule 40-01 / CIRIA Guidance',
            statutoryReference: 'Building Regulations / Occupiers Liability Act 1957',
            recommendedCompetency: 'Fabric Maintenance & Working at Height Team',
            evidenceExpected: 'Roof condition photographic inspection report with gutter clearance signoff',
            riskNotes: 'Blocked rainwater outlets during flash storms cause catastrophic roof ponding and structural ceiling collapses.',
          },
        ],
      },
      {
        id: 'fab-fall-arrest',
        categoryId: 'fabric',
        categoryName: 'Building Fabric',
        name: 'Mansafe Fall Arrest & Eyebolts',
        shortDescription: 'Tensioned horizontal wire lifeline systems, single-point eyebolts, guardrails, and roof access ladders.',
        defaultFrequencies: ['Annually', '6-Monthly'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 6,
        regimeId: 'WORKING_AT_HEIGHT',
        tasks: [
          {
            activity: 'Statutory mechanical pull-testing of eyebolts, wire rope tension measurement, swage inspection, and calibration certification',
            frequency: 'Annually',
            frequencyMonths: [4],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'BS EN 795:2012 / BS 7883:2019 Code of practice for design, selection and inspection of anchor devices',
            statutoryReference: 'Work at Height Regulations 2005 Regulation 12',
            recommendedCompetency: 'Qualified Fall Protection Inspection Engineer',
            evidenceExpected: 'Annual Fall Protection Test Certificate and structural load pull-test report (target 6kN / 10kN)',
            riskNotes: 'Allowing contractors onto an untested roof without certified anchor points creates direct employer criminal liability.',
          },
        ],
      },
      {
        id: 'fab-cladding',
        categoryId: 'fabric',
        categoryName: 'Building Fabric',
        name: 'Façade, Cladding & Glazing',
        shortDescription: 'Composite cladding panels, curtain walling pressure plates, structural silicone seals, and exterior masonry.',
        defaultFrequencies: ['Annually', '2-Yearly'],
        isStatutoryOrStandard: false,
        supportsQuantity: false,
        defaultQuantity: 1,
        tasks: [
          {
            activity: 'Tactile and visual condition survey of cladding fasteners, perished mastic seals, spalling masonry, and cracked glazing units',
            frequency: 'Annually',
            frequencyMonths: [7],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'CWCT (Centre for Window and Cladding Technology) Guidelines / SFG20',
            statutoryReference: 'Building Safety Act 2022 / Occupiers Liability Act',
            recommendedCompetency: 'IRATA Rope Access Building Surveyor / Façade Specialist',
            evidenceExpected: 'High-Level Façade Inspection Photographic Log and Defect Mapping Register',
            riskNotes: 'Early detection of mastic seal degradation prevents costly internal water ingress damage to tenant finishes.',
          },
        ],
      },
    ],
  },
  {
    id: 'grounds',
    name: 'External Areas / Grounds',
    description: 'External security lighting, car parks, drainage interceptors, boundary fencing, automated gates, and winter gritting.',
    iconName: 'Trees',
    assets: [
      {
        id: 'grounds-lighting',
        categoryId: 'grounds',
        categoryName: 'External Areas / Grounds',
        name: 'External Area & Car Park Lighting',
        shortDescription: 'Column-mounted LED floodlights, pedestrian bollard luminaires, photocell controls, and underground cabling.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: false,
        supportsQuantity: true,
        defaultQuantity: 12,
        tasks: [
          {
            activity: 'Photocell lux calibration, column door earthing check, luminaire cleaning, and dark-spot illumination survey',
            frequency: '6-Monthly',
            frequencyMonths: [3, 9],
            classification: 'SFG20_PLANNED_PRACTICE',
            governingBasis: 'CIBSE Lighting Guide LG6: The outdoor environment / SFG20',
            statutoryReference: 'Workplace (Health, Safety and Welfare) Regs 1992 Reg 8',
            recommendedCompetency: 'Commercial Electrician',
            evidenceExpected: 'External lighting maintenance report and lux level audit sheet',
            riskNotes: 'Dark car parks and walkways dramatically increase slip/trip claims and personal security incidents.',
          },
        ],
      },
      {
        id: 'grounds-interceptor',
        categoryId: 'grounds',
        categoryName: 'External Areas / Grounds',
        name: 'Petrol / Oil Interceptors & Drainage',
        shortDescription: 'Underground oil/petrol separators in car parks, service yards, and heavy vehicle washdown bays.',
        defaultFrequencies: ['6-Monthly', 'Annually'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 1,
        tasks: [
          {
            activity: 'Sludge and oil layer thickness measurement, automatic warning alarm probe test, and coalescence filter wash/replace',
            frequency: '6-Monthly',
            frequencyMonths: [5, 11],
            classification: 'LEGAL_STATUTORY_DUTY',
            governingBasis: 'BS EN 858-2 / Environment Agency Pollution Prevention Guidelines (PPG3 / GPP3)',
            statutoryReference: 'Environmental Permitting (England and Wales) Regs 2016 / Water Resources Act 1991',
            recommendedCompetency: 'Licensed Waste Environmental Drainage Engineer',
            evidenceExpected: 'Interceptor Service Report, alarm calibration certificate, and waste consignment notes for removed sludge',
            riskNotes: 'Allowing hydrocarbon runoff to enter surface water drainage carries unlimited Environment Agency prosecution fines.',
          },
        ],
      },
      {
        id: 'grounds-gates',
        categoryId: 'grounds',
        categoryName: 'External Areas / Grounds',
        name: 'Automated Vehicle Gates & Barriers',
        shortDescription: 'Automated sliding/cantilever security gates, rising arm barriers, inductive loop detectors, and safety edges.',
        defaultFrequencies: ['6-Monthly'],
        isStatutoryOrStandard: true,
        supportsQuantity: true,
        defaultQuantity: 2,
        tasks: [
          {
            activity: 'Dynamic impact force testing, photoelectric beam alignment, safety edge contact test, and manual override release test',
            frequency: '6-Monthly',
            frequencyMonths: [4, 10],
            classification: 'BRITISH_INDUSTRY_STANDARD',
            governingBasis: 'BS EN 12453 / BS EN 12445 / DHF Code of Practice for Powered Gates',
            statutoryReference: 'Supply of Machinery (Safety) Regulations 2008 / Workplace Regs 1992',
            recommendedCompetency: 'Gate Safe / DHF Certified Powered Gate Engineer',
            evidenceExpected: 'Powered Gate Force Testing Certificate with calibrated load cell graph data',
            riskNotes: 'Unchecked automated gates have caused multiple fatal crushing accidents in the UK with heavy corporate convictions.',
          },
        ],
      },
    ],
  },
];

export function getAllAssetDefinitions(): CommercialAssetDefinition[] {
  return COMMERCIAL_ASSET_CATEGORIES.flatMap((c) => c.assets);
}

export function getAssetById(id: string): CommercialAssetDefinition | undefined {
  return getAllAssetDefinitions().find((a) => a.id === id);
}
