import { CommunityCategory } from './types';

export const COMMUNITY_CATEGORIES: CommunityCategory[] = [
  {
    id: 'cat-general-fm',
    slug: 'general-fm',
    name: 'General FM',
    shortDescription: 'Facilities management practice, leadership and day-to-day operations.',
    longDescription:
      'Strategic facilities management practice, operational management, leadership across estates, client relationships, and practical problem solving in the built environment.',
    icon: 'Building2',
    displayOrder: 1,
    status: 'active',
    visibility: 'public',
    postingPermissions: 'members',
    discussionCount: 4,
    lastActivityAt: '2026-08-27T16:45:00Z',
  },
  {
    id: 'cat-compliance-hs',
    slug: 'compliance-health-safety',
    name: 'Compliance & Health + Safety',
    shortDescription: 'Compliance management, legislation, audits, risk and statutory governance.',
    longDescription:
      'Statutory compliance tracking, dutyholder obligations, risk assessments, HSE enforcement, audits, health and safety management, and legal liabilities for facilities professionals.',
    icon: 'ShieldCheck',
    displayOrder: 2,
    status: 'active',
    visibility: 'public',
    postingPermissions: 'members',
    discussionCount: 6,
    lastActivityAt: '2026-08-27T17:10:00Z',
  },
  {
    id: 'cat-engineering-me',
    slug: 'engineering-me',
    name: 'Engineering & M&E',
    shortDescription: 'Mechanical, electrical, HVAC, BMS, plant and technical building operations.',
    longDescription:
      'Hard FM delivery, mechanical and electrical engineering, chilled water systems, AHUs, switchgear, BMS controls, lifecycle replacement, and technical problem diagnosis.',
    icon: 'Wrench',
    displayOrder: 3,
    status: 'active',
    visibility: 'public',
    postingPermissions: 'members',
    discussionCount: 5,
    lastActivityAt: '2026-08-27T15:20:00Z',
  },
  {
    id: 'cat-fire-building-safety',
    slug: 'fire-building-safety',
    name: 'Fire & Building Safety',
    shortDescription: 'Building Safety Act, fire doors, compartmentation, golden thread and life safety.',
    longDescription:
      'Building Safety Act 2022 dutyholder duties, Accountable Person responsibilities, mandatory occurrence reporting, Golden Thread compliance, fire risk assessments, compartmentation, and life safety systems.',
    icon: 'Flame',
    displayOrder: 4,
    status: 'active',
    visibility: 'public',
    postingPermissions: 'members',
    discussionCount: 7,
    lastActivityAt: '2026-08-27T17:35:00Z',
  },
  {
    id: 'cat-water-hygiene',
    slug: 'water-hygiene',
    name: 'Water Hygiene',
    shortDescription: 'Legionella, water systems, testing, monitoring, flushing and risk management.',
    longDescription:
      'ACOP L8 compliance, HSG274 guidance, temperature monitoring, sampling regimes, calorifier maintenance, remedial works, and contractor management for water hygiene.',
    icon: 'Droplets',
    displayOrder: 5,
    status: 'active',
    visibility: 'public',
    postingPermissions: 'members',
    discussionCount: 3,
    lastActivityAt: '2026-08-27T14:15:00Z',
  },
  {
    id: 'cat-ppm-asset-mgmt',
    slug: 'ppm-asset-management',
    name: 'PPM & Asset Management',
    shortDescription: 'Maintenance strategy, asset registers, SFG20, lifecycle and asset reliability.',
    longDescription:
      'Planned preventative maintenance schedules, SFG20 alignment, asset condition grading, CIBSE Guide M lifecycle modeling, maintenance regimes, and verification of asset data.',
    icon: 'Layers',
    displayOrder: 6,
    status: 'active',
    visibility: 'public',
    postingPermissions: 'members',
    discussionCount: 5,
    lastActivityAt: '2026-08-27T16:50:00Z',
  },
  {
    id: 'cat-energy-sustainability',
    slug: 'energy-sustainability',
    name: 'Energy & Sustainability',
    shortDescription: 'Energy, carbon, utilities, ESG, sub-metering and environmental performance.',
    longDescription:
      'Decarbonisation strategies, heat pumps, building fabric optimisation, energy tariff management, SECR reporting, ISO 50001, and practical sustainability wins for FM estates.',
    icon: 'Leaf',
    displayOrder: 7,
    status: 'active',
    visibility: 'public',
    postingPermissions: 'members',
    discussionCount: 3,
    lastActivityAt: '2026-08-27T12:30:00Z',
  },
  {
    id: 'cat-cafm-data-tech',
    slug: 'cafm-data-technology',
    name: 'CAFM, Data & Technology',
    shortDescription: 'CAFM, AI, automation, IoT sensors, integrations, reporting and FM software.',
    longDescription:
      'CAFM/IWMS selection and implementation, IoT sensor telemetry, automated job dispatch, data hygiene, API integrations, and extracting genuine operational value from FM technology.',
    icon: 'Cpu',
    displayOrder: 8,
    status: 'active',
    visibility: 'public',
    postingPermissions: 'members',
    discussionCount: 4,
    lastActivityAt: '2026-08-27T15:40:00Z',
  },
  {
    id: 'cat-procurement-contracts',
    slug: 'procurement-contracts',
    name: 'Procurement & Contracts',
    shortDescription: 'Tendering, supplier selection, specifications, contract management and commercial FM.',
    longDescription:
      'Drafting FM specifications, commercial contract models (Total FM vs Bundled vs Single-service), KPI structures, indexation mechanisms, supplier performance disputes, and tender evaluations.',
    icon: 'FileText',
    displayOrder: 9,
    status: 'active',
    visibility: 'public',
    postingPermissions: 'members',
    discussionCount: 3,
    lastActivityAt: '2026-08-27T11:00:00Z',
  },
  {
    id: 'cat-mobilisation',
    slug: 'mobilisation',
    name: 'Mobilisation',
    shortDescription: 'FM mobilisation, TUPE, data handover, transition, asset validation and onboarding.',
    longDescription:
      'Contract mobilisation strategies, 30/60/90-day transition programmes, incoming vs outgoing contractor dynamics, TUPE transfers, inherited defect logs, and initial compliance baseline audits.',
    icon: 'Truck',
    displayOrder: 10,
    status: 'active',
    visibility: 'public',
    postingPermissions: 'members',
    discussionCount: 4,
    lastActivityAt: '2026-08-27T17:05:00Z',
  },
  {
    id: 'cat-workplace-soft-services',
    slug: 'workplace-soft-services',
    name: 'Workplace & Soft Services',
    shortDescription: 'Cleaning, security, front of house, waste, workplace experience and soft FM.',
    longDescription:
      'Workplace experience design, daytime vs evening cleaning models, security licensing, waste management and circular economy, and managing customer-facing FM touchpoints.',
    icon: 'Sparkles',
    displayOrder: 11,
    status: 'active',
    visibility: 'public',
    postingPermissions: 'members',
    discussionCount: 2,
    lastActivityAt: '2026-08-26T18:00:00Z',
  },
  {
    id: 'cat-careers-development',
    slug: 'careers-development',
    name: 'Careers & Professional Development',
    shortDescription: 'Careers, qualifications (IWFM, CIBSE, NEBOSH), CPD, learning and mentoring.',
    longDescription:
      'FM career pathways, transitioning from engineering to management, professional institute qualifications, continuing professional development, team retention, and industry mentoring.',
    icon: 'GraduationCap',
    displayOrder: 12,
    status: 'active',
    visibility: 'public',
    postingPermissions: 'members',
    discussionCount: 3,
    lastActivityAt: '2026-08-27T09:30:00Z',
  },
  {
    id: 'cat-contractor-desk',
    slug: 'contractor-desk',
    name: 'The Contractor Desk',
    shortDescription: 'Discussion relevant to FM contractors, specialist suppliers and service partners.',
    longDescription:
      'Community discussion for specialist FM contractors, supplier-side operational challenges, RAMS best practice, managing call-out evidence expectations, and fostering high-trust client-subcontractor relationships.',
    icon: 'HardHat',
    displayOrder: 13,
    status: 'active',
    visibility: 'public',
    postingPermissions: 'members',
    discussionCount: 4,
    lastActivityAt: '2026-08-27T16:15:00Z',
  },
];

export function getCommunityCategories(): CommunityCategory[] {
  return COMMUNITY_CATEGORIES.sort((a, b) => a.displayOrder - b.displayOrder);
}

export function getCommunityCategoryBySlug(slug: string): CommunityCategory | undefined {
  return COMMUNITY_CATEGORIES.find((c) => c.slug === slug);
}
