import { LEGAL_CONFIG, getLegalDisplayValue, PUBLIC_SUBPROCESSOR_REGISTER, COOKIE_INVENTORY } from '@/config/legal';

import { TocItem } from '@/components/legal/LegalToc';

export interface LegalPolicySection {
  id: string;
  heading: string;
  body: string | React.ReactNode;
  bullets?: string[];
  subsections?: Array<{
    title: string;
    body: string;
    bullets?: string[];
  }>;
  callout?: {
    type: 'info' | 'important' | 'warning' | 'statutory' | 'practical' | 'takeaway';
    title?: string;
    content: string;
  };
}

export interface LegalPolicy {
  slug: string;
  title: string;
  eyebrow: string;
  categorySlug: string;
  categoryTitle: string;
  summary: string;
  metaDescription: string;
  effectiveDate: string;
  version: string;
  keyTakeaways: string[];
  sections: LegalPolicySection[];
  relatedSlugs: string[];
}

/**
 * Registry of all 24 substantive UK-first legal policies
 */
export const LEGAL_POLICIES: Record<string, LegalPolicy> = {
  // ─────────────────────────────────────────────────────────────────────────────
  // 1. TERMS OF USE
  // ─────────────────────────────────────────────────────────────────────────────
  'terms-of-use': {
    slug: 'terms-of-use',
    title: 'Website Terms of Use',
    eyebrow: 'Using EntireFM',
    categorySlug: 'using-entirefm',
    categoryTitle: 'Using EntireFM',
    summary: 'Terms and conditions governing public access to the EntireFM website, interactive FM calculators, guides, and digital planning tools.',
    metaDescription: 'Website Terms of Use governing public access, intellectual property, digital calculators, and content reliance on EntireFM digital platforms.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Applies to all visitors accessing EntireFM public websites and interactive FM tools.',
      'All text, technical schematics, calculators, and branding are protected EntireFM intellectual property.',
      'Online calculators provide indicative estimates only; binding proposals require an asset survey.',
      'Governed by the laws of England and Wales under the exclusive jurisdiction of English courts.',
    ],
    relatedSlugs: ['terms-of-business', 'acceptable-use', 'privacy', 'disclosures'],
    sections: [
      {
        id: 'acceptance-of-terms',
        heading: '1. Acceptance of Terms',
        body: 'By accessing or browsing www.entirefm.com or any associated public digital service provided by Alkota Group Limited trading as EntireFM ("EntireFM", "we", "us", or "our"), you agree to be bound by these Website Terms of Use. If you do not accept these terms, you must discontinue using our website immediately.',
      },
      {
        id: 'intellectual-property',
        heading: '2. Intellectual Property & Permitted Use',
        body: 'All content published on this website—including but not limited to editorial guides, compliance matrices, planned maintenance calculators, technical diagrams, software code, graphic marks, and visual design—is the exclusive intellectual property of Alkota Group Limited or its licensors and is protected by UK and international copyright, trademark, and database laws.',
        bullets: [
          'You may view, download, and print reasonable extracts for your internal business evaluation or educational purposes.',
          'You must not systematically scrape, harvest, reproduce, republish, or commercialise any website material without prior written permission from EntireFM.',
          'EntireFM marks, crystalline branding, and logos may not be used in connection with any third-party product or service without express written authorisation.',
        ],
      },
      {
        id: 'tools-and-calculators',
        heading: '3. FM Tools, Calculators & Indicative Estimates',
        body: 'Our interactive tools (including the FM Building Health Check, PPM Schedule Builder, PPM Estimator, ROI Calculator, and Tender Brief Generator) are engineered to provide indicative guidance based on generalised FM benchmarks and user-supplied inputs.',
        callout: {
          type: 'important',
          title: 'Commercial Reliance Notice',
          content: 'Estimates and matrices generated by online calculators do not constitute formal engineering advice or binding commercial quotations. Every statutory compliance schedule and commercial contract requires an on-site asset condition survey by an authorised EntireFM surveyor.',
        },
      },
      {
        id: 'website-availability',
        heading: '4. Availability & Information Accuracy',
        body: 'While we endeavour to ensure that information published on our website is accurate, current, and aligned with UK statutory standards, we do not warrant that website content is error-free or that access will be continuous or uninterrupted. EntireFM reserves the right to modify, suspend, or withdraw any part of the website without notice.',
      },
      {
        id: 'limitation-of-liability',
        heading: '5. Limitation of Website Liability',
        body: 'To the maximum extent permitted by English law, EntireFM excludes all liability for any direct, indirect, or consequential loss or damage arising out of or in connection with the access, use, or inability to use this public website or reliance on any material contained within it. Nothing in these terms excludes our liability for death or personal injury resulting from negligence, fraud, or any liability that cannot be excluded under applicable UK law.',
      },
      {
        id: 'governing-law',
        heading: '6. Governing Law & Jurisdiction',
        body: 'These Website Terms of Use, their subject matter, and formation are governed by and construed in accordance with the laws of England and Wales. Any dispute arising out of or in connection with these terms shall be subject to the exclusive jurisdiction of the courts of England and Wales.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 2. TERMS OF BUSINESS
  // ─────────────────────────────────────────────────────────────────────────────
  'terms-of-business': {
    slug: 'terms-of-business',
    title: 'Standard Terms of Business',
    eyebrow: 'Clients & Commercial Terms',
    categorySlug: 'clients',
    categoryTitle: 'Clients & Commercial Terms',
    summary: 'Core commercial terms governing facilities management services, planned preventative maintenance (PPM), reactive engineering, statutory compliance, and CAFM technology delivery.',
    metaDescription: 'EntireFM Standard Terms of Business for commercial facilities management, mechanical & electrical engineering, planned maintenance, and compliance delivery.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Sets the overarching contractual framework for Total FM, Hard/Soft services, and CAFM operations.',
      'Specific proposal scopes, asset matrices, rate cards, and SLAs take precedence over standard terms.',
      'Dutyholder client retains statutory responsibility for site health & safety, asbestos registers, and safe access.',
      'Variations and out-of-scope reactive works require formal client authorisation before execution.',
    ],
    relatedSlugs: ['terms-of-use', 'work-order-terms', 'data-processing', 'complaints'],
    sections: [
      {
        id: 'engagement-structure',
        heading: '1. Contract Structure & Order of Precedence',
        body: 'These Standard Terms of Business apply to all facilities management services, planned maintenance (PPM), reactive callouts, statutory compliance testing, and technology platforms provided by Alkota Group Limited trading as EntireFM to commercial clients.',
        bullets: [
          'The Agreement comprises: (1) the signed Commercial Proposal / SLA / Scope of Works, (2) any bespoke Special Conditions, (3) these Standard Terms of Business, and (4) the Data Processing Agreement.',
          'In the event of any conflict, the documents take precedence in the order listed above.',
        ],
      },
      {
        id: 'service-delivery-and-mobilisation',
        heading: '2. Mobilisation & Service Execution',
        body: 'EntireFM shall deliver services with reasonable skill, care, and diligence in accordance with good industry practice, manufacturer recommendations, SFG20 maintenance standards (where specified), and applicable statutory regulations.',
        bullets: [
          'Mobilisation commences upon mutual execution of the contract proposal and receipt of necessary building access permits and asset records.',
          'Asset Survey: Where PPM schedules are agreed, EntireFM may conduct an initial asset verification survey. Any discrepancy in equipment count or condition will be notified with a recommended schedule adjustment.',
        ],
      },
      {
        id: 'client-responsibilities',
        heading: '3. Client Responsibilities & Site Access',
        body: 'The client shall provide EntireFM engineers and authorised contractors with safe, unobstructed access to all relevant building areas, plant rooms, risers, and utility isolation points during agreed working hours.',
        callout: {
          type: 'statutory',
          title: 'Statutory Dutyholder & Asbestos Obligations',
          content: 'The client, as statutory Dutyholder under the Control of Asbestos Regulations 2012 and HASAWA 1974, must make available the site Asbestos Management Plan, Asbestos Register, and relevant hazard disclosures before any invasive maintenance or engineering work commences.',
        },
      },
      {
        id: 'reactive-works-and-variations',
        heading: '4. Reactive Works, Quotations & Variations',
        body: 'Reactive service requests may be lodged via the EntireFM Helpdesk or Client Portal.',
        bullets: [
          'Emergency Make-Safe: Where an immediate threat to life, structural safety, or critical operations is identified, EntireFM is authorised to execute emergency make-safe actions up to the agreed Not-To-Exceed (NTE) limit without prior quotation.',
          'Variations: Any work exceeding agreed contract scopes or routine NTE limits requires written client sign-off or electronic approval via the Client Portal before commencement.',
        ],
      },
      {
        id: 'fees-invoicing-and-payment',
        heading: '5. Fees, Invoicing & Payment Terms',
        body: 'Fees are calculated in accordance with the agreed Commercial Proposal and Rate Card. Invoices are issued electronically with supporting job sheets, compliance certificates, and time-stamped attendance records.',
        bullets: [
          'Payment terms are strictly 30 calendar days from invoice date unless otherwise specified in the Commercial Proposal.',
          'All fees are stated exclusive of VAT, which shall be charged at the prevailing statutory rate.',
          'Late payment interest shall accrue under the Late Payment of Commercial Debts (Interest) Act 1998 at 8% above the Bank of England base rate.',
        ],
      },
      {
        id: 'limitation-of-liability',
        heading: '6. Limitation of Liability & Insurance',
        body: 'EntireFM maintains comprehensive commercial insurances including Employers Liability (£10m), Public/Products Liability (£5m), and Professional Indemnity (£2m).',
        bullets: [
          'Neither party shall be liable for indirect, special, or consequential loss, loss of profit, loss of revenue, or loss of business opportunity.',
          'EntireFM’s total aggregate liability arising under or in connection with the Agreement shall be capped at the total contract charges paid or payable in the preceding 12-month period, or £1,000,000, whichever is lower.',
          'Nothing in this Agreement limits or excludes liability for death or personal injury caused by negligence, fraud, or any liability which cannot be lawfully limited.',
        ],
      },
      {
        id: 'termination',
        heading: '7. Term & Termination',
        body: 'Either party may terminate the Agreement by providing written notice in accordance with the notice period specified in the Commercial Proposal (typically 90 days), or immediately upon written notice if the other party commits a material breach incapable of remedy, or becomes insolvent.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 3. PRIVACY NOTICE
  // ─────────────────────────────────────────────────────────────────────────────
  'privacy': {
    slug: 'privacy',
    title: 'Privacy Notice',
    eyebrow: 'Privacy & Data Protection',
    categorySlug: 'privacy-data',
    categoryTitle: 'Privacy & Data Protection',
    summary: 'Comprehensive UK GDPR, DPA 2018, and PECR privacy notice explaining how EntireFM collects, uses, protects, and respects personal information across all FM services, B2B marketing, and digital platforms.',
    metaDescription: 'EntireFM UK GDPR Privacy Notice: Detailed explanation of data processing, B2B marketing legitimate interests, rights, retention, and security.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'We act as Data Controller for website visitors, prospective B2B clients, portal users, and contractor vetting.',
      'We act as Data Processor under Article 28 when processing occupant data on behalf of FM clients.',
      'B2B marketing outreach is conducted under Legitimate Interests (UK GDPR Art 6(1)(f) / PECR) with an absolute right to object.',
      'We maintain a permanent internal suppression register to respect opt-outs immediately.',
      'We never sell, rent, or trade personal data to third-party marketing brokers.',
    ],
    relatedSlugs: ['data-protection', 'cookies', 'data-processing', 'subprocessors', 'data-protection-complaints'],
    sections: [
      {
        id: 'controller-identity',
        heading: '1. Identity of the Data Controller',
        body: `Alkota Group Limited trading as EntireFM (Company No. ${LEGAL_CONFIG.companyNumber}) is the Data Controller responsible for your personal data when you interact with our public websites, engage in commercial discussions, register for client/contractor portals, or receive B2B communications.`,
        callout: {
          type: 'info',
          title: 'Direct Data Protection Contact',
          content: `Our Data Protection Officer can be reached at ${LEGAL_CONFIG.dataProtectionOfficer.email} or by post at ${LEGAL_CONFIG.dataProtectionOfficer.postalAddress}.`,
        },
      },
      {
        id: 'categories-of-individuals',
        heading: '2. Individuals Whose Data We Process',
        body: 'In our capacity as a national facilities management provider, we process personal information relating to several distinct categories of individuals:',
        bullets: [
          'Website Visitors & Tool Users: Individuals browsing our site or using interactive calculators.',
          'Prospective Clients & Commercial Enquirers: Decision-makers submitting RFPs, quote requests, or survey bookings.',
          'Publicly Sourced Corporate B2B Contacts: Identified corporate facilities managers, estate directors, procurement personnel, and property managers.',
          'Client Personnel & Property Managers: Named operational, financial, and FM contacts under active service contracts.',
          'Building Occupants & Service Requesters: Tenants, employees, or site users logging maintenance helpdesk tickets.',
          'Approved Contractors, Subcontractors & Sole Traders: Vetted engineering partners, technicians, and directors.',
          'Field Engineers & Technicians: Operatives using mobile telemetry and visit logging tools.',
          'Job Applicants: Individuals submitting CVs or employment applications.',
        ],
      },
      {
        id: 'categories-of-data',
        heading: '3. Categories of Personal Data Collected',
        body: 'We collect and process the following categories of information depending on your relationship with EntireFM:',
        bullets: [
          'Identity & Contact Data: Full name, business email, direct phone number, mobile number, job title, and employer organisation.',
          'Property & Operational Data: Site addresses, access notes, keyholder contacts, asset identifiers, and service ticket history.',
          'Contractor Compliance Data: Trade qualifications, Gas Safe/NICEIC/F-Gas registrations, SSIP certifications, insurance certificates, photo ID for site security, and bank details for payment.',
          'Technical & Usage Data: Anonymised IP addresses, browser types, session journey trails (efm_journey_trail), portal login timestamps, and device categories.',
          'Communications Data: Enquiries, helpdesk logs, emails, survey feedback, and call recordings where applicable.',
        ],
      },
      {
        id: 'lawful-bases',
        heading: '4. Lawful Bases for Processing (UK GDPR Art 6)',
        body: 'We do not rely on "consent" as a blanket ground. We identify and document the specific lawful basis for each distinct processing activity:',
        bullets: [
          'Performance of a Contract (Art 6(1)(b)): Processing necessary to deliver FM services, dispatch engineers, execute work orders, process invoices, and manage client/contractor accounts.',
          'Compliance with Legal Obligations (Art 6(1)(c)): Retaining VAT/tax records (Companies Act/HMRC), statutory compliance certificates, health & safety logs (HASAWA/CDM 2015), and RIDDOR incident reports.',
          'Legitimate Interests (Art 6(1)(f)): B2B marketing to relevant corporate decision-makers, portal security monitoring, fraud prevention, service quality analytics, and commercial debt recovery.',
          'Consent (Art 6(1)(a)): Where explicitly required, such as non-essential analytics cookies or newsletter opt-in subscriptions for non-corporate contacts.',
        ],
      },
      {
        id: 'b2b-marketing-and-prospecting',
        heading: '5. B2B Marketing, Prospect Research & Right to Object',
        body: 'EntireFM legitimately identifies and contacts relevant corporate business contacts (e.g. Facilities Managers, Property Managers, Estates Directors, Operations Managers, and Procurement Teams) who have a professional interest in commercial building maintenance.',
        callout: {
          type: 'important',
          title: 'Legitimate Interests Assessment & Absolute Right to Object',
          content: 'Under UK GDPR Art 6(1)(f) and PECR, we process corporate business contact details based on our legitimate commercial interest. We rigorously minimise data, verify business relevance, and provide an immediate, unconditional right to opt out in every communication.',
        },
        bullets: [
          'Origin of Business Contacts: Sourced from public business registries (Companies House), professional networking platforms (LinkedIn), corporate websites, industry directories, or commercial data providers vetted for UK GDPR compliance.',
          'Reasonable Expectations: Communications are strictly business-to-business (B2B), addressed to corporate subscribers in their professional capacity, and directly relevant to their property portfolio.',
          'Suppression Register: When you object to marketing, your email is immediately added to our global suppression register to ensure no further outreach is generated.',
          'How to Opt Out: Click the "Unsubscribe" link in any outreach email, reply with "STOP/OPT-OUT", or email privacy@entirefm.com.',
        ],
      },
      {
        id: 'recipients-and-subprocessors',
        heading: '6. Data Recipients & Authorized Subprocessors',
        body: 'We do not sell, rent, or trade your personal data. We share information only with authorised recipients under strict contractual terms:',
        bullets: [
          'Authorised Contractors & Engineers: Shared strictly on a need-to-know basis (site address, contact name, phone number) to attend and resolve work orders.',
          'Cloud & Technology Providers: Vetted subprocessors providing edge hosting (Vercel), secure database storage (Supabase/AWS UK), transactional communications (Resend), and analytics.',
          'Statutory Bodies & Law Enforcement: When required by law, such as HMRC audits, HSE health & safety investigations, or court orders.',
        ],
      },
      {
        id: 'international-transfers',
        heading: '7. International Data Transfers',
        body: 'Our primary databases and CAFM systems are hosted within the United Kingdom (AWS London eu-west-2). Where cloud services process data outside the UK (e.g. European Union or United States), transfers are secured using UK Adequacy Regulations, the UK International Data Transfer Agreement (IDTA), or the UK Addendum to EU Standard Contractual Clauses.',
      },
      {
        id: 'data-retention',
        heading: '8. Data Retention Periods',
        body: 'We retain personal data only for as long as necessary to fulfil the purposes for which it was collected, including statutory legal, accounting, and health & safety requirements:',
        bullets: [
          'Client & Contractor Contract Records: 6 years following contract termination (Limitation Act 1980).',
          'Financial & Tax Invoices: 6 years plus current financial year (Companies Act / HMRC).',
          'Statutory Compliance & Asset Records (EICR, Gas, Legionella): Retained for the lifetime of the asset or 7 years.',
          'B2B Marketing Prospects: Retained for up to 24 months from last interaction, or until an opt-out request is lodged (suppression record retained indefinitely).',
          'Helpdesk Tickets & Occupant Requests: 3 years following ticket resolution.',
        ],
      },
      {
        id: 'data-subject-rights',
        heading: '9. Your Statutory Data Subject Rights',
        body: 'Under UK GDPR and the Data Protection Act 2018, you possess comprehensive statutory rights regarding your personal information:',
        bullets: [
          'Right of Access (Subject Access Request - SAR): Obtain confirmation and a free copy of your personal data.',
          'Right to Rectification: Correct inaccurate or incomplete personal records.',
          'Right to Erasure ("Right to be Forgotten"): Request deletion where data is no longer necessary or processed unlawfully.',
          'Right to Restriction of Processing: Temporarily restrict processing during dispute or verification.',
          'Right to Data Portability: Receive your electronic data in a structured, machine-readable format.',
          'Right to Object: An absolute right to stop direct marketing at any time, and a right to object to processing based on legitimate interests.',
          'Rights Related to Automated Decision-Making & AI: Request human intervention and challenge automated recommendations.',
        ],
      },
      {
        id: 'supervisory-complaint',
        heading: '10. Right to Complain & Supervisory Authority Escalation',
        body: `If you have concerns about how we handle your personal data, please submit an electronic complaint via our Data Protection Complaints Procedure or email ${LEGAL_CONFIG.dataProtectionOfficer.email}. You also have the statutory right to lodge a complaint with the UK Information Commissioner’s Office (ICO) at ico.org.uk or by calling 0303 123 1113.`,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 4. COOKIES POLICY
  // ─────────────────────────────────────────────────────────────────────────────
  'cookies': {
    slug: 'cookies',
    title: 'Cookies & Storage Policy',
    eyebrow: 'Privacy & Data Protection',
    categorySlug: 'privacy-data',
    categoryTitle: 'Privacy & Data Protection',
    summary: 'Clear breakdown of cookie, session storage, and local storage technologies used on the EntireFM website in compliance with PECR and UK GDPR.',
    metaDescription: 'EntireFM Cookies Policy: Live cookie inventory, essential storage, analytics consent, and preference management under PECR and DUA Act 2025.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Strictly necessary cookies are used exclusively for user authentication and session security.',
      'Analytics and marketing cookies are blocked by default until you grant explicit consent.',
      'We do not use third-party behavioral advertising networks or tracking pixels.',
      'You can update or revoke your cookie preferences at any time via the footer preference manager.',
    ],
    relatedSlugs: ['privacy', 'data-protection', 'security'],
    sections: [
      {
        id: 'what-are-cookies',
        heading: '1. What Are Cookies and Storage Technologies?',
        body: 'Cookies are small text files placed on your device by websites you visit. Similar technologies include Session Storage and Local Storage, which allow web applications to remember session states, user preferences, and secure authentication tokens.',
      },
      {
        id: 'statutory-framework',
        heading: '2. UK Statutory Framework (PECR & DUA Act 2025)',
        body: 'The use of cookies in the United Kingdom is governed by the Privacy and Electronic Communications Regulations 2003 (PECR), the UK GDPR, and reforms under the Data (Use and Access) Act 2025.',
        callout: {
          type: 'statutory',
          title: 'Conservative Privacy-First Standard',
          content: 'While recent UK legislation introduces flexibility for certain low-risk statistical storage, EntireFM adheres to a strict privacy-first model: non-essential analytics and tracking technologies are never executed prior to affirmative user consent.',
        },
      },
      {
        id: 'categories-of-cookies',
        heading: '3. Categories of Technologies We Use',
        body: 'We categorise our storage technologies into four clear tiers:',
        bullets: [
          'Strictly Necessary (Always Active): Essential for security, user login authentication (efm_session), CSRF protection, and recording your cookie consent preferences. Exempt from consent under PECR Reg 6(4).',
          'Functional & Journey Memory: In-session storage (efm_journey_trail) maintaining anonymous page views (capped at 15 URLs) to attach context to maintenance enquiry forms. Cleared automatically upon browser closure.',
          'Performance & Analytics (Consent-Gated): Google Analytics 4 configured in Zero-PII mode to monitor aggregated site traffic and popular FM tools without capturing personal identifiable data.',
          'Direct Marketing (Consent-Gated): Used exclusively for opted-in newsletter tracking. We do not participate in third-party ad retargeting networks.',
        ],
      },
      {
        id: 'live-inventory',
        heading: '4. Live Cookie & Storage Inventory',
        body: 'Below is the complete, audited register of storage technologies deployed across this platform:',
        bullets: COOKIE_INVENTORY.map(
          (c) => `${c.name} (${c.type}): ${c.purpose} [Duration: ${c.duration} | Basis: ${c.statutoryBasis}]`
        ),
      },
      {
        id: 'managing-preferences',
        heading: '5. How to Manage and Revoke Consent',
        body: 'You have complete control over non-essential cookies. You can modify your preferences at any time by clicking "Manage Cookie Preferences" in our website footer, or by clearing cookies directly within your web browser settings.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 5. DATA PROTECTION POLICY
  // ─────────────────────────────────────────────────────────────────────────────
  'data-protection': {
    slug: 'data-protection',
    title: 'Data Protection & Governance Framework',
    eyebrow: 'Privacy & Data Protection',
    categorySlug: 'privacy-data',
    categoryTitle: 'Privacy & Data Protection',
    summary: 'Internal governance standards, accountability measures, data classification, breach management protocols, and technical controls enforced across EntireFM operations.',
    metaDescription: 'EntireFM Corporate Data Protection Framework: UK GDPR accountability, privacy by design, data classification, and breach response.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Accountability framework embedding Privacy by Design into all CAFM software and field workflows.',
      'Four-tier data classification: Public, Internal, Confidential, and Restricted.',
      'Mandatory 72-hour ICO data breach notification and 48-hour client processor notification procedures.',
      'Compulsory annual data protection training for all operations staff, dispatchers, and engineers.',
    ],
    relatedSlugs: ['privacy', 'data-protection-complaints', 'data-processing', 'security', 'ai'],
    sections: [
      {
        id: 'accountability-principles',
        heading: '1. Organizational Accountability & Principles',
        body: 'EntireFM maintains strict adherence to the core data protection principles set out in Article 5 of the UK GDPR: Lawfulness, Fairness, and Transparency; Purpose Limitation; Data Minimisation; Accuracy; Storage Limitation; and Integrity and Confidentiality (Security).',
      },
      {
        id: 'privacy-by-design',
        heading: '2. Privacy by Design & Default',
        body: 'All CAFM platform features, automated dispatch algorithms, mobile engineering applications, and client reporting tools are architected under strict Privacy by Design principles. Data Protection Impact Assessments (DPIAs) are conducted prior to deploying new technologies, automated processing, or AI models.',
      },
      {
        id: 'data-classification',
        heading: '3. Data Classification Standard',
        body: 'EntireFM classifies all corporate, operational, and customer information into four structured tiers:',
        bullets: [
          'PUBLIC: Information approved for public dissemination (marketing guides, public legal policies).',
          'INTERNAL: General business communications, standard operational procedures, and anonymised analytics.',
          'CONFIDENTIAL: Commercial contracts, client asset registers, rate cards, and financial invoice details.',
          'RESTRICTED: Highly sensitive personal data, portal authentication credentials, contractor criminal record checks (where required for sensitive sites), and bank details.',
        ],
      },
      {
        id: 'incident-and-breach-management',
        heading: '4. Security Incident & Personal Data Breach Response',
        body: 'EntireFM maintains a formal Incident Response Protocol to identify, contain, assess, and remediate suspected personal data breaches.',
        callout: {
          type: 'statutory',
          title: 'Statutory Breach Reporting Windows',
          content: 'Where a breach creates a risk to individuals, EntireFM shall notify the ICO without undue delay and within 72 hours. Where EntireFM acts as a Data Processor for a client, we shall notify the client Data Controller within 48 hours of becoming aware.',
        },
      },
      {
        id: 'vendor-and-processor-oversight',
        heading: '5. Supply Chain & Vendor Governance',
        body: 'All third-party cloud providers, IT subcontractors, and specialist service vendors undergo rigorous data protection due diligence and are bound by written Data Processing Agreements compliant with UK GDPR Article 28.',
      },
      {
        id: 'staff-training-and-auditing',
        heading: '6. Training, Auditing & Governance Oversight',
        body: 'All EntireFM employees, helpdesk operators, commercial estimators, and management personnel undergo mandatory data protection training upon onboarding and annually thereafter. Internal audits of access logs and data retention are conducted semi-annually.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 6. DATA PROTECTION COMPLAINTS
  // ─────────────────────────────────────────────────────────────────────────────
  'data-protection-complaints': {
    slug: 'data-protection-complaints',
    title: 'Data Protection Complaints Procedure',
    eyebrow: 'Privacy & Data Protection',
    categorySlug: 'privacy-data',
    categoryTitle: 'Privacy & Data Protection',
    summary: 'Formal electronic complaints mechanism and statutory procedure for raising data privacy, marketing opt-out, or Subject Access Request concerns.',
    metaDescription: 'EntireFM Data Protection Complaints Procedure: Electronic complaint submission, tracking reference, and statutory investigation lifecycle.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Dedicated electronic submission form generating an official reference (DPC-YYYY-XXXXX).',
      'Prompt written acknowledgement and investigation conducted without undue delay.',
      'Transparent 6-stage investigation lifecycle: Received, Acknowledged, Investigating, Awaiting Info, Decision Issued, Closed.',
      'Clear escalation route to the UK Information Commissioner’s Office (ICO).',
    ],
    relatedSlugs: ['privacy', 'data-protection', 'complaints', 'ai'],
    sections: [
      {
        id: 'complaints-commitment',
        heading: '1. Our Commitment to Data Privacy Concerns',
        body: 'EntireFM takes all data protection concerns, marketing objections, and rights disputes with utmost seriousness. We maintain a transparent, accessible, and auditable electronic complaints workflow to investigate and resolve issues swiftly without undue delay.',
      },
      {
        id: 'investigation-lifecycle',
        heading: '2. Investigation Lifecycle & Timelines',
        body: 'Every complaint registered through our electronic form or received at privacy@entirefm.com progresses through a structured governance lifecycle:',
        bullets: [
          '1. RECEIVED: Complaint logged and assigned a unique tracking reference code.',
          '2. ACKNOWLEDGED: Written acknowledgement issued to your registered email promptly upon intake.',
          '3. INVESTIGATING: The Data Protection Officer reviews relevant audit logs, suppression registers, or processing records.',
          '4. AWAITING INFORMATION: If clarification is needed, we will contact you without delay.',
          '5. DECISION ISSUED: A formal written outcome detailing findings and remedial actions is communicated without unjustifiable or excessive delay.',
          '6. CLOSED: Remedial actions verified and complaint archived in the confidential audit ledger.',
        ],
      },
      {
        id: 'marketing-opt-out-fast-track',
        heading: '3. Fast-Track Direct Marketing Opt-Outs',
        body: 'Complaints relating to B2B direct marketing outreach or suppression failures are immediately prioritised. Your email address and organisation domain are entered into our global suppression database within 24 hours to prevent any further outreach while the investigation proceeds.',
      },
      {
        id: 'supervisory-escalation',
        heading: '4. Escalation to the Information Commissioner (ICO)',
        body: 'If you are dissatisfied with our response or believe our processing infringes data protection law, you have the statutory right to lodge a complaint with the UK Information Commissioner’s Office (ICO) at https://ico.org.uk or helpline 0303 123 1113.',
      },
    ],

  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 7. RESPONSIBLE AI & TECHNOLOGY TRANSPARENCY
  // ─────────────────────────────────────────────────────────────────────────────
  'ai': {
    slug: 'ai',
    title: 'Responsible AI & Technology Governance',
    eyebrow: 'Artificial Intelligence & Technology',
    categorySlug: 'ai-technology',
    categoryTitle: 'Artificial Intelligence & Technology',
    summary: 'Authoritative transparency statement governing AI-assisted CAFM workflows, predictive maintenance models, human-in-the-loop safeguards, and automated processing rights.',
    metaDescription: 'EntireFM Responsible AI Policy: Human-in-the-loop governance, transparency, model boundaries, and automated processing rights under UK GDPR.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'AI is used strictly as an analytical tool to support human decision-makers, not replace human accountability.',
      'We do not claim our AI is infallible, autonomous, or human-like.',
      'All commercial quotes, contractor allocations, and critical safety actions require authorised human approval.',
      'Individuals possess the right to obtain meaningful human review and contest any AI recommendation.',
    ],
    relatedSlugs: ['privacy', 'data-protection', 'disclosures', 'acceptable-use'],
    sections: [
      {
        id: 'ai-principles',
        heading: '1. Our Responsible AI Philosophy',
        body: 'EntireFM leverages artificial intelligence and machine learning to optimize facilities management logistics, synthesize building telemetry, and assist our technical team. We operate under clear principles: AI must be transparent, secure, bounded by safety limits, and subject to human oversight.',
      },
      {
        id: 'where-ai-is-used',
        heading: '2. Where AI Is Deployed in EntireFM Operations',
        body: 'We deploy AI assistance across specific, bounded facilities management workflows:',
        bullets: [
          'Service Request Triage: Categorising incoming maintenance requests by trade (HVAC, Electrical, Plumbing) and extracting asset codes.',
          'Priority Recommendation: Suggesting urgency tiers (P1-P4) based on safety keywords and client SLA terms for dispatcher confirmation.',
          'PPM Matrix Drafting: Synthesising asset lists and SFG20 guidelines to draft recommended planned maintenance schedules.',
          'Contractor Allocation Suggestion: Evaluating geographic proximity, trade competencies, and active SSIP accreditations to recommend vetted contractors.',
          'Document Data Extraction: Parsing technical certificates, EICRs, and service sheets to extract expiry dates and remedial actions for compliance lead verification.',
          'Predictive Telemetry Monitoring: Flagging anomalies in sensor and energy data indicating potential equipment deterioration.',
        ],
      },
      {
        id: 'what-ai-does-not-decide',
        heading: '3. What AI Does NOT Decide (Non-Delegable Human Boundaries)',
        body: 'To protect our clients, contractors, and building occupants, the following actions are strictly prohibited from sole automated execution:',
        bullets: [
          'No Automated Contract Cancellation or Penalties: AI cannot terminate contracts or assess financial damages.',
          'No Unsupervised Safety Risk Acceptance: AI cannot override safety exceptions, asbestos warnings, or statutory inspection deficits.',
          'No Sole Automated Contractor Suspension: Contractor onboarding and disciplinary actions require human compliance review.',
          'No Binding Quotations: Commercial proposals are formally reviewed and issued exclusively by authorised human surveyors.',
        ],
      },
      {
        id: 'human-in-the-loop',
        heading: '4. Human-in-the-Loop & Co-Responsibility Architecture',
        body: 'Every AI agent in our platform operates under strict autonomy policies (OFF, MANUAL, ASSIST, or CONTROLLED_AUTO). Confidence thresholds and spend guardrails automatically trigger escalation to human supervisors whenever ambiguity arises.',
      },
      {
        id: 'bias-and-accuracy',
        heading: '5. Accuracy, Fairness & Bias Controls',
        body: 'AI outputs are probabilistic recommendations. We mitigate algorithmic bias by evaluating models against objective technical standards (qualifications, geographic radius, verified certifications) rather than subjective profiling.',
      },
      {
        id: 'user-rights-and-challenge',
        heading: '6. Your Right to Challenge AI Outcomes & Request Human Review',
        body: 'Under UK GDPR Article 22 and the Data (Use and Access) Act 2025, if an AI recommendation affects your service request, quote, or contractor allocation, you have the right to request an explanation, express your point of view, and demand a full manual review by an EntireFM manager.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 8. ACCEPTABLE USE POLICY
  // ─────────────────────────────────────────────────────────────────────────────
  'acceptable-use': {
    slug: 'acceptable-use',
    title: 'Acceptable Use Policy',
    eyebrow: 'Using EntireFM',
    categorySlug: 'using-entirefm',
    categoryTitle: 'Using EntireFM',
    summary: 'Security rules, credential standards, and behavioral requirements for clients, contractors, and engineers accessing the EntireFM CAFM portals and APIs.',
    metaDescription: 'EntireFM Acceptable Use Policy governing client portals, contractor platforms, mobile apps, and developer APIs.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Prohibits credential sharing, unauthorized multi-tenant access, and automated scraping.',
      'Strictly prohibits submitting falsified maintenance records, forged certificates, or fraudulent invoices.',
      'Prohibits prompt injection, model jailbreaking, or attempting to extract proprietary CAFM system prompts.',
      'Immediate suspension and potential statutory reporting for severe security breaches.',
    ],
    relatedSlugs: ['terms-of-use', 'security', 'contractor-terms', 'ai'],
    sections: [
      {
        id: 'scope-and-application',
        heading: '1. Scope & Application',
        body: 'This Acceptable Use Policy applies to all registered users of EntireFM digital platforms, including the Client Portal (/clients), Contractor Portal (/contractor), Field Engineer App (/engineer), Admin Command (/admin), and associated APIs.',
      },
      {
        id: 'prohibited-activities',
        heading: '2. Prohibited Activities & Platform Abuse',
        body: 'You must not use EntireFM digital platforms to conduct, facilitate, or attempt any of the following:',
        bullets: [
          'Credential Sharing: Permitting multiple individuals to share a single user account or authenticating with another user’s credentials.',
          'Unauthorised Access: Attempting to bypass tenant isolation boundaries, view other client accounts, or access administrative endpoints.',
          'Falsification of Operational Records: Uploading fraudulent service sheets, staging false photos, manipulating compliance certificates, or falsifying GPS on-site timestamps.',
          'Malicious Injections & AI Manipulation: Submitting malicious prompts, prompt injections, or jailbreak instructions aimed at subverting AI guardrails or extracting underlying prompts.',
          'Automated Scraping & Denial of Service: Executing automated web crawlers, stress tests, or scrapers without prior written API authorization.',
          'Harassment & Defamation: Using portal messaging channels to send abusive, threatening, discriminatory, or unlawful material.',
        ],
      },
      {
        id: 'security-and-credentials',
        heading: '3. User Credential Security',
        body: 'Users are responsible for maintaining the confidentiality of their login credentials. Passwords must meet enterprise complexity standards. You must notify EntireFM immediately at security@entirefm.com if you suspect unauthorized access.',
      },
      {
        id: 'monitoring-and-enforcement',
        heading: '4. Monitoring, Audit & Sanctions',
        body: 'EntireFM continuously monitors API telemetry, login anomalies, and user actions for security and compliance. Any violation of this policy may result in immediate account suspension, contract termination for cause, civil recovery proceedings, and referral to law enforcement where criminal activity is suspected.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 9. DATA PROCESSING AGREEMENT (ARTICLE 28 DPA)
  // ─────────────────────────────────────────────────────────────────────────────
  'data-processing': {
    slug: 'data-processing',
    title: 'Data Processing Agreement (UK GDPR Art 28)',
    eyebrow: 'Privacy & Data Protection',
    categorySlug: 'privacy-data',
    categoryTitle: 'Privacy & Data Protection',
    summary: 'Statutory Data Processing Agreement (DPA) incorporating UK GDPR Article 28 terms where EntireFM processes building occupant and client personal data on behalf of commercial property clients.',
    metaDescription: 'EntireFM Data Processing Agreement (Article 28 UK GDPR): Processing instructions, security, subprocessors, breach notification, and audit rights.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Compliant with UK GDPR Article 28 and Data Protection Act 2018 requirements.',
      'EntireFM processes client personal data exclusively on documented instructions.',
      '48-hour personal data breach notification window to client Data Controllers.',
      'Configurable Schedule of Processing tailored to each property management contract.',
    ],
    relatedSlugs: ['privacy', 'data-protection', 'subprocessors', 'terms-of-business'],
    sections: [
      {
        id: 'dpa-framework',
        heading: '1. Scope & Relationship of the Parties',
        body: 'Where EntireFM delivers facilities management, helpdesk triage, keyholding, or CAFM software services to a Client, the Client acts as Data Controller and EntireFM acts as Data Processor in respect of personal data processed in connection with the Agreement.',
      },
      {
        id: 'processor-obligations',
        heading: '2. Processor Obligations (UK GDPR Article 28(3))',
        body: 'EntireFM agrees to:',
        bullets: [
          'Documented Instructions: Process personal data only on documented instructions from the Client, including regarding international transfers.',
          'Staff Confidentiality: Ensure that all personnel authorised to process personal data have committed themselves to confidentiality or are under an appropriate statutory obligation of confidentiality.',
          'Security Measures (Art 32): Implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk.',
          'Subprocessors: Not engage any subprocessor without prior specific or general written authorisation from the Client and maintaining a transparent Subprocessor Register.',
          'Data Subject Rights Assistance: Assist the Client by appropriate technical and organisational measures in fulfilling the Client’s obligation to respond to Subject Access Requests.',
          'Breach Notification: Notify the Client without undue delay and within 48 hours of becoming aware of a personal data breach.',
          'Deletion or Return: At the choice of the Client, delete or return all personal data to the Client after the end of the provision of services.',
          'Audits & Inspections: Make available to the Client all information necessary to demonstrate compliance and allow for and contribute to audits conducted by the Client or an appointed auditor.',
        ],
      },
      {
        id: 'schedule-of-processing',
        heading: '3. Configurable Schedule of Processing (FM Operations)',
        body: 'Subject Matter: Delivery of commercial facilities management, reactive engineering, statutory compliance testing, and tenant helpdesk services. Duration: For the duration of the Principal Agreement. Nature & Purpose: Scheduling work orders, attending site, logging compliance certificates, communicating with building occupants. Categories of Data: Contact details, site addresses, access logs, service request descriptions. Categories of Data Subjects: Client personnel, tenants, building occupants, visitor keyholders.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 10. SUBPROCESSORS REGISTER
  // ─────────────────────────────────────────────────────────────────────────────
  'subprocessors': {
    slug: 'subprocessors',
    title: 'Authorized Subprocessors Register',
    eyebrow: 'Privacy & Data Protection',
    categorySlug: 'privacy-data',
    categoryTitle: 'Privacy & Data Protection',
    summary: 'Transparent public register of third-party cloud infrastructure, database, communication, and analytics providers authorised to process data across EntireFM systems.',
    metaDescription: 'EntireFM Subprocessors Register: Audited list of cloud hosting, database, email, and analytics subprocessors with UK transfer mechanisms.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Complete transparency on cloud hosting, database, email, and analytics vendors.',
      'All subprocessors bound by UK GDPR Art 28 Data Processing Agreements.',
      'Primary database hosted in London (AWS eu-west-2); edge delivery secured via SCCs.',
      '30-day prior notification provided to clients for new subprocessor appointments.',
    ],
    relatedSlugs: ['privacy', 'data-processing', 'security', 'data-protection'],
    sections: [
      {
        id: 'subprocessor-policy',
        heading: '1. Subprocessor Engagement Policy',
        body: 'EntireFM enforces rigorous vendor due diligence before engaging any third-party technology provider. Subprocessors must demonstrate robust technical security controls, UK GDPR compliance, and undergo regular security reviews.',
      },
      {
        id: 'active-subprocessors',
        heading: '2. Live Audited Subprocessor Register',
        body: 'The following organisations are currently authorised to process data on behalf of EntireFM:',
        bullets: PUBLIC_SUBPROCESSOR_REGISTER.map(
          (s) => `${s.name} (${s.category}): ${s.purpose} [Primary Hosting: ${s.primaryHostingRegion} | Safeguard: ${s.transferSafeguard}]`
        ),

      },
      {
        id: 'change-notification',
        heading: '3. Notification of Subprocessor Changes',
        body: 'EntireFM shall provide contracted clients with at least 30 days’ advance written notice before onboarding any new subprocessor. Clients have the right to object on legitimate data protection grounds.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 11. CONTRACTOR NETWORK TERMS
  // ─────────────────────────────────────────────────────────────────────────────
  'contractor-terms': {
    slug: 'contractor-terms',
    title: 'Contractor Network Framework Agreement',
    eyebrow: 'Contractors & Supply Chain',
    categorySlug: 'contractors-suppliers',
    categoryTitle: 'Contractors & Supply Chain',
    summary: 'Legal, operational, and commercial terms governing independent trade contractors, specialist engineering firms, and approved supply chain partners within the EntireFM network.',
    metaDescription: 'EntireFM Contractor Network Framework Agreement: Onboarding, vetting, work allocation, payment terms, insurance, and statutory compliance.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Establishes independent commercial relationship; strictly no employment or agency status.',
      'Mandatory verified trade accreditations (Gas Safe, NICEIC, F-Gas) and active SSIP certification.',
      'Electronic job sign-off and photographic completion evidence required for invoice approval.',
      'Strict non-solicitation covenants protecting client relationships.',
    ],
    relatedSlugs: ['work-order-terms', 'contractor-code', 'health-safety', 'supplier-code'],
    sections: [
      {
        id: 'onboarding-and-verification',
        heading: '1. Network Eligibility, Application & Approval',
        body: 'Admission to the EntireFM Contractor Network is subject to formal verification of company registration, trade accreditations, insurance cover, and health & safety compliance. EntireFM reserves the right to reject or terminate any contractor application without guarantee of work allocation.',
      },
      {
        id: 'contractor-status',
        heading: '2. Independent Contractor Status (No Employment)',
        body: 'The relationship between EntireFM and the Contractor is strictly that of independent commercial trading entities. Nothing in this Agreement shall constitute an employment relationship, agency, partnership, or joint venture. The Contractor remains responsible for all tax, national insurance, and statutory employment liabilities of its own personnel.',
      },
      {
        id: 'competence-and-insurance',
        heading: '3. Competence, Accreditations & Mandatory Insurance',
        body: 'The Contractor warrants that all operatives deployed on EntireFM work orders are fully competent, appropriately qualified, and hold active trade certifications (e.g. Gas Safe for gas works, NICEIC/ECA for electrical, F-Gas for refrigeration, PASMA/IPAF for height access).',
        bullets: [
          'The Contractor must maintain active Employers Liability (£10m) and Public Liability (£5m minimum, or as agreed in rate card).',
          'Expired certifications immediately trigger automatic suspension from automated work order allocation.',
        ],
      },
      {
        id: 'work-execution-and-evidence',
        heading: '4. Work Order Execution, Evidence & Completion',
        body: 'Contractors must execute works in strict accordance with the Instructed Scope and agreed SLA response times.',
        bullets: [
          'Mandatory Attendance Evidence: Time-stamped GPS arrival logs, clear "before and after" photographs, and client-signed service sheets must be uploaded within 24 hours of job completion.',
          'Statutory Certificates: Completed EICRs, CP12/commercial gas certificates, or commissioning sheets must be provided before invoice approval.',
        ],
      },
      {
        id: 'variations-and-invoicing',
        heading: '5. Variations, Rates & Payment Terms',
        body: 'Contractors must not exceed agreed Not-To-Exceed (NTE) budget caps without prior written authorisation from the EntireFM Helpdesk, except where immediate action is required to make a dangerous asset safe.',
        bullets: [
          'Invoices must quote the valid EntireFM Work Order ID and match agreed rate cards.',
          'Disputed invoices are notified within 14 days; undisputed balances are settled in accordance with agreed commercial payment terms.',
        ],
      },
      {
        id: 'non-solicitation',
        heading: '6. Non-Solicitation & Confidentiality',
        body: 'The Contractor covenants that during the term and for 12 months following termination, it shall not directly or indirectly solicit, accept, or undertake facilities management or maintenance works from any EntireFM client introduced through the Network without express written agreement.',
      },
      {
        id: 'suspension-and-termination',
        heading: '7. Performance Monitoring & Termination',
        body: 'EntireFM monitors contractor performance via client ratings, SLA compliance, and audit pass rates. EntireFM may suspend or terminate network membership immediately for serious safety breaches, falsified records, loss of accreditation, or persistent poor performance.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 12. WORK ORDER TERMS
  // ─────────────────────────────────────────────────────────────────────────────
  'work-order-terms': {
    slug: 'work-order-terms',
    title: 'Work Order Execution Terms',
    eyebrow: 'Contractors & Supply Chain',
    categorySlug: 'contractors-suppliers',
    categoryTitle: 'Contractors & Supply Chain',
    summary: 'Binding conditions incorporated into each individual work order dispatched to trade contractors and mobile engineers.',
    metaDescription: 'EntireFM Work Order Execution Terms: Electronic acceptance, budget caps, asbestos protocols, and evidence requirements.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Incorporated by reference into every electronic work order instruction.',
      'Contractor must review site Asbestos Register before intrusive works.',
      'Strict Not-To-Exceed (NTE) budget limits; variations require prior approval.',
      'Electronic acceptance creates an auditable timestamped record.',
    ],
    relatedSlugs: ['contractor-terms', 'contractor-code', 'health-safety'],
    sections: [
      {
        id: 'incorporation-and-acceptance',
        heading: '1. Incorporation & Electronic Acceptance',
        body: 'These Work Order Execution Terms are incorporated into every individual work order instruction issued by EntireFM. By electronically accepting the dispatch or attending the site, the Contractor accepts these terms.',
      },
      {
        id: 'site-hazard-disclosure',
        heading: '2. Site Hazards & Asbestos Register Compliance',
        body: 'The Contractor’s attending operatives must report to site security/reception, review the site Asbestos Register and hazard warnings, and ensure appropriate Risk Assessment & Method Statements (RAMS) and permits-to-work are in place before starting work.',
      },
      {
        id: 'budget-caps-and-variations',
        heading: '3. Chargeable Scope & Not-To-Exceed Budget Caps',
        body: 'The Contractor is authorised to invoice only up to the specified NTE limit. If additional parts or labour are required, the operative must contact the EntireFM Helpdesk for written variation approval before proceeding.',
      },
      {
        id: 'defects-and-callbacks',
        heading: '4. 12-Month Workmanship Warranty & Callbacks',
        body: 'The Contractor warrants all workmanship for 12 months from completion. Any defect arising from faulty materials or poor workmanship shall be rectified by the Contractor at zero additional cost within the agreed callback SLA.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 13. CONTRACTOR CODE OF CONDUCT
  // ─────────────────────────────────────────────────────────────────────────────
  'contractor-code': {
    slug: 'contractor-code',
    title: 'Contractor Code of Conduct',
    eyebrow: 'Contractors & Supply Chain',
    categorySlug: 'contractors-suppliers',
    categoryTitle: 'Contractors & Supply Chain',
    summary: 'Professional conduct, site etiquette, customer care, safeguarding, and safety standards required of all contractor personnel attending client estates.',
    metaDescription: 'EntireFM Contractor Code of Conduct: Standards of behavior, appearance, safeguarding, and safety on client sites.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Smart appearance, high-visibility PPE, and photo ID badges required at all times.',
      'Zero tolerance for drugs, alcohol, smoking/vaping in non-designated areas.',
      'Strict safeguarding and confidentiality standards on education and healthcare sites.',
      'Prohibits posting site photos or client names on social media.',
    ],
    relatedSlugs: ['contractor-terms', 'supplier-code', 'anti-bribery', 'health-safety'],
    sections: [
      {
        id: 'professionalism-and-appearance',
        heading: '1. Professionalism, Identification & Appearance',
        body: 'Contractor operatives represent EntireFM and our clients. Operatives must be polite, wear clean company-branded workwear, maintain appropriate PPE, and visibly display photo ID badges at all times on site.',
      },
      {
        id: 'site-rules-and-safety',
        heading: '2. Safe Behavior & Zero Tolerance Substances',
        body: 'Operatives must adhere strictly to site safety rules, fire evacuation routes, and speed limits. Smoking and vaping are permitted only in designated external zones. There is zero tolerance for alcohol or illegal drugs.',
      },
      {
        id: 'safeguarding-and-respect',
        heading: '3. Safeguarding & Sensitive Environments',
        body: 'On education, healthcare, or residential sites, operatives must avoid unsupervised contact with children or vulnerable adults, use designated contractor facilities, and adhere to enhanced DBS checks where specified.',
      },
      {
        id: 'confidentiality-and-social-media',
        heading: '4. Confidentiality & Photography Rules',
        body: 'Photographs must be taken strictly for technical job evidence. Operatives must never photograph client staff, confidential documents, or post site photos or client names on social media platforms.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 14. SUPPLIER CODE OF CONDUCT
  // ─────────────────────────────────────────────────────────────────────────────
  'supplier-code': {
    slug: 'supplier-code',
    title: 'Supplier Code of Conduct',
    eyebrow: 'Contractors & Supply Chain',
    categorySlug: 'contractors-suppliers',
    categoryTitle: 'Contractors & Supply Chain',
    summary: 'Ethical sourcing, fair labour standards, environmental compliance, and anti-corruption requirements for suppliers and material vendors.',
    metaDescription: 'EntireFM Supplier Code of Conduct: Ethical procurement, prompt payment standards, and environmental requirements.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Zero tolerance for child labour, forced labour, and modern slavery across all supply tiers.',
      'Transparent payment practices settled strictly in accordance with agreed written purchase orders and contract terms.',
      'Compliance with UK environmental, waste transfer, and packaging regulations.',
    ],

    relatedSlugs: ['modern-slavery', 'anti-bribery', 'environment', 'contractor-terms'],
    sections: [
      {
        id: 'ethical-procurement',
        heading: '1. Ethical Procurement & Human Rights',
        body: 'EntireFM requires all suppliers of materials, equipment, and plant to uphold the highest ethical standards, pay statutory minimum/living wages, and prohibit any form of modern slavery or forced labour.',
      },
      {
        id: 'environmental-standards',
        heading: '2. Environmental Responsibility & Waste',
        body: 'Suppliers must minimize single-use packaging, provide valid Waste Transfer Notes for hazardous materials, and support energy-efficient and recyclable equipment sourcing.',
      },
      {
        id: 'anti-corruption',
        heading: '3. Anti-Bribery & Fair Competition',
        body: 'Suppliers must strictly comply with the Bribery Act 2010. Offering gifts, hospitality, or improper inducements to EntireFM procurement staff is grounds for immediate contract termination.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 15. CLIENT COMPLAINTS PROCEDURE
  // ─────────────────────────────────────────────────────────────────────────────
  'complaints': {
    slug: 'complaints',
    title: 'Commercial Complaints Handling Procedure',
    eyebrow: 'Clients & Commercial Terms',
    categorySlug: 'clients',
    categoryTitle: 'Clients & Commercial Terms',
    summary: 'Structured procedure for commercial clients to raise operational, billing, or SLA service concerns, with defined escalation paths and executive review.',
    metaDescription: 'EntireFM Commercial Complaints Procedure: Service dispute escalation, SLA reviews, and executive resolution.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Formal acknowledgment of all service complaints within 2 business days.',
      'Stage 1 operational review by Account Manager within 5 business days.',
      'Stage 2 executive escalation to Operations Director within 10 business days.',
      'Independent mediation option if amicable resolution cannot be reached.',
    ],
    relatedSlugs: ['terms-of-business', 'data-protection-complaints', 'whistleblowing'],
    sections: [
      {
        id: 'complaints-framework',
        heading: '1. Purpose & Scope',
        body: 'EntireFM is committed to operational excellence. When service issues arise, we resolve them transparently, objectively, and promptly in accordance with this 3-stage procedure.',
      },
      {
        id: 'stage-1-operational',
        heading: '2. Stage 1: Account Management Review',
        body: 'Submit your concern to your designated Account Manager or helpdesk@entirefm.com. We acknowledge receipt within 2 business days and conduct an operational review with an action plan within 5 business days.',
      },
      {
        id: 'stage-2-executive',
        heading: '3. Stage 2: Director-Level Escalation',
        body: 'If you are unsatisfied with Stage 1, the matter is escalated to the Operations Director or Head of Compliance for comprehensive contract review and executive meeting within 10 business days.',
      },
      {
        id: 'stage-3-mediation',
        heading: '4. Stage 3: Alternative Dispute Resolution',
        body: 'Where a commercial dispute remains unresolved following Stage 2, parties agree to explore independent alternative dispute resolution or professional mediation prior to initiating formal litigation.',
      },

    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 16. MODERN SLAVERY STATEMENT
  // ─────────────────────────────────────────────────────────────────────────────
  'modern-slavery': {
    slug: 'modern-slavery',
    title: 'Modern Slavery & Human Trafficking Statement',
    eyebrow: 'Governance, Ethics & Conduct',
    categorySlug: 'governance-ethics',
    categoryTitle: 'Governance, Ethics & Conduct',
    summary: 'Voluntary corporate statement and anti-slavery policy establishing our commitment to preventing modern slavery and human trafficking across all FM supply chains.',
    metaDescription: 'EntireFM Modern Slavery & Human Trafficking Statement: Supply chain due diligence, contractor vetting, and ethical standards.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Corporate anti-slavery policy voluntarily adopted to prevent forced labour across all FM supply chains.',
      'Mandatory Right to Work and identity checks for all direct staff and subcontractor operatives.',
      'Supply chain risk profiling across high-risk FM trades (cleaning, waste, construction).',
      'Confidential whistleblowing channels for reporting suspected exploitation.',
    ],
    relatedSlugs: ['supplier-code', 'contractor-code', 'whistleblowing', 'anti-bribery'],
    sections: [
      {
        id: 'corporate-commitment',
        heading: '1. Corporate Commitment & Policy Scope',
        body: 'EntireFM enforces zero tolerance for modern slavery, servitude, forced labour, and human trafficking in our business operations and supply chain. EntireFM falls below the statutory turnover threshold for mandatory reporting under Section 54 of the Modern Slavery Act 2015; however, we have voluntarily adopted this policy to enforce rigorous due diligence and ethical standards across all supply chain tiers.',
      },

      {
        id: 'supply-chain-due-diligence',
        heading: '2. Supply Chain Risk Assessment & Due Diligence',
        body: 'We recognize that facilities management sub-sectors such as commercial cleaning, waste handling, and building labour carry inherent supply chain risks. We enforce strict pre-qualification audits, verify direct bank payment details to eliminate intermediary exploitation, and conduct spot-check site audits.',
      },
      {
        id: 'reporting-and-whistleblowing',
        heading: '3. Reporting Suspicions & Non-Retaliation',
        body: 'Employees, contractors, or suppliers who suspect modern slavery within our operations are encouraged to report concerns immediately via our Whistleblowing channel or to the Modern Slavery Helpline on 08000 121 700.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 17. ANTI-BRIBERY & CORRUPTION POLICY
  // ─────────────────────────────────────────────────────────────────────────────
  'anti-bribery': {
    slug: 'anti-bribery',
    title: 'Anti-Bribery & Corruption Policy',
    eyebrow: 'Governance, Ethics & Conduct',
    categorySlug: 'governance-ethics',
    categoryTitle: 'Governance, Ethics & Conduct',
    summary: 'Corporate compliance framework under the Bribery Act 2010 prohibiting bribes, kickbacks, facilitation payments, and improper corporate hospitality.',
    metaDescription: 'EntireFM Anti-Bribery Policy: Bribery Act 2010 compliance, gifts register, procurement integrity, and zero tolerance.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Strict compliance with the UK Bribery Act 2010; zero tolerance for corruption.',
      'Prohibits facilitation payments and kickbacks across all procurement and contractor selection.',
      'Mandatory corporate hospitality register for all non-trivial gifts and entertainment.',
      'Protection and confidentiality for whistleblowers reporting corrupt practices.',
    ],
    relatedSlugs: ['modern-slavery', 'whistleblowing', 'supplier-code', 'contractor-terms'],
    sections: [
      {
        id: 'policy-statement',
        heading: '1. Policy Statement & Bribery Act 2010',
        body: 'EntireFM conducts all business in an honest, ethical, and transparent manner. We take a zero-tolerance approach to bribery and corruption and are committed to enforcing effective systems to counter bribery under the Bribery Act 2010.',
      },
      {
        id: 'prohibited-conduct',
        heading: '2. Bribes, Kickbacks & Facilitation Payments',
        body: 'No employee, contractor, or agent shall offer, promise, give, request, agree to receive, or accept any bribe, financial inducement, or facilitation payment to secure an improper commercial advantage.',
      },
      {
        id: 'gifts-and-hospitality',
        heading: '3. Gifts, Hospitality & Register Governance',
        body: 'Modest and proportionate corporate hospitality is acceptable only where customary and legitimate. All gifts, hospitality, or entertainment must be transparent, reasonable, and formally recorded in the Corporate Hospitality Register. Offering or accepting anything intended to improperly influence decisions is strictly prohibited.',
      },
    ],

  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 18. WHISTLEBLOWING POLICY
  // ─────────────────────────────────────────────────────────────────────────────
  'whistleblowing': {
    slug: 'whistleblowing',
    title: 'Whistleblowing & Speak-Up Policy',
    eyebrow: 'Governance, Ethics & Conduct',
    categorySlug: 'governance-ethics',
    categoryTitle: 'Governance, Ethics & Conduct',
    summary: 'Confidential reporting procedure protecting employees, contractors, and suppliers who make public interest disclosures under the Public Interest Disclosure Act 1998.',
    metaDescription: 'EntireFM Whistleblowing Policy: Confidential speak-up channels, statutory protection, and non-retaliation guarantee.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Provides a safe, confidential route to report serious wrongdoing, fraud, safety risks, or illegality.',
      'Distinguishes public interest whistleblowing from personal employment grievances.',
      'Guarantees absolute protection against victimisation or detriment for protected disclosures.',
      'Direct confidential reporting route to compliance@entirefm.com.',
    ],
    relatedSlugs: ['anti-bribery', 'modern-slavery', 'health-safety', 'complaints'],
    sections: [
      {
        id: 'purpose-and-qualifying-disclosures',
        heading: '1. Qualifying Disclosures & Scope',
        body: 'This policy enables individuals to report suspected criminal offenses, health & safety dangers, environmental damage, miscarriages of justice, or deliberate concealment of wrongdoing with complete confidence.',
      },
      {
        id: 'confidential-reporting-channels',
        heading: '2. How to Raise a Concern',
        body: `Disclosures should be directed to the Head of Compliance at ${LEGAL_CONFIG.complianceOfficer.email} or by confidential post. Disclosures can be made anonymously and will be investigated thoroughly.`,
      },
      {
        id: 'protection-against-detriment',
        heading: '3. Protection Against Retaliation',
        body: 'EntireFM guarantees that no employee or contractor will suffer dismissal, disciplinary action, or commercial detriment for raising a genuine public interest concern under the Employment Rights Act 1996 / PIDA.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 19. HEALTH & SAFETY POLICY
  // ─────────────────────────────────────────────────────────────────────────────
  'health-safety': {
    slug: 'health-safety',
    title: 'Health, Safety & Welfare Policy',
    eyebrow: 'Safety & Sustainability',
    categorySlug: 'safety-sustainability',
    categoryTitle: 'Safety & Sustainability',
    summary: 'Corporate policy statement, organisation, and arrangements under the Health and Safety at Work etc. Act 1974, CDM 2015, and Asbestos Regulations.',
    metaDescription: 'EntireFM Health & Safety Policy: HASAWA 1974 compliance, CDM 2015 arrangements, competent person oversight, and safe systems of work.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Formal policy under Section 2(3) Health and Safety at Work etc. Act 1974.',
      'Comprehensive safe systems of work covering high-risk FM trades (HVAC, Gas, Electrical, Heights).',
      'Strict asbestos management and disclosure protocols prior to intrusive works.',
      'Does not purport to transfer statutory Dutyholder liabilities from clients or building owners.',
    ],
    relatedSlugs: ['contractor-terms', 'environment', 'work-order-terms'],
    sections: [
      {
        id: 'general-statement',
        heading: '1. General Statement of Health & Safety Intent',
        body: 'EntireFM is committed to ensuring the health, safety, and welfare of our employees, contractors, clients, building occupants, and members of the public who may be affected by our facilities management operations.',
      },
      {
        id: 'organisation-and-competence',
        heading: '2. Organisation, Competent Persons & CDM 2015',
        body: 'Executive health & safety accountability rests with our Directors, supported by qualified Competent Persons (NEBOSH/IOSH). Where maintenance works constitute construction under CDM Regulations 2015, we plan, manage, and monitor works accordingly.',
      },
      {
        id: 'high-risk-activities',
        heading: '3. Safe Systems of Work for High-Risk Activities',
        body: 'Mandatory Risk Assessments and Method Statements (RAMS) are enforced across all high-risk operational areas:',
        bullets: [
          'Working at Height: Strict hierarchy of control, certified access equipment, PASMA/IPAF qualifications.',
          'Electrical Safety: Works executed to BS 7671 standards by NICEIC/approved engineers with safe isolation procedures.',
          'Commercial Gas: Gas Safe registered engineers complying with Gas Safety (Installation and Use) Regulations.',
          'Hazardous Substances (COSHH): Safety Data Sheets and appropriate PPE for industrial cleaning and chemical handling.',
          'Asbestos Protocol: Operatives must review site Asbestos Registers; invasive works stop immediately if suspect materials are identified.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 20. ENVIRONMENTAL & SUSTAINABILITY POLICY
  // ─────────────────────────────────────────────────────────────────────────────
  'environment': {
    slug: 'environment',
    title: 'Environmental & Sustainability Policy',
    eyebrow: 'Safety & Sustainability',
    categorySlug: 'safety-sustainability',
    categoryTitle: 'Safety & Sustainability',
    summary: 'Operational environmental principles governing energy optimization, carbon reduction, F-Gas refrigerant recovery, circular maintenance, and statutory waste management.',
    metaDescription: 'EntireFM Environmental Policy: Circular maintenance, energy efficiency, F-Gas compliance, and waste duty of care.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Promotes "Repair-before-Replace" engineering to extend building asset life and cut embodied carbon.',
      'Full compliance with F-Gas regulations for refrigerant recovery and leak containment.',
      'Enforces statutory Waste Duty of Care with licensed carrier consignment notes.',
      'Factual environmental policy avoiding unverified Net Zero claims.',
    ],
    relatedSlugs: ['health-safety', 'supplier-code', 'contractor-terms'],
    sections: [
      {
        id: 'environmental-commitment',
        heading: '1. Environmental Commitment & Core Principles',
        body: 'EntireFM recognizes our responsibility to minimize environmental impacts across our estate operations and mobile engineering fleet. We promote energy efficiency, responsible material sourcing, and waste reduction.',
      },
      {
        id: 'circular-maintenance',
        heading: '2. Circular Maintenance: Repair Before Replace',
        body: 'We prioritize asset refurbishment, precision PPM, and component-level repair over premature equipment disposal, reducing embodied carbon and maximizing lifecycle value for clients.',
      },
      {
        id: 'waste-and-refrigerants',
        heading: '3. Waste Duty of Care & F-Gas Controls',
        body: 'All hazardous waste, electrical equipment (WEEE), and chemical residues are handled by licensed waste carriers with full statutory consignment notes. Refrigeration servicing complies strictly with F-Gas leak-check and recovery mandates.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 21. EQUALITY, DIVERSITY & INCLUSION POLICY
  // ─────────────────────────────────────────────────────────────────────────────
  'equality': {
    slug: 'equality',
    title: 'Equality, Diversity & Inclusion Policy',
    eyebrow: 'Governance, Ethics & Conduct',
    categorySlug: 'governance-ethics',
    categoryTitle: 'Governance, Ethics & Conduct',
    summary: 'Commitment to equal opportunity, non-discrimination under the Equality Act 2010, fair treatment in contractor selection, and inclusive workplace practices.',
    metaDescription: 'EntireFM Equality, Diversity & Inclusion Policy: Equality Act 2010 compliance, fair treatment, and inclusive workplaces.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Strict adherence to Equality Act 2010 across all 9 protected characteristics.',
      'Fair, merit-based contractor selection and employment practices.',
      'Commitment to reasonable adjustments for employees, clients, and portal users.',
    ],
    relatedSlugs: ['accessibility', 'contractor-code', 'whistleblowing'],
    sections: [
      {
        id: 'equality-statement',
        heading: '1. Policy Statement & Protected Characteristics',
        body: 'EntireFM is committed to eliminating discrimination and encouraging diversity across our workforce, contractor network, and client engagements in accordance with the Equality Act 2010.',
      },
      {
        id: 'fair-procurement',
        heading: '2. Fair Procurement & Employment',
        body: 'Recruitment, contractor selection, and promotion decisions are based solely on merit, qualifications, and operational capability, without regard to age, disability, gender reassignment, marriage, pregnancy, race, religion, sex, or sexual orientation.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 22. ACCESSIBILITY STATEMENT
  // ─────────────────────────────────────────────────────────────────────────────
  'accessibility': {
    slug: 'accessibility',
    title: 'Digital Accessibility Statement',
    eyebrow: 'Using EntireFM',
    categorySlug: 'using-entirefm',
    categoryTitle: 'Using EntireFM',
    summary: 'Audited accessibility commitments for EntireFM digital portals, tools, and websites aligned with WCAG 2.2 Level AA guidelines.',
    metaDescription: 'EntireFM Digital Accessibility Statement: WCAG 2.2 AA alignment, keyboard navigation, and accessibility reporting channels.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Committed to achieving and maintaining WCAG 2.2 Level AA accessibility.',
      'Features high-contrast typography, full keyboard navigability, and screen-reader support.',
      'Dedicated reporting channel to assist users experiencing accessibility barriers.',
    ],
    relatedSlugs: ['terms-of-use', 'equality', 'privacy'],
    sections: [
      {
        id: 'accessibility-commitment',
        heading: '1. Accessibility Standards (WCAG 2.2 AA)',
        body: 'EntireFM is committed to ensuring digital accessibility for people of all abilities. We continuously improve user experience by applying relevant Web Content Accessibility Guidelines (WCAG 2.2 Level AA).',
      },
      {
        id: 'compliance-measures',
        heading: '2. Technical Measures Implemented',
        body: 'Our platform implements semantic HTML structures, distinct focus indicators, high color contrast (minimum 4.5:1 for body copy), scalable typography, and ARIA attributes for complex components such as modal dialogs and navigation drawers.',
      },
      {
        id: 'reporting-barriers',
        heading: '3. Reporting Accessibility Issues',
        body: `If you encounter an accessibility barrier or require content in an alternative format, please email ${LEGAL_CONFIG.dataProtectionOfficer.email} or call ${LEGAL_CONFIG.dataProtectionOfficer.phone}. We aim to respond within 3 business days.`,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 23. INFORMATION SECURITY POLICY
  // ─────────────────────────────────────────────────────────────────────────────
  'security': {
    slug: 'security',
    title: 'Information Security & Trust Overview',
    eyebrow: 'Privacy & Data Protection',
    categorySlug: 'privacy-data',
    categoryTitle: 'Privacy & Data Protection',
    summary: 'High-level security overview covering database encryption, role-based access controls, tenant isolation, automated backups, and vulnerability management.',
    metaDescription: 'EntireFM Information Security Overview: Encryption, tenant isolation, access control, and incident response architecture.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Multi-tenant database isolation preventing cross-organization data leakage.',
      'Data encrypted in transit (TLS 1.3) and at rest (AES-256).',
      'Cryptographically signed HMAC authentication sessions with live revocation.',
      'Regular automated backups and business continuity redundancy.',
    ],
    relatedSlugs: ['privacy', 'data-protection', 'acceptable-use', 'subprocessors'],
    sections: [
      {
        id: 'security-principles',
        heading: '1. Information Security Architecture',
        body: 'EntireFM protects client, contractor, and operational data through a defense-in-depth security model encompassing physical, network, database, and application controls.',
      },
      {
        id: 'encryption-and-storage',
        heading: '2. Encryption & Data Storage',
        body: 'All communications are encrypted in transit using modern TLS 1.3 encryption. Data stored in our database and document vault is encrypted at rest using industry-standard AES-256 encryption within UK datacenters (AWS London).',
      },
      {
        id: 'access-control-and-isolation',
        heading: '3. Identity, Access Control & Tenant Isolation',
        body: 'User access is governed by strict Role-Based Access Control (RBAC) and object-level membership scoping. Cross-tenant access is blocked at the database query boundary. Sessions are cryptographically signed with HMAC SHA-256 tokens.',
      },
      {
        id: 'resilience-and-backups',
        heading: '4. Backup Redundancy & Business Continuity',
        body: 'Databases are backed up automatically with point-in-time recovery capabilities. Disaster recovery protocols ensure high availability and business continuity for critical FM dispatch and compliance operations.',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 24. CORPORATE & REGULATORY DISCLOSURES
  // ─────────────────────────────────────────────────────────────────────────────
  'disclosures': {
    slug: 'disclosures',
    title: 'Corporate & Regulatory Disclosures',
    eyebrow: 'Artificial Intelligence & Technology',
    categorySlug: 'ai-technology',
    categoryTitle: 'Artificial Intelligence & Technology',
    summary: 'Statutory company information, Companies Act disclosures, regulatory references, insurance details, and official governance contacts.',
    metaDescription: 'EntireFM Corporate & Regulatory Disclosures: Companies Act 2006 compliance, registered details, and insurance schedules.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'Authoritative Companies Act 2006 statutory trading and registration disclosures.',
      'Operating Entity: Alkota Group Limited trading as EntireFM (Company No. 13535215).',
      'Official governance channels and registered office address details.',
    ],
    relatedSlugs: ['terms-of-use', 'terms-of-business', 'privacy'],
    sections: [
      {
        id: 'statutory-company-details',
        heading: '1. Statutory Company Details (Companies Act 2006)',
        body: `Legal Name: ${LEGAL_CONFIG.legalName}. Trading Name: ${LEGAL_CONFIG.tradingStatement}. Registered in ${LEGAL_CONFIG.statutoryJurisdiction} under Company Number ${LEGAL_CONFIG.companyNumber}.`,
        bullets: [
          `Registered Office: ${LEGAL_CONFIG.registeredOffice.addressLines.join(', ')}, ${LEGAL_CONFIG.registeredOffice.city}, ${LEGAL_CONFIG.registeredOffice.postcode}, ${LEGAL_CONFIG.registeredOffice.country}.`,
          `Statutory Jurisdiction: Incorporated under the laws of ${LEGAL_CONFIG.statutoryJurisdiction}.`,
        ],
      },
      {
        id: 'insurance-schedule',
        heading: '2. Commercial Insurance Arrangements',
        body: 'EntireFM maintains commercial insurances covering employers’ liability, public liability, and professional indemnity appropriate to our facilities management operations. Verified broker verification letters and policy schedules are provided directly to clients during contract mobilisation.',
      },
      {
        id: 'contact-channels',
        heading: '3. Official Governance & Legal Contacts',
        body: `Commercial Enquiries: ${LEGAL_CONFIG.dataProtectionOfficer.phone} | Legal & Data Protection: ${LEGAL_CONFIG.dataProtectionOfficer.email} | Compliance Desk: ${LEGAL_CONFIG.complianceOfficer.email}.`,
      },
    ],

  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 25. COMMUNITY GUIDELINES (LOBBY MEMBER COMMUNITY)
  // ─────────────────────────────────────────────────────────────────────────────
  'community-guidelines': {
    slug: 'community-guidelines',
    title: 'Community Guidelines',
    eyebrow: 'The Lobby Community',
    categorySlug: 'community',
    categoryTitle: 'Community',
    summary: 'The behavioural standards, moderation principles and participation expectations for all members of The Lobby — EntireFM\'s professional FM intelligence community.',
    metaDescription: 'EntireFM Lobby Community Guidelines: participation standards, moderation approach and member expectations for the UK FM professional community.',
    effectiveDate: '2026-01-01',
    version: '2026.1',
    keyTakeaways: [
      'The Lobby community is for UK FM professionals. All contributions should be relevant, constructive and professional.',
      'Harassment, hate speech, spam and self-promotion without disclosure are prohibited.',
      'EntireFM reserves the right to remove content or suspend accounts that violate these guidelines.',
      'Content you post remains your intellectual property, but you grant EntireFM a licence to display it within The Lobby.',
    ],
    relatedSlugs: ['acceptable-use', 'privacy', 'terms-of-use'],
    sections: [
      {
        id: 'purpose',
        heading: '1. Purpose of The Lobby Community',
        body: 'The Lobby is a professional intelligence space for UK facilities management practitioners, compliance officers, building services engineers and property managers. It is designed to facilitate the sharing of industry knowledge, compliance insight, technical expertise and professional opinion in a constructive and respectful environment.',
      },
      {
        id: 'who-can-participate',
        heading: '2. Who Can Participate',
        body: 'The Lobby community is open to individuals who have registered a Lobby Member account. Membership is free. We particularly welcome contributions from practising FM professionals, though membership is not restricted to those working in the sector. Organisations may not post through a shared account — one account per individual applies.',
      },
      {
        id: 'expected-conduct',
        heading: '3. Expected Conduct',
        body: 'Members are expected to engage in a professional, constructive and respectful manner at all times. Specifically, you must:',
        bullets: [
          'Be honest and accurate: Only share information you believe to be true. If you are uncertain, say so. Correct your mistakes when you identify them.',
          'Be respectful: Disagree with ideas, not with people. Personal attacks, insults, harassment and targeted abuse of any kind are prohibited.',
          'Be relevant: Keep contributions relevant to facilities management, compliance, building services, property management or related professional topics.',
          'Disclose affiliations: If you mention a product, service or employer in which you have a financial interest, disclose this clearly.',
          'Respect confidentiality: Do not post confidential client information, unreleased contract details or personal data belonging to third parties.',
        ],
      },
      {
        id: 'prohibited-content',
        heading: '4. Prohibited Content',
        body: 'The following content will be removed and may result in account suspension:',
        bullets: [
          'Hate speech, discriminatory language or content targeting individuals on the basis of protected characteristics.',
          'Harassment, threats, stalking or sustained personal attacks against any individual.',
          'Spam, unsolicited commercial promotion or repetitive off-topic posts.',
          'Misinformation: content that is factually false and likely to cause harm or mislead other members on compliance or safety matters.',
          'Content that infringes copyright, trademarks or other intellectual property rights.',
          'Personally identifiable information about third parties posted without their consent.',
          'Content that is unlawful under English and Welsh law.',
        ],
      },
      {
        id: 'moderation',
        heading: '5. Moderation',
        body: 'EntireFM moderates The Lobby community. We operate a report-and-review model: members can flag content they believe violates these guidelines. Flagged content is reviewed by the editorial team. We aim to review flagged content within 2 business days. Our moderation decisions are final, though members may appeal by contacting us at lobby@entirefm.com.',
        callout: {
          type: 'practical',
          title: 'Moderation approach',
          content: 'We aim to be proportionate. A first minor violation will typically result in a private message and content edit request. Severe violations — including harassment, hate speech and intentional misinformation — may result in immediate account suspension without prior warning.',
        },
      },
      {
        id: 'intellectual-property',
        heading: '6. Intellectual Property',
        body: 'Content you post in The Lobby remains your intellectual property. By posting, you grant EntireFM a non-exclusive, royalty-free licence to display, distribute and archive that content within The Lobby and its communications (such as the FM Briefing digest). You may request removal of your content at any time by contacting lobby@entirefm.com.',
      },
      {
        id: 'changes',
        heading: '7. Changes to These Guidelines',
        body: 'EntireFM may update these Community Guidelines as The Lobby develops. Significant changes will be communicated to registered Members by email. Continued participation in The Lobby community after notification of changes constitutes acceptance of the updated guidelines.',
      },
    ],
  },
};

/**
 * Get policy by slug
 */
export function getLegalPolicy(slug: string): LegalPolicy | null {
  return LEGAL_POLICIES[slug] || null;
}

/**
 * Generate TOC items for a policy
 */
export function getPolicyTocItems(policy: LegalPolicy): TocItem[] {
  return policy.sections.map((sec) => ({
    id: sec.id,
    title: sec.heading,
  }));
}
